### ISSUE TITLE
svyarpt linearization technique does not account for records outside of the subset

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#1]
https://github.com/DjalmaPessoa/convey/blob/master/all_funs.R#L267-L289

	# CORRECT method to break out by groups
	dati <- data.frame(IDd = 1:nrow(eusilc), eusilc)
	d1 <- linarpt(Y="eqIncome", id="IDd", weight = "rb050", Dom = "db040",
	  dataset = dati, percentage = 60, order_quant=50)

	# INCORRECT SUBSET
	ics <- subset(dati,db040=='Tyrol')
	d2 <- linarpt(Y="eqIncome", id="IDd", weight = "rb050", Dom = NULL,
	  dataset = ics , percentage = 60, order_quant=50)

	# your function matches the incorrect subsetting technique
	d3 <-  svyarpt(~eqIncome, subset( des_eusilc , db040 == 'Tyrol' ) , .5, .6)

	# this is the correct way to use `linarpt`
	table( d1$lin$lin_arpt__db040.Tyrol )
	# NOTICE that the zeroes are maintained!

	# this is the incorrect way to use `linarpt`
	summary(d2$lin)

	# your function matches the incorrect method
	table(d3$lin)

**Comment by DjalmaPessoa** [comment]
# I thought this was done by svyby:
# to estimate in the domain db040=='Tyrol' , create the new variable:

dom_tyrol<- eusilc$eqIncome*(eusilc$db040=="Tyrol")

# update the design
des_eusilc <- update(des_eusilc,dom_tyrol=dom_tyrol)

#  use  svyarpt for the variable dom_tyrol with the design des_eusilc
arpt_dom_tyrol<-svyarpt(~dom_tyrol, des_eusilc)

#  svyby shhould this for each domain.
#  the function svyarpt uses the whole data frame eusilc, including the
lines  with 0  in the variable dom_tyrol
