### ISSUE TITLE
can SE_lin and SE_lin2 be collapsed into a single function?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#10]
they are currently in two separate locations:

https://github.com/DjalmaPessoa/convey/blob/master/R/all_funs.R#L342

https://github.com/DjalmaPessoa/convey/blob/master/R/all_funs.R#L436

**Comment by ajdamico** [comment]
i believe you might have done this?  but now i am not sure that `SE_lin2` should exist at all if we can avoid it?

**Comment by DjalmaPessoa** [comment]
What do you suggest? To compute directly the variance inside each function?
The `SE_lin2` just avoids repetitions.

**Comment by ajdamico** [comment]
have you completely removed `SE_lin`?  if so, could you close this issue?

**Comment by DjalmaPessoa** [comment]
yes.
