### ISSUE TITLE
add expect_equal() linearized and replicate-weighted coefficients and near-equal for SEs

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#100]
confirm with subsets too.  coefficients should always match.  SEs should have a little room to be different

**Comment by DjalmaPessoa** [comment]
shoul this be done for the 0.1.0 version?

**Comment by ajdamico** [comment]
i think you should put 0.1.0 on cran as soon as we hear from hannes.  i set
the milestone to 0.2.0 for this issue

**Comment by DjalmaPessoa** [comment]
the tests for equality of coefficients are already include in the files
test-extract. There is no comparison for se estimates. As an example, look
at test-extract_svyapr.R. We would have to fix a  proximity to compare se.

**Comment by DjalmaPessoa** [comment]
It is easy to include some tests to compare se from linearized and replicate designs. Should I, right now?

**Comment by DjalmaPessoa** [comment]
I just made a commit comparing the se from linearized and replicate designs for svyarpt. See in test-extract_svyapr.R if it is ok.
If so, I can introduce it for the other functions

**Comment by ajdamico** [comment]
hi, that looks great.  one additional thing needs to be added everywhere:
the database-backed linearized design SE and coefs must be precisely equal
to the in-memory design.  i think once you add that test as well, it is
okay to expand it to all functions

**Comment by DjalmaPessoa** [comment]
When trying to use the database-backed linearized design for domains I got a bad surprise:

svyby(~ eqincome, by = ~db040, design = dbd_eusilc, FUN = svyarpr, order = 0.5, percent = 0.6,deff = FALSE)

could you help me to fix it?

**Comment by ajdamico** [comment]
@DjalmaPessoa is this complete?  if so, please close..thanks

**Comment by ajdamico** [comment]
duplicate of https://github.com/DjalmaPessoa/convey/issues/102
