### ISSUE TITLE
database-backed svyby() on svyarpr() breaks

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#101]
library(survey)
	library(convey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	# database-backed design
	library(MonetDBLite)
	library(DBI)
	dbfolder <- tempdir()
	conn <- dbConnect( MonetDBLite::MonetDBLite() , dbfolder )
	dbWriteTable( conn , 'eusilc' , eusilc )

	dbd_eusilc <-
		svydesign(
			ids = ~rb030 ,
			strata = ~db040 , 
			weights = ~rb050 ,
			data="eusilc",
			dbname=dbfolder,
			dbtype="MonetDBLite"
		)

	dbd_eusilc <- convey_prep( dbd_eusilc )

	svyby( ~eqincome, by = ~db040, design = dbd_eusilc, FUN = svyarpr, order = 0.5, percent = 0.6,deff = FALSE)

**Comment by DjalmaPessoa** [comment]
This is working:
svyarpr( ~ eqincome , design = subset(dbd_eusilc, db040=="Tyrol") )

**Comment by DjalmaPessoa** [comment]
I've checked for other functions and it seems to be working for functions not depending on arpt, the global  tthreshold.

**Comment by ajdamico** [comment]
works now!  thanks
