### ISSUE TITLE
add subset vs svyby vs dbi-subset vs dbi-svyby testthats to all functions

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#102]
library(convey)
	library(survey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	# linearized design
	des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
	des_eusilc <- convey_prep( des_eusilc )

	# database-backed design
	library(MonetDBLite)
	library(DBI)
	dbfolder <- tempdir()
	conn <- dbConnect( MonetDBLite::MonetDBLite() , dbfolder )
	dbWriteTable( conn , 'eusilc' , eusilc )

	dbd_eusilc <-
		svydesign(
			ids = ~rb030 ,
			strata = ~db040 , 
			weights = ~rb050 ,
			data="eusilc",
			dbname=dbfolder,
			dbtype="MonetDBLite"
		)

	dbd_eusilc <- convey_prep( dbd_eusilc )

	svyarpr( ~eqincome , design = subset( des_eusilc , db040 == "Burgenland" ) )
	svyby( ~eqincome, by = ~db040, design = des_eusilc, FUN = svyarpr)

	svyby( ~eqincome, by = ~db040, design = dbd_eusilc, FUN = svyarpr)
	svyarpr( ~ eqincome , design = subset(dbd_eusilc, db040=="Burgenland") )

**Comment by ajdamico** [comment]
`model.frame` for incvar is returning the full design rather than the subset

**Comment by DjalmaPessoa** [comment]
Please run: 
  
  library(convey)
testthat::test_file("C:/Users/owner/Documents/GitHub/convey/tests/testthat/test-extract_svygpg.R")

and see what is going on

**Comment by ajdamico** [comment]
we should add the four comparisons above to testthat for all functions -- not just svyarpt

subset vs svyby vs dbi-subset vs dbi-svyby

please reassign to me if you prefer

**Comment by ajdamico** [comment]
we should do these four comparisons for both svydesign objects and separately for svrepdesign objects

**Comment by DjalmaPessoa** [comment]
svrepdesign just to compare the point estimates?

**Comment by ajdamico** [comment]
but also compare these four across svrepdesigns:

subset vs svyby vs dbi-subset vs dbi-svyby

after you have the four pairs of comparisons, then one coefficient comparison across svrepdesign vs svydesign and perhaps a second that just tests that the SEs are within some small range of one another.  so ten tests in total for each function?

**Comment by DjalmaPessoa** [comment]
please just complete the 10 tests for svyarpr in the initial script.

**Comment by ajdamico** [comment]
@DjalmaPessoa i have completed the tests [in this commit](https://github.com/DjalmaPessoa/convey/commit/708bc850b0a73a6f90d71d114290c6ee83554ab8).  i believe each of these comparisons should be replicated across all svy* functions

**Comment by DjalmaPessoa** [comment]
Please check if this is okay. Is there anymore?
    
 context("Arpr output survey.design and svyrep.design")
          library(vardpoor)
          library(survey)
          data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
          
          des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
          des_eusilc <- convey_prep(des_eusilc)
          des_eusilc_rep <-as.svrepdesign(des_eusilc, type= "bootstrap")
          des_eusilc_rep <- convey_prep(des_eusilc_rep)
          a1 <- svyarpr(~eqincome, design = des_eusilc, 0.5, 0.6)
          
          a2 <- svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyarpr, order = 0.5, percent = 0.6,deff = FALSE)
          
          a3 <- svyarpr(~eqincome, design = subset(des_eusilc, db040 == "Tyrol"), 0.5, 0.6)
          
          b1 <- svyarpr(~eqincome, design = des_eusilc_rep, 0.5, 0.6)
          
          b2 <- svyby(~eqincome, by = ~db040, design = des_eusilc_rep, FUN = svyarpr, order = 0.5, percent = 0.6,deff = FALSE)
          
          b3 <- svyarpr(~eqincome, design = subset(des_eusilc_rep,db040 =="Tyrol"), 0.5, 0.6)
          
          # library(MonetDBLite) is only available on 64-bit machines,
          # so do not run this block of code in 32-bit R
          if( .Machine$sizeof.pointer > 4 ){
          
            # database-backed design
            library(MonetDBLite)
            library(DBI)
            dbfolder <- tempdir()
            conn <- dbConnect( MonetDBLite::MonetDBLite() , dbfolder )
            dbWriteTable( conn , 'eusilc' , eusilc )
          
            dbd_eusilc <-
              svydesign(
                ids = ~rb030 ,
                strata = ~db040 ,
                weights = ~rb050 ,
                data="eusilc",
                dbname=dbfolder,
                dbtype="MonetDBLite"
              )
            dbd_eusilc <- convey_prep( dbd_eusilc )
          
          
            c1 <- svyarpr( ~ eqincome , design = dbd_eusilc )
            c2 <- svyby(~ eqincome, by = ~db040, design = dbd_eusilc, FUN = svyarpr, order = 0.5, percent = 0.6,deff = FALSE)
            c3 <- svyarpr( ~ eqincome , design = subset(dbd_eusilc, db040=="Tyrol") )
          
            dbRemoveTable( conn , 'eusilc' )
          
          }
          
          
          test_that("database svyarpr",{
            expect_equal(coef(a1), coef(c1))
            expect_equal(coef(a2), coef(c2))
            expect_equal(coef(a3), coef(c3))
            expect_equal(SE(a1), SE(c1))
            expect_equal(SE(a2), SE(c2))
            expect_equal(SE(a3), SE(c3))
          })
          
          test_that("svrep svyarpr",{
            expect_equal(coef(a1), coef(b1))
            expect_equal(coef(a2), coef(b2))
            expect_equal(coef(a3), coef(b3))
            expect_equal(SE(a1), SE(b1)) # approx.
            expect_equal(SE(a2), SE(b2)) # approx
            expect_equal(SE(a3), SE(b3)) # approx
          })

**Comment by ajdamico** [comment]
did you read my commit?

**Comment by DjalmaPessoa** [comment]
Sorry, I just realized that you've already implemented all these tests. Sorry.

**Comment by ajdamico** [comment]
haha cool  :)  i only did svyarpr tho

**Comment by DjalmaPessoa** [comment]
Okay, I'll implement for the other functions

**Comment by DjalmaPessoa** [comment]
For svyfgt we need more tests. Could you help me to organize all these?  we need also to include 
         svyby tests.
      ## type_thresh= "abs"
      
      svyfgt(~eqincome, subset(des_eusilc, db040 == "Burgenland"), g=0,  abs_thresh=10000)
      
      svyfgt(~eqincome, subset(des_eusilc_rep,db040 == "Burgenland"), g=0,  abs_thresh=10000)
      
      svyfgt(~eqincome, subset(dbd_eusilc,db040 == "Burgenland"), g=0, abs_thresh=10000)
      
      svyfgt(~eqincome, subset(des_eusilc, db040 == "Burgenland"), g=1,  abs_thresh=10000)
      
      svyfgt(~eqincome, subset(des_eusilc_rep,db040 == "Burgenland"), g=1,  abs_thresh=10000)
      
      svyfgt(~eqincome, subset(dbd_eusilc,db040 == "Burgenland"), g=1, abs_thresh=10000)
      
      
      ## type_thresh= "relq"
      
      svyfgt(~eqincome, subset(des_eusilc, db040 == "Burgenland"), g=0, type_thresh= "relq")
      
      svyfgt(~eqincome, subset(des_eusilc_rep,db040 == "Burgenland"), g=0, type_thresh= "relq")
      
      svyfgt(~eqincome, subset(dbd_eusilc,db040 == "Burgenland"), g=0,type_thresh= "relq")
      
      svyfgt(~eqincome, subset(des_eusilc, db040 == "Burgenland"), g=1, type_thresh= "relq")
      
      svyfgt(~eqincome, subset(des_eusilc_rep,db040 == "Burgenland"), g=1, type_thresh= "relq")
      
      svyfgt(~eqincome, subset(dbd_eusilc,db040 == "Burgenland"), g=1, type_thresh= "relq")
      
      ## type_thresh= "relm"
      
      svyfgt(~eqincome, subset(des_eusilc, db040 == "Burgenland"), g=0, type_thresh= "relm")
      
      svyfgt(~eqincome, subset(des_eusilc_rep,db040 == "Burgenland"), g=0, type_thresh= "relm")
      
      svyfgt(~eqincome, subset(dbd_eusilc,db040 == "Burgenland"), g=0, type_thresh= "relm")
      
      svyfgt(~eqincome, subset(des_eusilc, db040 == "Burgenland"), g=1, type_thresh= "relm")
      
      svyfgt(~eqincome, subset(des_eusilc_rep,db040 == "Burgenland"), g=1, type_thresh= "relm")
      
      svyfgt(~eqincome, subset(dbd_eusilc,db040 == "Burgenland"), g=1, type_thresh= "relm")

**Comment by ajdamico** [comment]
could you put everything inside two nested for loops?

    for ( this_thresh in c( "abs" , "relm" , "relq" ) ){
        for ( this_g in c( 0 , 1 ) ) {

**Comment by DjalmaPessoa** [comment]
That's a good idea. I'll try that.

**Comment by DjalmaPessoa** [comment]
Please help me to fix test-extract_svyfgt.R , putting dbRemoveTable( conn , 'eusilc' ) in the right place

**Comment by ajdamico** [comment]
i have edited the script so it now runs correctly  :)

**Comment by ajdamico** [comment]
@DjalmaPessoa this has been completed for your functions, so i'll work with @guilhermejacob and get similar tests implemented there

**Comment by ajdamico** [comment]
only svylorenz left to do

**Comment by ajdamico** [comment]
added everywhere
