### ISSUE TITLE
svyzenga breaks on what should be a legal subset

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#108]
once fixed, please revert this commit because these lines should run..  https://github.com/DjalmaPessoa/convey/commit/9eefb947de538fe4a143bb238afab13f5868cee4

minimal reproducible example

	library(convey)
	library(survey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
	des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
	des_eusilc <- convey_prep(des_eusilc)
	svyzenga(~py010n, subset( des_eusilc, py010n > 0 | is.na(py010n)) )

**Comment by guilhermejacob** [comment]
Solved.

**Comment by ajdamico** [comment]
whoops, your commit didn't link for some reason..  https://github.com/DjalmaPessoa/convey/commit/03caf0878721fd2b33024b06e376a663f07d5bf4

also, awesome!  thanks!  reopening and assigning to me to make one more change..

**Comment by ajdamico** [comment]
@guilhermejacob  okay, i have re-enabled a few of the lines from the examples that we had previously commented out.  let's let travis-ci do its magic and check that it now works :)

https://github.com/DjalmaPessoa/convey/commit/24bc4dcebfb91706f1f83dc826c2ff45ba8fa4b1

**Comment by ajdamico** [comment]
nice work.  https://travis-ci.org/DjalmaPessoa/convey/builds/141073932
