### ISSUE TITLE
fix column names for coef and SE

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#11]
library(devtools)
install_github( "djalmapessoa/convey" )

library(convey)
library(vardpoor)
data(eusilc)
library(survey)
des_eusilc <- svydesign(ids=~db040, weights=~rb050, data=eusilc)
des_eusilc <- convey_prep( des_eusilc )
gini_eqIncome <- svygini(~eqIncome, design=des_eusilc)

svygini( ~ eqIncome , des_eusilc )
svyby( ~ eqIncome , ~ rb090 , des_eusilc , svygini )
svygini( ~ eqIncome , subset( des_eusilc , rb090 == 'male' ) )
svygini( ~ eqIncome , subset( des_eusilc , rb090 == 'female' ) )

**Comment by DjalmaPessoa** [comment]
Great!

**Comment by ajdamico** [comment]
works now
