### ISSUE TITLE
figure out why as.svrepdesign on monetdblite locks up a computer

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#112]
do not run this code..  computer will crash

	library(convey)
	library(survey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	# linearized design
	des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
	des_eusilc <- convey_prep( des_eusilc )

	# database-backed design
	library(MonetDBLite)
	library(DBI)
	dbfolder <- tempdir()
	conn <- dbConnect( MonetDBLite::MonetDBLite() , dbfolder )
	dbWriteTable( conn , 'eusilc' , eusilc )

	dbd_eusilc <-
		svydesign(
			ids = ~rb030 ,
			strata = ~db040 , 
			weights = ~rb050 ,
			data="eusilc",
			dbname=dbfolder,
			dbtype="MonetDBLite"
		)

	dbd_eusilc <- convey_prep( dbd_eusilc )
	w <- as.svrepdesign( dbd_eusilc )

**Comment by ajdamico** [comment]
compressed weights.

**Comment by guilhermejacob** [comment]
Sorry, didn't understand how to solve that.

**Comment by ajdamico** [comment]
non-compressed weights create a huge object, adding "bootstrap" as the second parameter solves the issue  :)
