### ISSUE TITLE
database-backed subsetted svyfgt SEs do not match in-memory designs

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#114]
these two lines (currently commented out) in `testthat/test-extract_svyfgt.R` are currently not equal to one another

	expect_equal(SE(sub_des), SE(sub_dbd))

	expect_equal(as.numeric(SE(sub_dbd)), as.numeric(SE(sby_dbd))[1])

here's what the give--

	> sub_des
				fgt0     SE
	eqincome 0.13936 0.0152

	> sub_dbd
				fgt0    SE
	eqincome 0.13936 0.084

minimal reproducible example:

	library(convey)
	library(survey)
	library(vardpoor)

	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	library(convey)
	library(MonetDBLite)
	library(DBI)
	dbfolder <- tempdir()
	conn <- dbConnect( MonetDBLite::MonetDBLite() , dbfolder )
	dbWriteTable( conn , 'eusilc' , eusilc )

	dbd_eusilc <-
		svydesign(
			ids = ~rb030 ,
			strata = ~db040 ,
			weights = ~rb050 ,
			data="eusilc",
			dbname=dbfolder,
			dbtype="MonetDBLite"
		)

	dbd_eusilc <- convey_prep( dbd_eusilc )

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- convey_prep(des_eusilc)
	sub_dbd <- svyfgt( ~eqincome , design = subset( dbd_eusilc , db040 == "Burgenland" ), g=0, type_thresh= "abs", abs_thresh=10000 )
	sby_dbd <- svyby( ~eqincome, by = ~db040, design = dbd_eusilc, FUN = svyfgt ,g=0, type_thresh= "abs", abs_thresh=10000)
	stopifnot(as.numeric(SE(sub_dbd))==as.numeric(SE(sby_dbd))[1])

**Comment by DjalmaPessoa** [comment]
I don't see what's wrong, I got the same values:
> as.numeric(SE(sub_dbd))
[1] 0.01515671
> as.numeric(SE(sby_dbd))[1]
[1] 0.01515671

**Comment by ajdamico** [comment]
i think you are correct  :)
