### ISSUE TITLE
if( !( list(...)[["g"]] %in% c( 0 , 1 ) ) ) stop( "g= must be 0 to estimate the headcount ratio or 1 to estimate the poverty index" )

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#117]
g could be ==0 or  >=1 , the index proposal was for these g values. The function is supposed to work in any of these situations. In practice the most  used values are 0,1,2. The index has  special names for  these cases.

**Comment by ajdamico** [comment]
@DjalmaPessoa could you review my edit to accommodate this?  thanks  https://github.com/DjalmaPessoa/convey/commit/3c2c04e4aee30020dd8ea920d8764c4335dbd442
