### ISSUE TITLE
svyfgt testthat comparisons failing

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#118]
these four lines currently do not match up, according to travis..

https://travis-ci.org/DjalmaPessoa/convey/builds/141373880#L2406-L2409

**Comment by ajdamico** [comment]
hi @DjalmaPessoa could you look at this one in the next few days?  those four lines from the `svyfgt` testthat script is the reason that travis-ci is giving us a build failure..

**Comment by DjalmaPessoa** [comment]
the svyfgt is passing in my computer. I only get 50 warnings:
Mensagens de aviso:
1: package ‘MonetDBLite’ was built under R version 3.3.1
2: 'isIdCurrent' é obsoleto.
Use 'dbIsValid' em seu lugar
Veja help("Deprecated")

how come it is breaking in Travis????

**Comment by DjalmaPessoa** [comment]
When I  just run the test for svyfgt it is passing, but when I run the tests for all functions the svyfgt tests are not passing??? This doesn't make sense!

**Comment by DjalmaPessoa** [comment]
Also, I've noticed that the problem is with the coef which never gave problem before, I used to get mismatches wih  the se??

**Comment by ajdamico** [comment]
the svyfgt tests do not pass.  run only the tests with this:


	devtools::install_github("djalmapessoa/convey")
	library(convey)
	library(testthat)
	library(downloader)
	source_url( "https://raw.githubusercontent.com/DjalmaPessoa/convey/master/tests/testthat/test-extract_svyfgt.R" , echo = TRUE , prompt = FALSE )

**Comment by DjalmaPessoa** [comment]
Please just run:
    library(vardpoor)
    library(survey)
    library(convey)
    data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
    
    des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
    des_eusilc <- convey_prep(des_eusilc)
    des_eusilc_rep <-as.svrepdesign(des_eusilc, type= "bootstrap")
    
    des_eusilc_rep <- convey_prep(des_eusilc_rep)
    
    this_thresh <- "abs"
    this_g <- 0
    
    a2 <- svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyfgt, g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    b2 <- svyby(~eqincome, by = ~db040, design = des_eusilc_rep, FUN = svyfgt,g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    all.equal(coef(a2), coef(b2))
    
    this_thresh <- "abs"
    this_g <- 1
    
    a2 <- svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyfgt, g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    b2 <- svyby(~eqincome, by = ~db040, design = des_eusilc_rep, FUN = svyfgt,g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    all.equal(coef(a2), coef(b2))
    
    this_thresh <- "relq"
    this_g <- 0
    
    a2 <- svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyfgt, g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    b2 <- svyby(~eqincome, by = ~db040, design = des_eusilc_rep, FUN = svyfgt,g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    all.equal(coef(a2), coef(b2))
    
    
    this_thresh <- "relq"
    this_g <- 1
    
    a2 <- svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyfgt, g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    b2 <- svyby(~eqincome, by = ~db040, design = des_eusilc_rep, FUN = svyfgt,g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    all.equal(coef(a2), coef(b2))
    
    this_thresh <- "relm"
    this_g <- 0
    
    a2 <- svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyfgt, g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    b2 <- svyby(~eqincome, by = ~db040, design = des_eusilc_rep, FUN = svyfgt,g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    all.equal(coef(a2), coef(b2))
    
    this_thresh <- "relm"
    this_g <- 1
    
    a2 <- svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyfgt, g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    b2 <- svyby(~eqincome, by = ~db040, design = des_eusilc_rep, FUN = svyfgt,g=this_g, type_thresh= this_thresh, abs_thresh=10000, deff = FALSE)
    
    all.equal(coef(a2), coef(b2))

**Comment by ajdamico** [comment]
@DjalmaPessoa that is not the whole script..  try running the lines that i sent?

**Comment by DjalmaPessoa** [comment]
I can't run devtools::install_github("djalmapessoa/convey") because I'm not able to install MonetDBLite

**Comment by ajdamico** [comment]
not true.  you can install monetdblite with

    install.packages("MonetDBLite")

**Comment by DjalmaPessoa** [comment]
this I can do,  but when I try devtools::install_github("djalmapessoa/convey") it breaks bcause it tries to install MonetDBLite from github

**Comment by ajdamico** [comment]
if you already have MonetDBLite installed,
`devtools::install_github("djalmapessoa/convey")` is not going to
re-install monetdblite..

**Comment by DjalmaPessoa** [comment]
I'll try...

**Comment by DjalmaPessoa** [comment]
> devtools::install_github("djalmapessoa/convey")
Downloading GitHub repo djalmapessoa/convey@master
from URL https://api.github.com/repos/djalmapessoa/convey/zipball/master
Installing convey
Downloading GitHub repo hannesmuehleisen/MonetDBLite@master
from URL https://api.github.com/repos/hannesmuehleisen/MonetDBLite/zipball/master
Error: Could not find build tools necessary to build MonetDBLite

**Comment by ajdamico** [comment]
you need to run this _first_

    install.packages("MonetDBLite")

**Comment by DjalmaPessoa** [comment]
I've already done this before. The library is already installed. Do I need to install from cran each time?

**Comment by ajdamico** [comment]
call on skype?
