### ISSUE TITLE
should all of the svyrep.design functions all have nested functions?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#12]
for example, svyarpr.svyrep.design contains a `ComputeArpr` function

https://github.com/DjalmaPessoa/convey/blob/master/R/svyarpr.R#L119

where it only gets used once within the function.  i'm confused why these aren't placed outside of the svyrep.design functions?  and - since they're only used once - i'm not sure why they need to be functions?  (you may have a good reason)  :)

**Comment by DjalmaPessoa** [comment]
Used to compute estimate replicates. See line 128.

**Comment by DjalmaPessoa** [comment]
I mean line 125! In the apply function. An alternative is to put the function inside the apply.

**Comment by ajdamico** [comment]
completely missed that  :)  thanks!
