### ISSUE TITLE
clean up svylorenz testthat script

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#121]
hi, this script is a start but a lot of these tests should be modified because `svylorenz` defaults are a bit different..  https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-extract_svylorenz.R  assign back to me if you get stuck?  thanks guilherme!

**Comment by guilhermejacob** [comment]
I guess most of it is done. But can you solve the "deff" warning on svyby?

**Comment by ajdamico** [comment]
took me three commits but it's been solved :)  thanks for fixing this test script.  closing but re-open if you disagree
