### ISSUE TITLE
tests have cv of svyisq linearized vs repwgt designs too far apart

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#123]
minimal reproducible example of the problem occurring at line 33 here: https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-extract_svyisq.R#L33

    # convey/tests/testthat/test-extract_svyisq.R

	library(devtools)
	install_github("djalmapessoa/convey")

	library(convey)
	library(testthat)
	library(vardpoor)
	library(survey)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- convey_prep(des_eusilc)
	des_eusilc_rep <- as.svrepdesign(des_eusilc, type= "bootstrap")
	des_eusilc_rep <- convey_prep(des_eusilc_rep)

	a2 <- svyby(~eqincome, by = ~hsize, design = des_eusilc, FUN = svyisq, alpha = .20, deff = FALSE)

	b2 <- svyby(~eqincome, by = ~hsize, design = des_eusilc_rep, FUN = svyisq, alpha = .20, deff = FALSE)

	cv_diff2 <- 100*max(abs(cv(a2)-cv(b2)))

	# fails
	expect_lte(cv_diff2,5)

**Comment by DjalmaPessoa** [comment]
the same comment made for svygini applies here. There are too small domains so does not make any sense to compare cv in those domains. In fact the point estimate  does not make sense.

**Comment by ajdamico** [comment]
could you apply either of the solutions i suggested?
