### ISSUE TITLE
when using svyarpt, the SEs for subsetted, database-backed survey designs do not match in-memory designs nor database-backed svyby results

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#124]
minimal reproducible example from test-extract_svyarpt.R:

	library(devtools)
	install_github("djalmapessoa/convey")

	library(MonetDBLite)
	library(DBI)
	library(convey)
	library(testthat)
	library(vardpoor)
	library(survey)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- convey_prep(des_eusilc)

	# compare subsetted objects to svyby objects
	sub_des <- svyarpt( ~eqincome , design = subset( des_eusilc , hsize == 1) )
	sby_des <- svyby( ~eqincome, by = ~hsize, design = des_eusilc, FUN = svyarpt)
	sub_rep <- svyarpt( ~eqincome , design = subset( des_eusilc_rep , hsize == 1) )
	sby_rep <- svyby( ~eqincome, by = ~hsize, design = des_eusilc_rep, FUN = svyarpt)

	dbfolder <- tempdir()
	conn <- dbConnect( MonetDBLite::MonetDBLite() , dbfolder )
	dbWriteTable( conn , 'eusilc' , eusilc )

	dbd_eusilc <-
		svydesign(
			ids = ~rb030 ,
			strata = ~db040 ,
			weights = ~rb050 ,
			data="eusilc",
			dbname=dbfolder,
			dbtype="MonetDBLite"
		)

	dbd_eusilc <- convey_prep( dbd_eusilc )

	sub_dbd <- svyarpt( ~eqincome , design = subset( dbd_eusilc , hsize == 1) )
	sby_dbd <- svyby( ~eqincome, by = ~hsize, design = dbd_eusilc, FUN = svyarpt)

	dbRemoveTable( conn , 'eusilc' )

	# fails
	expect_equal(SE(sub_des), SE(sub_dbd))

	# fails
	expect_equal(as.numeric(SE(sub_dbd)), as.numeric(SE(sby_dbd))[1])

**Comment by DjalmaPessoa** [comment]
It is possible to fix this problem, But the usual is to compute the arpt just for the whole population. The arpt for the whole population is used in the other indicators (this makes life harder).
But, someone might wish to estimate the arpt for domains, so I think it should be fixed.

**Comment by ajdamico** [comment]
right, the two `expect_equal()` tests above should definitely match :)

**Comment by DjalmaPessoa** [comment]
fixed

**Comment by ajdamico** [comment]
awesome
