### ISSUE TITLE
tests for svyrmir are not working because of NA

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#126]
library(devtools)
install_github("djalmapessoa/convey")

library(MonetDBLite)
library(DBI)
library(convey)
library(testthat)
library(vardpoor)
library(survey)
data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
des_eusilc <- convey_prep(des_eusilc)

# compare subsetted objects to svyby objects
sby_rep <-svyby(~eqincome, by = ~hsize, design = des_eusilc_rep, FUN = svyrmir, age = ~age )

# fails
sum(confint(sby_rep)[, 1] <= coef(sby_rep)) 
# fails
sum(confint(sby_rep)[, 2] >= coef(sby_rep))

**Comment by ajdamico** [comment]
this script isolates the problem?


	library(convey)
	library(vardpoor)
	library(survey)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- convey_prep(des_eusilc)
	des_eusilc_rep <-as.svrepdesign(des_eusilc, type= "bootstrap")
	des_eusilc_rep <- convey_prep(des_eusilc_rep)

	# this should not be NA
	SE( svyrmir( ~eqincome , age=~age,design=subset(des_eusilc_rep,hsize==9)) )
