### ISSUE TITLE
restore svyzenga testthat script after fixing function

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#127]
i just commented out so we could get a passing build..thanks!

https://github.com/DjalmaPessoa/convey/issues/66 and https://github.com/DjalmaPessoa/convey/commit/2d2edd1c638a2fb564d27761e37e3eed9a1c322c

**Comment by guilhermejacob** [comment]
Function fixed!

**Comment by ajdamico** [comment]
thanks!
