### ISSUE TITLE
could each of the svy* functions have one replicate-weighted example as well?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#13]
on the ?help pages, it looks like the examples only show a usage case for the linearized designs?

does it make sense to add an example that shows the functions work properly on replicate-weighted survey design objects as well?

**Comment by DjalmaPessoa** [comment]
yes, this can be done easily. I'll include some examples.

**Comment by DjalmaPessoa** [comment]
I've just included an example with replicate-weight design in the help of
svyarpr. I got the error message:

Error in `rownames<-`(`*tmp*`, value = "eqIncome") :
  attempt to set 'rownames' on an object with no dimensions

the error seems to be in

rownames( variance ) <- names( rval ) <- strsplit( as.character( formula
)[[2]] , ' \\+ ' )[[1]]

**Comment by ajdamico** [comment]
the svrVar() function that you use inside of the svrepdesign functions
returns a numeric vector

the SE_lin2() function returns a matrix

the rval creation lines expect a matrix

so i have made this change--

https://github.com/DjalmaPessoa/convey/commit/1e59a69d843091b19d00d574c3b820b41a466397
