### ISSUE TITLE
are there ever circumstances where `convey_prep` should not be called immediately after svydesign?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#130]
hey @djalmapessoa, could you remind me why the `subset` needs to occur before the `convey_prep` call here?  

source: https://github.com/ajdamico/asdfree/blob/master/Pesquisa%20Nacional%20por%20Amostra%20de%20Domicilios/test_pnad2011.R

doing this is not what we recommend in our documents, and it might confuse users..  thanks boss

	# obviously first
	sample.pnad <-
	  svydesign(
		id = ~v4618 ,
		strata = ~v4617 ,
		data = 'pnad2011' ,
		weights = ~pre_wgt ,
		nest = TRUE ,
		dbtype = "MonetDBLite" ,
		dbname = pnad.dbfolder
	  )

	# obviously second
	y <-
	  pnad.postStratify(
		design = sample.pnad ,
		strata.col = 'v4609' ,
		oldwgt = 'pre_wgt'
	  )

	# should this be fourth?
	y.sub <- subset (y,  !is.na(v4720) & v4720!=0 & v8005>=15)

	# should this be third?
	y.sub <- convey_prep(y.sub)

**Comment by DjalmaPessoa** [comment]
I just thought the full design now would be y.sub, since these are the registers of interest. If the results don't change it is okay with me.

**Comment by ajdamico** [comment]
hi @djalmapessoa they produce different standard errors..  could you look at whether convey_prep() should be run before or after the `subset()` here?  if the correct answer is *after*, then we will need to update the ?convey_prep documentation to explain situations where `convey_prep` should not be called immediately after `svydesign` or `svrepdesign`?  currently, our documentation is pretty forceful that users must run it immediately after making the design object  :)



	> svyarpt(~v4720, y.sub , na.rm = TRUE)
		  arpt     SE
	v4720  450 1.8745


	> svyarpt(~v4720, y.sub , na.rm = TRUE)
		  arpt     SE
	v4720  450 1.8413

**Comment by DjalmaPessoa** [comment]
all functions that use the full_design as argument in svyrecvar will depend on the full_design  defined by means of convey_prep.

That's why in the PNAD2011 example the full_design was defined after taking subset, since the population of interest was the restricted one.

But on second thougth, by taking the subset this is already considered,  so the correct should be to apply the convey_prep before subseting.

**Comment by ajdamico** [comment]
i have made the change here, thanks djalma

https://github.com/ajdamico/asdfree/commit/d0dce9d3795de93d93b1c3ff5caedd458a39bd0d
