### ISSUE TITLE
svyarpt and svyarpr give unexpected results on equal probability designs

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#131]
please double-check if this problem is more widespread?  cc @guilhermejacob   thanks

	library(survey)
	library(convey)

	data(api)

	dstrat1<-convey_prep(svydesign(id=~1,weights=~pw, data=apistrat))
	dstrat2<-convey_prep(svydesign(id=~1,data=apistrat))

	svyarpt(~api00,dstrat1)
	svyarpt(~api00,dstrat2)

	svyarpr(~api00,dstrat1)
	svyarpr(~api00,dstrat2)

**Comment by DjalmaPessoa** [comment]
in the functions we use names(design$prob) and names(full_design$prob) and in the example they are NULL.  I suggest that in each function, before  these are used, be introduced:
if(is.null(names(design$prob)) names(design$prob) <- as.character(1: length(design$prob))
and 

if(is.null(names(full_design$prob)) names(full_design$prob) <- as.character(1: length(full_design$prob))

**Comment by ajdamico** [comment]
if i'm wrong, the build will fail.. but i believe this issue has been solved :)

https://travis-ci.org/DjalmaPessoa/convey/builds

**Comment by ajdamico** [comment]
hi @DjalmaPessoa i am not sure your proposed fix (which i implemented) is enough here?  on unweighted designs, `svyarpt` returns a value that is below the minimum value in the whole dataset..which seems wrong?  it is causing `svypoormed` and `svyrmpg` to crash on travis (but i think the fix is in svyarpt, svyarpr, and svyfgt -- not the two functions that are actually crashing travis.

could you take a look at this behavior?  thanks  :)

	library(convey)
	library(survey)

	data(api)
	dstrat2<-convey_prep(svydesign(id=~1,data=apistrat))

	# svyarpt is below the minimum
	# api00 values in the whole table
	
	svyarpt(~api00,dstrat2)

	table( sort( apistrat$api00 ) )

**Comment by ajdamico** [comment]
@DjalmaPessoa if this is not a bug, then the crashes occurring inside of `svypoormed` and `svyrmpg` should `stop()` with a description of the problem..  and we should revise the `testthat` scripts so they do not crash  :)

**Comment by DjalmaPessoa** [comment]
Check:
svyarpt(~api00,dstrat2)

from library survey:
.6* svyquantile(~api00,dstrat2, .5)

so the problem is with the library survey!

I don't understand the comment "if this is not a bug ...blabababa"

**Comment by DjalmaPessoa** [comment]
check for svyarpr:

sum(apistrat$api00<=coef(svyarpt(~api00,dstrat2)) )

**Comment by DjalmaPessoa** [comment]
I just made a synch and and noticed the fix was not included in svypoormed. All the functions that use 

names(design$prob) and names(full_design$prob)  had to be changed. So I'll try to do it.

**Comment by DjalmaPessoa** [comment]
svypoormed(~api00,dstrat2) is not working because it is computing the median of an empty set

and the same median is needed to compute svyrmpg.  

Since you found out this "nice example" please find some way out :)

**Comment by DjalmaPessoa** [comment]
Please see the following

svyquantile(~I(api00<=394.2 ) ,dstrat2, .5)

the result is 0, which is not correct. I think is not possible to compute.

**Comment by ajdamico** [comment]
i believe the latest behavior is good?  but reopen if you disagree..thanks djalma!


	> svypoormed(~api00,dstrat1)
		  poormed     SE
	api00     398 9.0539
	> svypoormed(~api00,dstrat2)
	Error in svypoormed.survey.design(~api00, dstrat2) : 
	  zero records in the set of poor people.  determine the poverty threshold by running svyarpt on ~ api00
	> svyrmpg(~api00,dstrat1)
			  rmpg     SE
	api00 0.006986 0.0203
	> svyrmpg(~api00,dstrat2)
	Error in svypoormed.survey.design(formula = formula, design = design,  : 
	  zero records in the set of poor people.  determine the poverty threshold by running svyarpt on ~ api00

**Comment by DjalmaPessoa** [comment]
Is it worth to include an argument thresh = TRUE in svypoormed?

**Comment by ajdamico** [comment]
what would it do?

**Comment by DjalmaPessoa** [comment]
Just like in svyfgt there is : 
@param thresh return the poverty threshold value

would avoid 

determine the poverty threshold by running svyarpt on ~ api00
> svyrmpg(~api00,dstrat1)

in the error message.

Besides this message should be general and not only for this particular example.

**Comment by ajdamico** [comment]
i still don't understand how it avoids the error?

the stop() message determines the formula dynamically, ~api00 is not
hardcoded..

**Comment by DjalmaPessoa** [comment]
of course this does not avoid the error. Just saves the time of computing
the poverty threshold and using svyarpt.

I think it is already ok the way it is.
