### ISSUE TITLE
restore svyrmir to skewedness testthat

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#134]
currently the functions crash without an informative error message.  when some mid-function value is out of bounds or results in a zero record subset, trigger a stop with useful information

**Comment by DjalmaPessoa** [comment]
there is nothing more skewed or concentrated than incomes in Brazil and the functions worked for PNAD

**Comment by DjalmaPessoa** [comment]
could you please give an example of having value out of bounds ?

**Comment by ajdamico** [comment]
https://github.com/DjalmaPessoa/convey/commit/3f75a1f787a8ea9526e0d2e8951015078500659e

**Comment by ajdamico** [comment]
still need to integrate these four: https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-skewed_distributions.R#L6

**Comment by ajdamico** [comment]
restored https://github.com/DjalmaPessoa/convey/commit/1f18802c8eda6b194a4511c305e3a42dee29bb41
