### ISSUE TITLE
svylorenz sometimes gives all missings on svrepdesign object

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#138]
# set the random seed, otherwise the problem does not always occur!
	set.seed(2)

	library(convey)
	library(survey)

	n <- 10

	dist_frame <-
		data.frame( 
			wt_binom = rbinom( n , 1 , .5 ) ,
			pois1 = rpois( n , 1 ) 
		)

	binom_des <- convey_prep( svydesign( ~ 1 , data = dist_frame , weight = ~ wt_binom ) )
	binom_rep <- convey_prep( as.svrepdesign( binom_des , type = 'bootstrap' ) )

	svylorenz( ~ pois1 , binom_des )
	svylorenz( ~ pois1 , binom_rep )

**Comment by guilhermejacob** [comment]
Check issue #137 and commit 12c2529f799aef8ce1ec6206b060000d9dcd9350.

**Comment by guilhermejacob** [comment]
Check issue #137 and commit 12c2529f799aef8ce1ec6206b060000d9dcd9350.
