### ISSUE TITLE
svyqsr returns unexpected results

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#139]
library(survey)
	library(convey)

	n <- 1000

	set.seed( n )

	dist_frame <-
		data.frame( 
			wt_binom = rbinom( n , 1 , .5 ) ,
			wt_unif = runif( n ) ,
			beta_050_050 = rbeta( n , 0.5 , 0.5 ) ,
			beta_500_100 = rbeta( n , 5 , 1 ) ,
			beta_100_300 = rbeta( n , 1 , 3 ) ,
			beta_200_200 = rbeta( n , 2 , 2 ) ,
			beta_200_500 = rbeta( n , 2 , 5 ) ,
			pois1 = rpois( n , 1 ) ,
			pois100 = rpois( n , 100 ) ,
			sex = ifelse( rbinom( n , 1 , 0.5 ) , "male" , "female" ) ,
			age = sample( 0:99 , n , replace = TRUE )
		)

	# seems like a reasonable distribution
	summary(dist_frame$pois1)

	unwtd_des <- convey_prep( svydesign( ~ 1 , data = dist_frame ) )

	# does not return a value
	svyqsr( ~ pois1 , unwtd_des )

	# returns infinity
	coef( svyqsr( ~ pois1 , unwtd_des ) )

**Comment by DjalmaPessoa** [comment]
Check using survey:
q20<- svyquantile(~ pois1 , unwtd_des,.20)
      q20<- as.vector(q20)
      q80<- svyquantile(~ pois1 , unwtd_des,.20)
      q80<- as.vector(q80)
      S20 <- svytotal(~I(pois1*(pois1<=q20)) , unwtd_des)
      S80 <- svytotal(~I(pois1*(pois1>q80)) , unwtd_des)   
      (qsr<- coef(S80)/coef(S20))

coef(S20) is zero. Should we include some test in the function?

**Comment by ajdamico** [comment]
i think this solves the problem then?  thanks

https://github.com/DjalmaPessoa/convey/commit/4648eddcba60c86de9f202797f185576b6b37f46
