### ISSUE TITLE
should the `testthat` folder include examples for svymir?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#14]

**Comment by DjalmaPessoa** [comment]
results for the se estimate from svymir and from the linrmir function of vardpoor are different.  Remember we wrote a message to the authors of vardpoor about that and never got an answer.
So, perhaps, we should include examples for svyrmir, but not comparing se estimates with vardpoor?

**Comment by ajdamico** [comment]
i've followed up..  but your decision how you want to present it  :)

**Comment by DjalmaPessoa** [comment]
the tests for svyrmir were inluded
