### ISSUE TITLE
fix svyrmir linearized variance calculation

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#140]
```
library(survey)
library(convey)

n <- 1000

set.seed( n )

dist_frame <-
    data.frame( 
        wt_binom = rbinom( n , 1 , .5 ) ,
        wt_unif = runif( n ) ,
        beta_050_050 = rbeta( n , 0.5 , 0.5 ) ,
        beta_500_100 = rbeta( n , 5 , 1 ) ,
        beta_100_300 = rbeta( n , 1 , 3 ) ,
        beta_200_200 = rbeta( n , 2 , 2 ) ,
        beta_200_500 = rbeta( n , 2 , 5 ) ,
        pois1 = rpois( n , 1 ) ,
        pois100 = rpois( n , 100 ) ,
        sex = ifelse( rbinom( n , 1 , 0.5 ) , "male" , "female" ) ,
        age = sample( 0:99 , n , replace = TRUE )
    )

unwtd_des <- convey_prep( svydesign( ~ 1 , data = dist_frame ) )
unwtd_rep <- convey_prep( as.svrepdesign( unwtd_des , type = 'bootstrap' ) )

lin_res <- svyrmir( ~ beta_050_050 , unwtd_des , age = ~ age )
rep_res <- svyrmir( ~ beta_050_050 , unwtd_rep , age = ~ age )


# data set looks pretty reasonable..
plot( dist_frame[ , c( 'age' , 'beta_050_050' ) ] )

# ..but there's a huge difference in standard errors
SE( lin_res )

SE( rep_res )
```

**Comment by DjalmaPessoa** [comment]
as the distribution is known, it is possible to simulate
      
      ComputeRmir <-
        function(x, w, order, age, agelim) {
          indb <- age < agelim
          quant_below <- convey:::computeQuantiles(x[indb], w[indb], p = order)
          inda <-  age >= agelim
          quant_above <- convey:::computeQuantiles(x[inda], w[inda], p = order)
          c(quant_above, quant_below, quant_above/quant_below)
        }
      
      
      
      
      
      rmir <- vector()
      for ( i in 1:500){
      beta5050 <- rbeta( n , 0.5 , 0.5 )
      age <- sample( 0:99 , n , replace = TRUE )
      rmir[i] <- ComputeRmir(beta5050,rep(1,n),.5, age, 65 )[3]
      }
      
      mean(rmir)
      sd(rmir)
      
  it seem that the se by linearization is wrong. Notice the difference between coef( lin_res) and coef(rep_res)  and mean(rmir)???

**Comment by ajdamico** [comment]
thanks :)  sounds like a bug that we should eventually fix, then?

**Comment by DjalmaPessoa** [comment]
This is probably due to the way we are using the function Fprime, and it is got to be also reviewed in other functions. So, it is not a very simple matter. 
The Fprime estimates a density from a distribution function. Since this last one is a step function, some smoothing is needed. The  crux of the matter is to work with the correct distribution function. So I'll have to think at over.

**Comment by DjalmaPessoa** [comment]
I just made a commit changing the function svyrmir. The results for the example became closer. Also, the results that  were much different from vardpor are closer now. I'm not sure this is the right way to fix, but it goes in the right direction.

**Comment by DjalmaPessoa** [comment]
For the rmir results, convey and vardpoor are now very close. The difference is due to the bandwidth (h) used. Vardpoor uses the same h for the two groups and convey uses one h for each group. I'm not sure about  which one is correct. This is a question about density estimation.  Perhaps we should ask someone.

**Comment by ajdamico** [comment]
great!  you can also file a question with the csblatvia people

**Comment by DjalmaPessoa** [comment]
I'd rather ask some specialist in density estimation.

**Comment by DjalmaPessoa** [comment]
This was fixed!

**Comment by ajdamico** [comment]
great, thanks djalma!  re-opening and self-assigning just so i remember to have a look in the next few weeks

**Comment by ajdamico** [comment]
thanks again @DjalmaPessoa
