### ISSUE TITLE
svygini estimates do not match IBGE estimates exactly.  do we care?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#142]
```
# setwd( "C:/My Directory/PNAD/" )


library(DBI)
library(MonetDBLite)    # load MonetDBLite package (creates database files in R)
library(downloader)     # downloads and then runs the source() function on scripts from github
library(survey)
library(convey)

pnad.dbfolder <- paste0( getwd() , "/MonetDB" )
db <- dbConnect( MonetDBLite::MonetDBLite() , pnad.dbfolder )
dbListTables(db)

options(survey.lonely.psu = "adjust")

source_url( "https://raw.githubusercontent.com/ajdamico/asdfree/master/Pesquisa%20Nacional%20por%20Amostra%20de%20Domicilios/pnad.survey.R" , prompt = FALSE )

out <- NULL

for( year in c( 2004:2009 , 2011:2012 ) ){

    sample.pnad <-
      svydesign(
        id = ~v4618 ,
        strata = ~v4617 ,
        data = paste0( 'pnad' , year ) ,
        weights = ~pre_wgt ,
        nest = TRUE ,
        dbtype = "MonetDBLite" ,
        dbname = pnad.dbfolder
      )

    y <-
      pnad.postStratify(
        design = sample.pnad ,
        strata.col = 'v4609' ,
        oldwgt = 'pre_wgt'
      )

    y <- convey_prep(y)

    y.sub <- subset (y,  !is.na(v4720) & v4720!=0 & as.numeric( v8005 ) >= 15 )


    brazil <- data.frame( coef( svygini (~ v4720,y.sub, na.rm=TRUE) ) )

    regions <- data.frame( coef( svyby(~v4720, ~region, y.sub, svygini, na.rm=TRUE ) ) )

    names( brazil ) <- names( regions ) <- paste0( 'y' , year )

    if( is.null( out ) ) out <- rbind( brazil , regions ) else out <- cbind( out , rbind( brazil , regions ) )

}

# compare `out` to PDF page 174
# http://biblioteca.ibge.gov.br/visualizacao/livros/liv66777.pdf#page=174
round( out , 3 )
```

**Comment by ajdamico** [comment]
possibly related?  https://github.com/DjalmaPessoa/convey/issues/3

**Comment by DjalmaPessoa** [comment]
I had noticed that. I could ask them the code they are using. It is
probably in SAS

**Comment by ajdamico** [comment]
yep, we should match or be able to explain the difference

**Comment by DjalmaPessoa** [comment]
I used the library laeken to check:

renda <- pnad2011_des_pos_sub$variables$v4720
    
    pesos <- weights(pnad2011_des_pos_sub)
    
    library(laeken)
    
    gini(renda,pesos, na.rm=TRUE)
    
    gini(renda, pesos, breakdown = pnad2011_des_pos_sub$variables$region, na.rm=TRUE )

the results are closer to convey than to http://biblioteca.ibge.gov.br/visualizacao/livros/liv66777.pdf#page=174

**Comment by guilhermejacob** [comment]
svygini results for both 2014 and 2015 match [this IBGE publication](http://biblioteca.ibge.gov.br/visualizacao/livros/liv98887.pdf#page=68).
Try: 
```svygini( ~v4719 , subset( y, v8005 >=  15 & v4805 == 1 & v4719 > 0 ), na.rm = T )```

**Comment by ajdamico** [comment]
hi, do the CVs or SEs match?  i only skimmed but didn't see anything that looked like a variance in that publication?  thanks

**Comment by guilhermejacob** [comment]
they didn't publish CVs or SEs for gini estimates. I couldn't find them in the CV tables

**Comment by DjalmaPessoa** [comment]
I just sent a message to the people at IBGE asking if they have cv estimates for gini estimates, so that we could compare.
As for the difference between point estimates, I asked them to see the SAS program they use to estimate the Gini. I'm just waiting for the answer.

**Comment by ajdamico** [comment]
thanks djalma

**Comment by DjalmaPessoa** [comment]
I just received a message from the  IBGE PNAD manager explaining how they estimated the GINI from PNAD.
They repeated each register according to its weight (integer) and computed the GINI like from a pseudo-census. So, no wonder there is a difference between the values when we use convey. 
As PNAD is going to be replaced  by PNADC and they intend  to use convey to estimate the GINI, I believe we should close this issue.
