### ISSUE TITLE
warning in citation("convey")

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#144]
this generates the following warning

Warning messages:
1: In citation("convey") :
  no date field in DESCRIPTION file of package ‘convey’
2: In citation("convey") :
  could not determine year for ‘convey’ from package DESCRIPTION file

**Comment by ajdamico** [comment]
CRAN adds this automatically.  that warning only appears in the dev version. :)  cc @guilhermejacob 


	> install.packages("convey")
	Installing package into ‘C:/Users/anthonyd/Documents/R/win-library/3.3’
	(as ‘lib’ is unspecified)
	--- Please select a CRAN mirror for use in this session ---
	trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.3/convey_0.1.0.zip'
	Content type 'application/zip' length 165280 bytes (161 KB)
	downloaded 161 KB

	package ‘convey’ successfully unpacked and MD5 sums checked

	The downloaded binary packages are in
			C:\Users\anthonyd\AppData\Local\Temp\RtmpMpo39N\downloaded_packages
	> citation("convey")

	To cite package ‘convey’ in publications use:

	  Djalma Pessoa, Anthony Damico and Guilherme Jacob (2016). convey: Income
	  Concentration Analysis with Complex Survey Samples. R package version 0.1.0.
	  https://CRAN.R-project.org/package=convey

	A BibTeX entry for LaTeX users is

	  @Manual{,
		title = {convey: Income Concentration Analysis with Complex Survey Samples},
		author = {Djalma Pessoa and Anthony Damico and Guilherme Jacob},
		year = {2016},
		note = {R package version 0.1.0},
		url = {https://CRAN.R-project.org/package=convey},
	  }
