### ISSUE TITLE
generalize svysqr to any quantile

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#147]
_The function svysqr works for symmetric quantiles alpha and 1-alpha. They suggested to generalize to quantiles like .20 and .70, for instance, where the sum is not 1. I believe this is easy to implement._

**Comment by DjalmaPessoa** [comment]
I've just changed the function for non- symmetric quantiles. Travis is breaking due to the test for skewed distributions that you designed. Could you please fix that?

**Comment by ajdamico** [comment]
hi, looks like travis was failing here because the parameter `alpha=` could have been either `alpha1=` or `alpha2=` ?    https://github.com/DjalmaPessoa/convey/commit/9c90d99609950116e6ab1d2101b19bd8d490111f

are there any basic checks that you could add to `convey\tests\testthat\test-svyqsr.R` that would just verify that the numbers are being computed in the right direction?

**Comment by DjalmaPessoa** [comment]
instead of alpha now should have 2 arguments: alpha1 and alpha2 . There is
no alpha anymore.

I don't understand the question about direction: alpha1<= alpha2 ?

**Comment by ajdamico** [comment]
right, the red line in this commit was the problem:  https://github.com/DjalmaPessoa/convey/commit/9c90d99609950116e6ab1d2101b19bd8d490111f  i fixed it

i'm just curious if it's worth adding a few checks to the testthat folder that use both `alpha1` and `alpha2`?  but it's okay if you don't want to add anything, i think this issue is okay to close
