### ISSUE TITLE
within the testthat folder, could each function have at least four use case tests?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#15]
for each of the main svy*() functions you have written,

`a1 <- svy*( ~variable , design )` run on linearized design
`a2 <- svyby( ~ variable , ~ byvar , design , svy*() )` run on linearized design

`b1 <- svy*( ~variable , design )` run on svyrep design
`b2 <- svyby( ~ variable , ~ byvar , design , svy*() )` run on svyrep design

and then could you also write testing code that checks and confirms that
`coef` and `SE` and `confint` all work on the outputted objects `a1`, `a2`, `b1`, and `b2`?

so for each function, 4 examples x 3 helper functions

**Comment by DjalmaPessoa** [comment]
for the b2 there were error messages:

> svyby(~eqIncome, by = ~db040, design = des_eusilc_rep, FUN = svyarpt, order = 0.5, percent = 0.6, deff = FALSE)
Error in approxfun(cum.w, xx[oo], method = "constant", f = 1, yleft = min(xx),  : 
  zero non-NA points

> svyby(~eqIncome, by = ~db040, design = des_eusilc_rep, FUN = svyarpr, order = 0.5, percent = 0.6, deff = FALSE)
Error in approxfun(cum.w, xx[oo], method = "constant", f = 1, yleft = min(xx),  : 
  zero non-NA points

> svyby(~eqIncome, by = ~db040, design = des_eusilc_rep, FUN = svyrmpg, order = 0.5, percent = 0.6, deff = FALSE)
Error in approxfun(cum.w, xx[oo], method = "constant", f = 1, yleft = min(xx),  : 
  zero non-NA points

> svyby(~eqIncome, by = ~db040, design = des_eusilc_rep, FUN = svyqsr, alpha=.2, deff = FALSE)
Error in approxfun(cum.w, xx[oo], method = "constant", f = 1, yleft = min(xx),  : 
  zero non-NA points

> svyby(~eqIncome, by = ~db040, design = des_eusilc_rep, FUN = svygini, deff = FALSE)

there were 9 warning messages like

1: In svrVar(qq, design$scale, design$rscales, mse = design$mse, coef = rval) :
  18 replicates gave NA results and were discarded.
2.
3.

9

**Comment by DjalmaPessoa** [comment]
Consider the function svyarpr and get:

library(survey)
library(convey
des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
des_eusilc_rep <- as.svrepdesign(des_eusilc, type = "bootstrap")
des_eusilc <- convey_prep(des_eusilc)

a2 <- svyby(~eqIncome, by = ~db040, design = des_eusilc, FUN = svyarpr, order = 0.5, percent = 0.6,deff = FALSE)

b2 <- svyby(~eqIncome, by = ~db040, design = des_eusilc_rep, FUN = svyarpr, order = 0.5, percent = 0.6, deff = FALSE)

               # then we should have the same result for coef(a2) and coef(b2)
		# but they are different
		# reason; in b1 we compute the arpr in each domain using the arpt for the whole population      
		#  in b2 we use the an arpt for each domain.
		#  Problem: how to use in b2 the arpt for the whole population?

**Comment by ajdamico** [comment]
i made a few more commits to add full_design to svrepdesign objects!

**Comment by DjalmaPessoa** [comment]
I'm not so sure how to use the full design with svrepdesign objects using
svyby.

To explain the difficulty, suppose we had the population and could
repeatedly select samples using the same design many times.

For each sample,  we estimate:

1. arpt = 0.6  X the median for the whole population;
2. arpr = the proportion of people with income less or equal than arpt in
the domain.

Note that there are two sources of variation: 1. estimation of arpt for the
whole population; 2. estimation of the ratio inside the domain.

In the bootstrap we have to mimic the above process. Each bootstrap weight
replicate corresponds to one sample of the simulation process described.

To account for the variation 1. we have to replicate weights using the
full_design. then each weight replicate has to be used to estimate 2.

It is not clear to me how to implement this using svyby

**Comment by ajdamico** [comment]
i don't understand why `svyby` is different from any other subsetted object?  forgetting about `svyby` for a second, are you able to solve this problem with the `full_design` and with the subsetted `design`?  if you start with both designs, are able to solve it?  for a subsetted object, you can safely assume that the replicate-weighted *columns* will always be in the same position -- even if the rows are not.

**Comment by DjalmaPessoa** [comment]
that much I know...
