### ISSUE TITLE
Inequality decomposition: GEI and J-Divergence

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#150]
In a previous conversation, we discussed the possibility of implementing inequality decomposition methods for the Generalized Entropy Index and the J-Divergence measure.

This unfolded into two questions:
1. Technical aspects related to inference of the the decomposed terms;
2. How to add options to the main (non-decomposed) functions in order to generate other important variables without troubling the general user?

**Comment by guilhermejacob** [comment]
See `svygeidec` and `jdivdec`.

**Comment by ajdamico** [comment]
@DjalmaPessoa did you see this?  awesome.
