### ISSUE TITLE
fix build

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#156]
@ajdamico , can you help me with this?
I think it has something to do with how i get the values from the `estimate` object inside the function.
Also, something related to non-ascii characters.
thanks!

**Comment by ajdamico** [comment]
i am not sure if i screwed up other things, though.  could you check my commit?

https://travis-ci.org/DjalmaPessoa/convey/builds/181142150

**Comment by guilhermejacob** [comment]
It's fine, thanks!
