### ISSUE TITLE
add print method for `cvydstat`

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#159]
See `svygeidec` and `svyjdivdec` for `cvydstat`.
See `svyafcdec` for proper print method.
Make sure that they work for `coef` and `SE`, as testthats will be implemented on top of this.

**Comment by ajdamico** [comment]
hi, two questions:
1. i don't understand this sentence? `See svyafcdec for proper print method.`  ..there's no print method inside `svyafcdec.R`?  seems like i should write something like `survey:::print.svyquantile` unless you have other ideas?
2. there isn't a `SE` attribute in those decomposition results, right?  not sure if i should just be using the `sqrt()` of the variance for the `SE` calculation?

**Comment by guilhermejacob** [comment]
I think this one is ok
