### ISSUE TITLE
should the ?examples pages include basic info about the parameters?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#16]
you previously had lines like

    #' arpt_eqIncome <-svyarpt(~eqIncome, design=des_eusilc, .5, .6,comp=TRUE)

but the 0.5 and 0.6 and comp=TRUE are just the default for the function, so they are unnecessary.  do you want to add examples to each svy*() function that show what the non-default parameters do?  for example, what is the difference between

    svyarpt( ~eqIncome , des_eusilc )

and

    svyarpt( ~eqIncome , des_eusilc , order = 0.5 )

and

    svyarpt( ~eqIncome , des_eusilc , comp = TRUE )

some notes about how each parameter changes each function would make it easier for users..  if you do not add notes, then the svy*() examples should only use the defaults, i think?

**Comment by DjalmaPessoa** [comment]
I agree.
