### ISSUE TITLE
Add richness measures

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#166]
[This Stata paper](http://fmwww.bc.edu/repec/bocode/r/richness.pdf) discusses measures of inequality. It shouldn't be difficult to adapt poverty measures to richness measures.

**Comment by guilhermejacob** [comment]
[This paper](http://www.wne.uw.edu.pl/inf/wyd/WP/WNE_WP88.pdf) presents the linearization framework for those measures

**Comment by DjalmaPessoa** [comment]
I believe the functions to estimate the richness measures defined in the paper  can be easily derived from the functions we already in convey. 
The HC can be obtained from svyarpr and the FGT,T2 form svyfgt.

**Comment by guilhermejacob** [comment]
done!
