### ISSUE TITLE
please check whether svyfgt needs a reference to foster 1984?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#167]
https://github.com/DjalmaPessoa/convey/blob/master/R/svyfgt.R

https://github.com/guilhermejacob/context/blob/master/book.bib#L208-L219

thanks

**Comment by DjalmaPessoa** [comment]
the references I used for svyfgt were: [@foster1984] and [@berger2003] (as in the book)
I believe they can replace the references that are presently there.
