### ISSUE TITLE
please check variance construction of svyamato.svrepdesign and svyamato.survey.design?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#169]
here's an example script that prints the standard errors of a bunch of convey functions..  the `svyamato` standard errors seem too far apart?  thanks

	library(convey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
	library(survey)

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- convey_prep(des_eusilc)
	des_eusilc_rep <- as.svrepdesign( des_eusilc , type = "bootstrap" )
	des_eusilc_rep <- convey_prep(des_eusilc_rep)

	out <- NULL

	for( this_fun in c( "svyatk" , "svyamato" , "svyqsr" , "svypoormed" , "svyjdiv" , "svyzenga" , "svyrmpg" , "svyrmir" , "svyisq" , "svyiqalpha" , "svyarpr" , "svyarpt" , "svyfgt" , "svygini" , "svyrenyi" ) ){

		final_fun <- FUN <- get( this_fun )

		if( identical( FUN , svyrmpg ) ) final_fun <- function( ... ) FUN( ... , thresh = TRUE )
		if( identical( FUN , svyrmir ) ) final_fun <- function( ... ) FUN( ... , age = ~ age , med_old = TRUE )
		if( identical( FUN , svyisq ) ) final_fun <- function( ... ) FUN( ... , alpha = 0.2 )
		if( identical( FUN , svyiqalpha ) ) final_fun <- function( ... ) FUN( ... , alpha = 0.5 )
		if( identical( FUN , svyfgt ) ) final_fun <- function( ... ) FUN( ... , g = 0 , abs_thresh = 10000 )
		if( identical( FUN , svyrenyi ) ) final_fun <- function( ... ) FUN( ... , epsilon = 0.5 )
		
		this_df <-
			data.frame(
				function_name = this_fun ,
				coef_lin = coef( final_fun( ~ eqincome , des_eusilc ) ) ,
				se_lin = SE( final_fun( ~ eqincome , des_eusilc ) )[1] ,
				coef_rep = coef( final_fun( ~ eqincome , des_eusilc_rep ) ) ,
				se_rep = SE( final_fun( ~ eqincome , des_eusilc_rep ) )[1]
			)

		rownames( this_df ) <- NULL
			
		out <- rbind( out , this_df )
	}

	options( scipen = 20 )

	# compare coefficients and standard errors across designs
	out

	# svyamato is way off, relative to the others?
	out$se_lin / out$se_rep

**Comment by ajdamico** [comment]
after resolving these three issues https://github.com/DjalmaPessoa/convey/issues/169  https://github.com/DjalmaPessoa/convey/issues/170  https://github.com/DjalmaPessoa/convey/issues/171

please restore these two lines in the testing scripts  https://github.com/DjalmaPessoa/convey/commit/be8dbba9b15c4b058ba865954799bb41e7b327d3

**Comment by guilhermejacob** [comment]
fixed and tests restored
