### ISSUE TITLE
please check variance construction of svybmi?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#170]
the standard errors seem too far apart?  thanks bud

	library(convey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
	library(survey)

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- convey_prep(des_eusilc)
	des_eusilc_rep <- as.svrepdesign( des_eusilc , type = "bootstrap" )
	des_eusilc_rep <- convey_prep(des_eusilc_rep)

	options(scipen=10)

	svybmi(~eqincome+hy050n, design = des_eusilc, alpha = .5, beta = .5, na.rm = FALSE )
	svybmi(~eqincome+hy050n, design = des_eusilc_rep, alpha = .5, beta = .5, na.rm = FALSE )

**Comment by ajdamico** [comment]
after resolving these three issues https://github.com/DjalmaPessoa/convey/issues/169  https://github.com/DjalmaPessoa/convey/issues/170  https://github.com/DjalmaPessoa/convey/issues/171

please restore these two lines in the testing scripts  https://github.com/DjalmaPessoa/convey/commit/be8dbba9b15c4b058ba865954799bb41e7b327d3

**Comment by guilhermejacob** [comment]
commit e1608b3dfcd511c8d85707a9cfa25a74f37cf457 fixes this

**Comment by ajdamico** [comment]
you are a hero
