### ISSUE TITLE
please check variance construction in svyafcdec

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#171]
these two sets of numbers seem too far apart?  thanks

	library(convey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
	library(survey)

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- convey_prep(des_eusilc)
	des_eusilc_rep <- as.svrepdesign( des_eusilc , type = "bootstrap" )
	des_eusilc_rep <- convey_prep(des_eusilc_rep)

	options(scipen=10)

	cos <- list( 10000, 5000 )
	
	afc_lin <- svyafcdec( ~eqincome+hy050n , design = des_eusilc , by.formula = ~rb090 , k = .5 , g = 0, cutoffs = cos )
	afc_rep <- svyafcdec( ~eqincome+hy050n , design = des_eusilc_rep , by.formula = ~rb090 , k = .5 , g = 0, cutoffs = cos )

	# compare
	afc_lin[[5]]
	afc_rep[[5]]
	
	
	# compare
	afc_lin[[6]]
	afc_rep[[6]]

**Comment by ajdamico** [comment]
after resolving these three issues https://github.com/DjalmaPessoa/convey/issues/169  https://github.com/DjalmaPessoa/convey/issues/170  https://github.com/DjalmaPessoa/convey/issues/171

please restore these two lines in the testing scripts  https://github.com/DjalmaPessoa/convey/commit/be8dbba9b15c4b058ba865954799bb41e7b327d3

**Comment by guilhermejacob** [comment]
commit d621885a28e55def0d4a8e89094480a09569ebea fixes this issue

**Comment by ajdamico** [comment]
thank ya
