### ISSUE TITLE
testthat SE comparisons should use meaningful differences

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#172]
these two pairs of lines have maximum values that are too big to catch mistakes.  after resolving https://github.com/DjalmaPessoa/convey/issues/169 please change those `5`s to an upper bound for the difference between the uncertainty measures that will realistically detect a mistake?  that one value is pretty sneakily function-dependent, so you can't just copy and paste from other testthats.  thanks  :)

https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-extract_svyamato-all.R#L37-L38

https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-extract_svyamato-pos.R#L43-L44

**Comment by DjalmaPessoa** [comment]
All results compairing linearization and bootstrap are simulation studies and the difference between variance estimates depends on:
1. The point estimate whose variance you are estimating: ratio, correlation coefficient, etc
2. The design used

So it is impossible to fix reasonable bounds for the difference. 
So why the value 5 was chosen? 
Oficial statistics agencies often try to guide the users about the point estimates quality using the cv  bounds like: cv<= 5% ,   5%< cv <=10% and so forth.
 So the < 5% difference would put the estimate in the same class( roughly)

**Comment by ajdamico** [comment]
putting in `5` was my sledgehammer approach but it obviously misses wide differences it should be picking up.  i've revised everything here:  https://github.com/DjalmaPessoa/convey/commit/a1dee8e5ef301421ac8ab39467dc2aaa1b82a4a5   @guilhermejacob i think you can close this issue unless you have questions?  thanks
