### ISSUE TITLE
svyrmpg linearized vs replication-based designs give different coefficients

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#173]
these numbers should match precisely..  thanks

	library(convey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
	library(survey)

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- subset( convey_prep(des_eusilc) , eqincome > 0 )
	des_eusilc_rep <- as.svrepdesign( des_eusilc , type = "bootstrap" )
	des_eusilc_rep <- subset( convey_prep(des_eusilc_rep) , eqincome > 0 )

	# these two values are not equal
	coef( svyrmpg( ~ eqincome , des_eusilc , thresh = TRUE ) )
	coef( svyrmpg( ~ eqincome , des_eusilc_rep , thresh = TRUE ) )

**Comment by ajdamico** [comment]
after fixing this, please uncomment this line in the testthats:  https://github.com/DjalmaPessoa/convey/commit/2e4a38e32d38b3071d15a205897276ae1c6bbaff

**Comment by DjalmaPessoa** [comment]
Do you any idea why these two are equal???

library(convey)
        library(vardpoor)
        data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
        library(survey)
        
        
        des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  
          weights = ~rb050, data = eusilc)
        des_eusilc <-convey_prep(des_eusilc)
        des_eusilc_rep <- as.svrepdesign( des_eusilc , type = "bootstrap" )
        des_eusilc_rep <-convey_prep(des_eusilc_rep)
        
        coef(svyrmpg( ~ eqincome , des_eusilc , thresh = TRUE ) )
        
        coef( svyrmpg( ~ eqincome , des_eusilc_rep , thresh = TRUE ) )

**Comment by ajdamico** [comment]
because you are not correctly dealing with subsets somewhere.  the coefficients match if there's no `subset` function.

**Comment by DjalmaPessoa** [comment]
In test-extrat_svyrmpg.R it tested for subsets. See

expect_equal(coef(a2), coef(b2))

**Comment by ajdamico** [comment]
it looks like this bug only affects subsets that do not affect the column
being analyzed

**Comment by DjalmaPessoa** [comment]
How to explain this:
 
 library(convey)
        library(vardpoor)
        data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
        library(survey)

        des_eusilc <- svydesign(ids = ~rb030, strata =~db040,
          weights = ~rb050, data = eusilc)
        des_eusilc <-convey_prep(des_eusilc)
        des_eusilc_rep <- as.svrepdesign( des_eusilc , type = "bootstrap" )
        des_eusilc_rep <-convey_prep(des_eusilc_rep)


        coef(svyrmpg( ~ eqincome , subset(des_eusilc,eqincome > 0) ,
          thresh = TRUE ) )

        coef( svyrmpg( ~ eqincome , subset(des_eusilc_rep, eqincome>0) ,
          thresh = TRUE ) )

They are equal!

**Comment by ajdamico** [comment]
obviously you are correct.  the `subset` needs to occur after the `as.svrepdesign`

**Comment by guilhermejacob** [comment]
Just a guess but if you
```
des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
des_eusilc <- subset( convey_prep(des_eusilc) , eqincome > 0 )
```
then running
```
des_eusilc_rep <- as.svrepdesign( des_eusilc , type = "bootstrap" )
des_eusilc_rep <- subset( convey_prep(des_eusilc_rep) , eqincome > 0 )
```
will use the subsetted `des_eusilc` to produce the bootstrap weights. 

If you use the entire sample to calculate the threshold, this will yield different results.
Run:
```
des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
des_eusilc_rep <- as.svrepdesign( des_eusilc , type = "bootstrap" )
des_eusilc <- subset( convey_prep(des_eusilc) , eqincome > 0 )
des_eusilc_rep <- subset( convey_prep(des_eusilc_rep) , eqincome > 0 )

coef( svyrmpg( ~ eqincome , des_eusilc , thresh = TRUE ) )
coef( svyrmpg( ~ eqincome , des_eusilc_rep , thresh = TRUE ) )
```

The problem would be: how to calculate subsetted thresholds with the linearized design?

**Comment by DjalmaPessoa** [comment]
In convey we used the same idea as in vardpoor. The threshold is global. That is, when computing the rate of poors for states we use the poverty line for the whole country. I believe this makes sense. I'm not so sure this ok for any type of subset. We have to think it over.
