### ISSUE TITLE
svylorenz replication

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#174]
@ajdamico , you can replicate [this](http://repec.sowi.unibe.ch/files/wp15/jann-2016-lorenz.pdf) using the code below:
```
# load the convey package
library(convey)

# load the survey library
library(survey)

# load the stata-style webuse library
library(webuse)

# load the NLSW 1988 data
webuse("nlsw88")

# coerce that `tbl_df` to a standard R `data.frame`
nlsw88 <- data.frame( nlsw88 )

# initiate a linearized survey design object
des_nlsw88 <- svydesign( ids = ~1 , data = nlsw88 )

# immediately run the `convey_prep` function on the survey design
des_nlsw88 <- convey_prep(des_nlsw88)

# estimates lorenz curve
svylorenz( ~wage, des_nlsw88, na.rm = T )
```

**Comment by ajdamico** [comment]
hi, thanks, but this doesn't replicate the confidence intervals presented in that document?

whenever r `survey` functions do not match stata, my first guess is always looking at `degf(object)` because `survey` uses `df=Inf` by default whereas stata survey commands often use `degf(object)` as displayed in these r-replication-of-stata examples:  http://www.ats.ucla.edu/stat/r/faq/svy_r_post.htm

maybe they're using a t score rather than a z score that relies on the degrees of freedom of the survey object somehow?  like this?

    svylorenz( ~wage, des_nlsw88, na.rm = T,alpha=pnorm(qt(0.025,degf(subset(des_nlsw88,!is.na(wage))))))

but you could be matching the SEs without matching the CIs, maybe that's the first intermediary step in the replication?

stata code: http://fmwww.bc.edu/repec/bocode/l/lorenz.ado

**Comment by guilhermejacob** [comment]
It's just a guess, but...
Apparently, Stata's `lorenz` doesn't use kovacevic-binder method, considering it as a simple ratio, which is a bad idea since the influence of the quantile is ignored.
```
program Contrast_opt
    syntax [anything] [, Ratio LNRatio ]
    Contrast `anything' , `ratio' `lnratio'
end
```
That's why `svylorenz`'s confidence interval is slightly larger: it takes into account this other source of variance.
Makes sense, right?

**Comment by guilhermejacob** [comment]
As a suggestion, I would try Stata's `svylorenz`

**Comment by guilhermejacob** [comment]
I'll try changing the quantile definition. Might be that too.

**Comment by ajdamico** [comment]
stata's `svylorenz` does not match either


	library(convey)
	library(survey)
	library(foreign)
	tf <- tempfile()
	download.file( "http://econpapers.repec.org/scripts/redir.pf?u=http%3A%2F%2Frepec.org%2Fnasug2006%2Fnasug2006_jenkins.zip;h=repec:boc:asug06:16" , tf , mode = 'wb' )
	these_files <- unzip( tf , exdir = tempdir() )

	x81 <- read.dta( grep( "ifs81" , these_files , value = TRUE ) )
	x85 <- read.dta( grep( "ifs85" , these_files , value = TRUE ) )
	x91 <- read.dta( grep( "ifs91" , these_files , value = TRUE ) )

	x <- rbind( x81 , x85 , x91 )
	y <- svydesign( ~ hrn , data = x , weights = ~ wgt )
	z <- convey_prep( y )



	z81 <- subset( z , year == 1981 )

	svylorenz( ~ eybhc0 , z81 )
	
	# does not match nasug03.log included in the downloaded zip file	
	readLines(grep("nasug03",these_files,value=T))[660:708]

**Comment by guilhermejacob** [comment]
Ah yes. Found out.
I used [the function 3.20 and its influence function](https://doc.rero.ch/record/29204/files/00002252.pdf#page=58), then i divided it by the total of y and operated the influence functions. This is kind of an original result, so there's not much to compare there.

**Comment by ajdamico** [comment]
hi, thanks, my knee-jerk bias is against original results that don't match
anything currently published.  seems like it might be better if you could
add a parameter that *does* allow us to replicate other published work,
even if it isn't the default for the function?    if both you and
@djalmapessoa disagree, that's fine.

**Comment by guilhermejacob** [comment]
Ok, will do (:

**Comment by ajdamico** [comment]
thanks guilherme

**Comment by guilhermejacob** [comment]
commit a073d17c9c8acc0c9c10059ab79efa6e732ac663 solves this (i think)

**Comment by DjalmaPessoa** [comment]
Of course it is better if we can match results from reliable sources. But remember that we tried to match results from vardpoor library and had problems.

**Comment by ajdamico** [comment]
@guilhermejacob should this match stata's `lorenz` or `svylorenz`?  i just tried out both of the minimal reproducible examples above and it didn't appear to match either?

**Comment by ajdamico** [comment]
@DjalmaPessoa agreed.  with vardpoor, you actually found a bug in their software in one case, and were able to edit the `parameters=` sent to your function in another case.  even if we do not match other software by default, it's safer to demonstrate that we are able to replicate others' work and then explain why the default settings differ?  thanks

**Comment by guilhermejacob** [comment]
@ajdamico , this replicates the results in [page 18](http://repec.sowi.unibe.ch/files/wp15/jann-2016-lorenz.pdf#page=18):

```
# load the convey package
library(convey)

# load the survey library
library(survey)

# load the stata-style webuse library
library(webuse)

# load the NLSW 1988 data
webuse("nlsw88")

# coerce that `tbl_df` to a standard R `data.frame`
nlsw88 <- data.frame( nlsw88 )

# initiate a linearized survey design object
des_nlsw88 <- svydesign( ids = ~1 , data = nlsw88 )

# immediately run the `convey_prep` function on the survey design
des_nlsw88 <- convey_prep(des_nlsw88)

des_nlsw88_rep <-  as.svrepdesign( des_nlsw88, type = "bootstrap", replicates = 50 )
des_nlsw88_rep <- convey_prep( des_nlsw88_rep )


# estimates lorenz curve
result.lin <- svylorenz( ~wage, des_nlsw88, quantiles = seq( 0, 1, .05 ), na.rm = T )
result.rep <- svylorenz( ~wage, des_nlsw88_rep, quantiles = seq( 0, 1, .05 ), na.rm = T )


round( coef( result.lin ), 7 )
round( coef( result.rep ), 7 )

round( SE( result.lin ), 7 )
round( SE( result.rep ), 7 )
```

**Comment by ajdamico** [comment]
amazing.  thanks!  and here's how to match the confidence intervals precisely

    coef( result.lin ) + SE( result.lin ) * qt(0.025,degf(subset(des_nlsw88,!is.na(wage))))
    coef( result.lin ) + SE( result.lin ) * qt(0.975,degf(subset(des_nlsw88,!is.na(wage))))

**Comment by ajdamico** [comment]
added to 3.1.1!
