### ISSUE TITLE
create a replication vignette for svyatk

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#175]
@guilhermejacob  flip back assignee to me if you're ok with this?

	library(convey)
	library(survey)
	library(foreign)
	tf <- tempfile()
	download.file( "http://econpapers.repec.org/scripts/redir.pf?u=http%3A%2F%2Frepec.org%2Fnasug2006%2Fnasug2006_jenkins.zip;h=repec:boc:asug06:16" , tf , mode = 'wb' )
	z <- unzip( tf , exdir = tempdir() )

	x81 <- read.dta( grep( "ifs81" , z , value = TRUE ) )
	x85 <- read.dta( grep( "ifs85" , z , value = TRUE ) )
	x91 <- read.dta( grep( "ifs91" , z , value = TRUE ) )

	x <- rbind( x81 , x85 , x91 )
	y <- svydesign( ~ hrn , data = x , weights = ~ wgt )
	z <- convey_prep( y )

	z81 <- subset( z , year == 1981 )

	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 0.5 )
	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) )
	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 1.5 )
	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 2 )
	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 2.5 )
	# . * account for clustering within HHs 
	# . version 8: svyset [pweight = wgt], psu(hrn)
	# pweight is wgt
	# psu is hrn

	# . svyatk x if year == 1981
	 
	# Warning: x has 20 values = 0. Not used in calculations

	# Complex survey estimates of Atkinson inequality indices
	 
	# pweight: wgt                                   Number of obs    = 9752
	# Strata: <one>                                  Number of strata = 1
	# PSU: hrn                                       Number of PSUs   = 7459
												   # Population size  = 54766261
	# ---------------------------------------------------------------------------
	# Index    |  Estimate   Std. Err.      z      P>|z|     [95% Conf. Interval]
	# ---------+-----------------------------------------------------------------
	# A(0.5)   |  .0543239   .00107583    50.49    0.000      .0522153   .0564324
	# A(1)     |  .1079964   .00245424    44.00    0.000      .1031862   .1128066
	# A(1.5)   |  .1701794   .0066943    25.42    0.000       .1570588      .1833
	# A(2)     |  .2755788   .02597608    10.61    0.000      .2246666    .326491
	# A(2.5)   |  .4992701   .06754311     7.39    0.000       .366888   .6316522
	# ---------------------------------------------------------------------------

	z81_two <- subset( z , year == 1981 & eybhc0 > 1 )

	svyatk( ~ eybhc0 , z81_two , epsilon = 0.5 )
	svyatk( ~ eybhc0 , z81_two )
	svyatk( ~ eybhc0 , z81_two , epsilon = 1.5 )
	svyatk( ~ eybhc0 , z81_two , epsilon = 2 )
	svyatk( ~ eybhc0 , z81_two , epsilon = 2.5 )
	# . svyatk x if year == 1981 & x >= 1

	# Complex survey estimates of Atkinson inequality indices
	 
	# pweight: wgt                                   Number of obs    = 9748
	# Strata: <one>                                  Number of strata = 1
	# PSU: hrn                                       Number of PSUs   = 7457
												   # Population size  = 54744234
	# ---------------------------------------------------------------------------
	# Index    |  Estimate   Std. Err.      z      P>|z|     [95% Conf. Interval]
	# ---------+-----------------------------------------------------------------
	# A(0.5)   |  .0540059   .00105011    51.43    0.000      .0519477   .0560641
	# A(1)     |  .1066082   .00223318    47.74    0.000      .1022313   .1109852
	# A(1.5)   |  .1638299   .00483069    33.91    0.000       .154362   .1732979
	# A(2)     |  .2443206   .01425258    17.14    0.000      .2163861   .2722552
	# A(2.5)   |   .394787   .04155221     9.50    0.000      .3133461   .4762278
	# ---------------------------------------------------------------------------

**Comment by guilhermejacob** [comment]
Thanks! I'll use it in the book, after i put all the mini-explanations for each measure in the chapter

**Comment by guilhermejacob** [comment]
I'm ok with it

**Comment by ajdamico** [comment]
added to section 3.3.4
