### ISSUE TITLE
create a replication vignette for svygei

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#176]
@guilhermejacob how do we hit the numbers `GE(-1)` ?  flip back assignee to me once you finish or if we shouldn't bother?  thanks

	library(convey)
	library(survey)
	library(foreign)
	tf <- tempfile()
	download.file( "http://econpapers.repec.org/scripts/redir.pf?u=http%3A%2F%2Frepec.org%2Fnasug2006%2Fnasug2006_jenkins.zip;h=repec:boc:asug06:16" , tf , mode = 'wb' )
	z <- unzip( tf , exdir = tempdir() )

	x81 <- read.dta( grep( "ifs81" , z , value = TRUE ) )
	x85 <- read.dta( grep( "ifs85" , z , value = TRUE ) )
	x91 <- read.dta( grep( "ifs91" , z , value = TRUE ) )

	x <- rbind( x81 , x85 , x91 )
	y <- svydesign( ~ hrn , data = x , weights = ~ wgt )
	z <- convey_prep( y )

	z81 <- subset( z , year == 1981 )

	svygei( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 0 )
	svygei( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) )
	svygei( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 2 )
	svygei( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 3 )

	svygei( ~ eybhc0 , subset( z81 , eybhc0 > 1 ) , epsilon = 0 )
	svygei( ~ eybhc0 , subset( z81 , eybhc0 > 1 ) )
	svygei( ~ eybhc0 , subset( z81 , eybhc0 > 1 ) , epsilon = 2 )
	svygei( ~ eybhc0 , subset( z81 , eybhc0 > 1 ) , epsilon = 3 )

	# . svygei x if year == 1981
	 
	# Warning: x has 20 values = 0. Not used in calculations

	# Complex survey estimates of Generalized Entropy inequality indices
	 
	# pweight: wgt                                   Number of obs    = 9752
	# Strata: <one>                                  Number of strata = 1
	# PSU: hrn                                       Number of PSUs   = 7459
												   # Population size  = 54766261
	# ---------------------------------------------------------------------------
	# Index    |  Estimate   Std. Err.      z      P>|z|     [95% Conf. Interval]
	# ---------+-----------------------------------------------------------------
	# GE(-1)   |  .1902062   .02474921     7.69    0.000      .1416987   .2387138
	# MLD      |  .1142851   .00275138    41.54    0.000      .1088925   .1196777
	# Theil    |  .1116923   .00226489    49.31    0.000      .1072532   .1161314
	# GE(2)    |   .128793   .00330774    38.94    0.000      .1223099    .135276
	# GE(3)    |  .1739994   .00662015    26.28    0.000      .1610242   .1869747
	# ---------------------------------------------------------------------------

		
	
	
	
	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) )
	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 1.5 )
	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 2 )
	svyatk( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 2.5 )
	# . * account for clustering within HHs 
	# . version 8: svyset [pweight = wgt], psu(hrn)
	# pweight is wgt
	# psu is hrn

	# . svyatk x if year == 1981
	 
	# Warning: x has 20 values = 0. Not used in calculations

	# Complex survey estimates of Atkinson inequality indices
	 
	# pweight: wgt                                   Number of obs    = 9752
	# Strata: <one>                                  Number of strata = 1
	# PSU: hrn                                       Number of PSUs   = 7459
												   # Population size  = 54766261
	# ---------------------------------------------------------------------------
	# Index    |  Estimate   Std. Err.      z      P>|z|     [95% Conf. Interval]
	# ---------+-----------------------------------------------------------------
	# A(0.5)   |  .0543239   .00107583    50.49    0.000      .0522153   .0564324
	# A(1)     |  .1079964   .00245424    44.00    0.000      .1031862   .1128066
	# A(1.5)   |  .1701794   .0066943    25.42    0.000       .1570588      .1833
	# A(2)     |  .2755788   .02597608    10.61    0.000      .2246666    .326491
	# A(2.5)   |  .4992701   .06754311     7.39    0.000       .366888   .6316522
	# ---------------------------------------------------------------------------

	z81_two <- subset( z , year == 1981 & eybhc0 > 1 )

	svyatk( ~ eybhc0 , z81_two , epsilon = 0.5 )
	svyatk( ~ eybhc0 , z81_two )
	svyatk( ~ eybhc0 , z81_two , epsilon = 1.5 )
	svyatk( ~ eybhc0 , z81_two , epsilon = 2 )
	svyatk( ~ eybhc0 , z81_two , epsilon = 2.5 )
	# . svyatk x if year == 1981 & x >= 1

	# Complex survey estimates of Atkinson inequality indices
	 
	# pweight: wgt                                   Number of obs    = 9748
	# Strata: <one>                                  Number of strata = 1
	# PSU: hrn                                       Number of PSUs   = 7457
												   # Population size  = 54744234
	# ---------------------------------------------------------------------------
	# Index    |  Estimate   Std. Err.      z      P>|z|     [95% Conf. Interval]
	# ---------+-----------------------------------------------------------------
	# A(0.5)   |  .0540059   .00105011    51.43    0.000      .0519477   .0560641
	# A(1)     |  .1066082   .00223318    47.74    0.000      .1022313   .1109852
	# A(1.5)   |  .1638299   .00483069    33.91    0.000       .154362   .1732979
	# A(2)     |  .2443206   .01425258    17.14    0.000      .2163861   .2722552
	# A(2.5)   |   .394787   .04155221     9.50    0.000      .3133461   .4762278
	# ---------------------------------------------------------------------------

	# . svygei x if year == 1985 & x >= 1

	# Complex survey estimates of Generalized Entropy inequality indices
	 
	# pweight: wgt                                   Number of obs    = 8969
	# Strata: <one>                                  Number of strata = 1
	# PSU: hrn                                       Number of PSUs   = 6950
												   # Population size  = 55042871
	# ---------------------------------------------------------------------------
	# Index    |  Estimate   Std. Err.      z      P>|z|     [95% Conf. Interval]
	# ---------+-----------------------------------------------------------------
	# GE(-1)   |  .1602358   .00936931    17.10    0.000      .1418723   .1785993
	# MLD      |   .127616   .00332187    38.42    0.000      .1211052   .1341267
	# Theil    |  .1337177   .00406302    32.91    0.000      .1257543    .141681
	# GE(2)    |  .1676393   .00730057    22.96    0.000      .1533304   .1819481
	# GE(3)    |  .2609507   .01850689    14.10    0.000      .2246779   .2972235
	# ---------------------------------------------------------------------------

**Comment by guilhermejacob** [comment]
commit 4eb04e02bceecb4cab4d226e89bffa97658c4b1d adds `GE(-1)` and its decomposition

**Comment by ajdamico** [comment]
added, thanks!
