### ISSUE TITLE
Add var-cov matrix for inequality decomposition

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#178]

**Comment by ajdamico** [comment]
nice.  thinking out loud:
1) should this be an attribute contained inside the `rval` result of other functions?
2) how should this be tested with `testthat`?
3) how should this be documented for users?

**Comment by guilhermejacob** [comment]
1. Yes, i think so. But the print method should only show variances;
2. Probably, but I have to think about that a bit more;
3. I'll think about that. An example of its usability can be useful: calculate the variance of the differences between total index, between- and within- components.

**Comment by guilhermejacob** [comment]
done!
