### ISSUE TITLE
print.cvydstat not working

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#180]
Although `print.cvydstat` exists in the package, it only works if explicitly called:
```
library(survey)
library(convey)
library(vardpoor)
data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

# linearized design
des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
des_eusilc <- convey_prep(des_eusilc)

# unstructured result
svygeidec( ~eqincome , ~hsize , subset(des_eusilc, eqincome > 0) )

# how it should look like:
convey:::print.cvydstat(svygeidec( ~eqincome , ~hsize , subset(des_eusilc, eqincome > 0) ) )
```
can you help me with that?

**Comment by ajdamico** [comment]
hi, the function just needs to be exported.  https://github.com/DjalmaPessoa/convey/commit/dec4cf064124296e7e69ec369806a53c9385fd6d  i've exported both `print.cvydstat` and also `print.cvystat` and it looks like there are some bugs with how the functions are being used?  https://travis-ci.org/DjalmaPessoa/convey

**Comment by guilhermejacob** [comment]
working now. thanks!
