### ISSUE TITLE
create a replication vignette for svyarpr

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#183]

**Comment by ajdamico** [comment]
@DjalmaPessoa any edits to this?  please close this issue if you're okay with it..thanks!

https://guilhermejacob.github.io/context/2-1-at-risk-of-poverty-ratio-svyarpr.html#at-risk-of-poverty-ratio-svyarpr

**Comment by DjalmaPessoa** [comment]
I just suggest  excluding this sentence:

"The ultimate cluster method is marginally less conservative, therefore, we do not recommend using it as the default."

**Comment by ajdamico** [comment]
that sentence occurs in three places.  should it be removed from all three
examples?  svyarpr, svyarpt, and svygini.  thanks

https://github.com/guilhermejacob/context/search?utf8=%E2%9C%93&q=The+ultimate+cluster+method+is+marginally+less+conservative%2C+therefore%2C+we+do+not+recommend+using+it+as+the+default

**Comment by DjalmaPessoa** [comment]
Yes, please.

**Comment by ajdamico** [comment]
it'll be removed in my next commit..thanks
