### ISSUE TITLE
create a replication vignette for svygini

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#188]

**Comment by ajdamico** [comment]
this has been added to the book..  @DjalmaPessoa please look it over and close this issue if you're ok with it?  thanks

**Comment by ajdamico** [comment]
@DjalmaPessoa  https://guilhermejacob.github.io/context/3-2-gini-index-svygini.html#gini-index-svygini

**Comment by ajdamico** [comment]
@djalmapessoa this svygini example seems to me like a good way to gain users' trust

**Comment by DjalmaPessoa** [comment]
In all examples compairing results from vardpoor and convey it was raised that there are differences  between variance estimates. The reason why should be completed by showing that the linearized variables match in both libraries. 
It is more important to check two things: point estimates  and linearized variables match. 
In the explanation, it should be mentioned that the variances are estimated by the formulas ??? and ??? (need to number these formulas) and the the z's in both libraries are the same.

**Comment by ajdamico** [comment]
could you add it?  thanks

**Comment by DjalmaPessoa** [comment]
I'll do for the arpt and then you check if it is ok

**Comment by DjalmaPessoa** [comment]
In explaining why the variances estimates are different it is said: 
"because `library(vardpoor)` defaults to the ultimate cluster method"

Ultimate cluster means to use only the information in the first level cluster (psu) . Both vardpoor and survey defaults to that. The diference is that vardpoor defines an fpc that we don't use in survey.

So perhaps this explanation has to be improved.

**Comment by ajdamico** [comment]
please do

**Comment by DjalmaPessoa** [comment]
I just did it.
I have mentioned that the linearized variables are the same in all examples but only shown  for svyarpr.
Should we show for all examples?

**Comment by ajdamico** [comment]
whatever you think makes the most sense  :)

**Comment by DjalmaPessoa** [comment]
I included a test compairing the linearized variable in all examples. Also, I included an example for svyrmir that now matches with varpoord.

**Comment by ajdamico** [comment]
funny, i added a svyrmir example as well but it looks like you beat me to
it so i am not pushing my version to github.  yours is better.  thanks!

**Comment by DjalmaPessoa** [comment]
please check copy and paste errors in the svyrmir example. I copied from the svyrmpg example and changed were necessary. Hope it is ok.

**Comment by ajdamico** [comment]
looks good to me
