### ISSUE TITLE
confint for svyrep not working

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#19]
des_eusilc <- survey:::svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
des_eusilc_rep <- as.svrepdesign(des_eusilc, type= "bootstrap")
des_eusilc_rep <- convey_prep(des_eusilc_rep)
b1 <- svyarpr(~eqIncome, design = des_eusilc_rep, 0.5, 0.6)
confint(b1)

**Comment by ajdamico** [comment]
nice catch, thanks!  re-synch and re-install, it works now  :)

https://github.com/DjalmaPessoa/convey/commit/bd728c8c0a9e2370261ed9986480f7aa77fa87fd
