### ISSUE TITLE
create a replication vignette for svyfgt

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#196]

**Comment by ajdamico** [comment]
@DjalmaPessoa i have added a replication example for svyfgt to the book.  could you please look it over and close this issue if it looks okay?  thanks!

**Comment by ajdamico** [comment]
i thought the purpose of the replication examples was to prove that our code works as expected?  if you arbitrarily pick 10000 as the threshold, then we are no longer reproducing statistics published by other researchers.  at that point, i don't understand what the example adds beyond what is already in the ?svyfgt help page..

**Comment by DjalmaPessoa** [comment]
It seems that you did not understand my point. So I will explain by parts:

1. When we estimate the rate of poor people, there are 2 different situations:  either the threshold is fixed or estimated;
2. When you take the threshold= .6*quantile you are estimating the threshold, even being a wrong estimate.
3. When you estimate the poverty rate this should be reflected not only in the point estimate of the rate but also in its se estimate.
4. When we estimate the threshold, this source of variation should be considered when estimating  the se of the poverty rate.
5. In your example there are 2 errors: 
a) the estimate of poverty line is wrong and
 b) when you estimate the se of the poverty rate you do not take into account the fact that you estimated the threshold.

This is to force too much to agree with someone's result. I would do that inly if the guy had a nobel prize in statistics. haha

**Comment by ajdamico** [comment]
hi, could you or @guilhermejacob find a published example of foster greer thorbecke that we could replicate?  i'll rewrite the replication text if we can find a more appropriate example that has statistics and standard errors (or confidence intervals) that can be reproduced with our `svyfgt` function..  thanks

**Comment by guilhermejacob** [comment]
@ajdamico , you could try replicating Stata `poverty` module. [Apparently, Van Kerm was aware of the problem of using relative poverty lines.](http://www.stata.com/meeting/germany09/vankerm.pdf#page=16).
I'll keep looking, though.

**Comment by ajdamico** [comment]
added a bit more detail but generally the same..  thanks djalma!  https://github.com/guilhermejacob/context/commit/910f795eab22445a5bcb9f836d07bf6fb58a555c
