### ISSUE TITLE
please add more detail to `g=0, 1, 2` descriptions for svyfgt?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#200]
in both the book and also the ?svyfgt help file?

right now, the ?svyfgt help file just says `Measures with g=1 or g=2 also have a natural interpretation`  ..should it say something about this?  i don't think "a natural interpretation" is specific enough?

could you add more detail about these three things in the book?  thanks!

    FGT(0): headcount ratio (proportion poor)
    FGT(1): average normalised poverty gap
    FGT(2): average squared normalised poverty gap

**Comment by guilhermejacob** [comment]
Actually, you can also see it in another way:

If `g=0`, the FGT index equals the poverty headcount ratio, which accounts for the spread of poverty. If `g=1`, FGT is the mean of the normalized income shortfall of the poor. By doing so, the measure takes into account both the spread and the intensity of poverty. When `g=2`, the relative weight of larger shortfalls increases even more, which yields a measure that accounts for poverty severity, i.e., the inequality among the poor. This way, a transfer from a poor person to an even poorer person would reduce the FGT(2).

**Comment by DjalmaPessoa** [comment]
Awesome!

**Comment by DjalmaPessoa** [comment]
completed the documentation for g=1 and g=2 in the library.
I'll see what can be done in the book

**Comment by DjalmaPessoa** [comment]
The book defines the FGT for g=0 and for g >= 1.  Perhaps we can include Guilherme's explanation of  19 Dec 2016 in the book. What do you think?

**Comment by ajdamico** [comment]
fine with me..

**Comment by ajdamico** [comment]
looks great, thank you
