### ISSUE TITLE
why does svygini not match the stata svylorenz command's gini coefficient?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#201]
# load the convey package
	library(convey)

	# load the survey library
	library(survey)

	# load the foreign library
	library(foreign)

	# create a temporary file on the local disk
	tf <- tempfile()

	# store the location of the presentation file
	presentation_zip <- "http://repec.org/nasug2006/nasug2006_jenkins.zip"

	# download jenkins' presentation to the temporary file
	download.file( presentation_zip , tf , mode = 'wb' )

	# unzip the contents of the archive
	presentation_files <- unzip( tf , exdir = tempdir() )

	# load the institute for fiscal studies' 1981, 1985, and 1991 data.frame objects
	x81 <- read.dta( grep( "ifs81" , presentation_files , value = TRUE ) )
	x85 <- read.dta( grep( "ifs85" , presentation_files , value = TRUE ) )
	x91 <- read.dta( grep( "ifs91" , presentation_files , value = TRUE ) )

	# stack each of these three years of data into a single data.frame
	x <- rbind( x81 , x85 , x91 )

	# initiate a linearized survey design object
	y <- svydesign( ~ hrn , data = x , weights = ~ wgt )

	# immediately run the `convey_prep` function on the survey design
	z <- convey_prep( y )

	z81 <- subset( z , year == 1981 )

	z91 <- subset( z , year == 1991 )

	# this number matches the number of observations on PDF page 15
	# http://www.stata.com/meeting/12uk/uksug2006_jenkins.pdf#page=15
	nrow( z81 )

	# this gini coefficient does not exactly match bottom of PDF page 25
	# http://www.stata.com/meeting/12uk/uksug2006_jenkins.pdf#page=24
	svygini( ~ eybhc0 , z81 )

	# this number matches the number of observations on PDF page 22
	# http://www.stata.com/meeting/12uk/uksug2006_jenkins.pdf#page=22
	nrow( z91 )

	# this gini coefficient does not exactly match bottom of PDF page 24
	# http://www.stata.com/meeting/12uk/uksug2006_jenkins.pdf#page=24
	svygini( ~ eybhc0 , z91 )

**Comment by guilhermejacob** [comment]
Just to add: Jenkins uses the Gini formula of [Kovacevic & Binder (1997)](http://www.jos.nu/Articles/abstract.asp?article=13141). The estimator we use, from Osier (2009) is slighty different.
Page 24 is actually (an approximation to) the share of income the richest 90% owns. It is slightly different from the `svylorenz` because of its interpolation, but matches this:
```
1 - ( coef(svyisq( ~ eybhc0 , z91, alpha = .9 )) / coef( svyisq( ~ eybhc0 , z91, alpha = 1 ) ) )
```
The interpolation is useful because it returns a convex Lorenz curve (without the steps of the cdf).

**Comment by ajdamico** [comment]
is it reasonable to add a parameter to `svygini` that allows the user to choose between the two methods?

**Comment by guilhermejacob** [comment]
I don't really know. This would add a lot of code to the program. Maybe i have this from some previous work.

**Comment by ajdamico** [comment]
might not be worth it, then?  but gini is popular, so not sure.  @DjalmaPessoa does `svygini` match anything published? -- trying to avoid replicating `vardpoor` if possible?

**Comment by DjalmaPessoa** [comment]
yes, it matches results from IBGE. Recently, Guilherme computed results for
different years and they matched IBGE results. Also, I believe they match
vardpoor results.

**Comment by guilhermejacob** [comment]
I agree with @DjalmaPessoa . And this is an old version of Stata's `svylorenz` software. It might have changed.
Kovacevic-Binder Gini are only different for SEs. (Just wrote the function here).

**Comment by ajdamico** [comment]
thanks.  i'll use vardpoor for the svygini vignette in the book, then.  i think the more variety in the sources that we replicate, the better - so would like to avoid only replicating vardpoor if possible
