### ISSUE TITLE
svygini does not match varpoord's lingini

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#203]
the current testthat script runs `SE_lin2` on the output of vardpoor to get matching numbers, but we should match the variance estimates produced by vardpoor, even if they are not the default for convey.

https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-svygini.R

	library(convey)
	library(survey)
	library(vardpoor)

	data(eusilc) 

	names( eusilc ) <- tolower( names( eusilc ) )

	des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )

	des_eusilc <- convey_prep(des_eusilc)

	dati <- data.table(IDd = 1 : nrow(eusilc), eusilc)

	aa <-
		varpoord(
			Y = "eqincome", 
			w_final = "rb050",
			ID_level1 = "IDd",
			H = "db040", 
			N_h = NULL ,
			PSU = "rb030", 
			dataset = dati, 
			type = "lingini"
		)
		

	# does not match
	aa$all_result$var
	attr( svygini( ~ eqincome , des_eusilc ) , 'var' ) * 10000

	# does not match
	aa$all_result$se
	SE( svygini( ~ eqincome , des_eusilc ) ) * 100

**Comment by DjalmaPessoa** [comment]
just take a look at: convey/ tests/testthat/test-svygini.R
all tests are passing.

**Comment by ajdamico** [comment]
i did.  you are using a function you wrote and not `lingini`

On Dec 20, 2016 1:22 PM, "DjalmaPessoa" <notifications@github.com> wrote:

just take a look at: convey/ tests/testthat/test-svygini.R
all tests are passing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DjalmaPessoa/convey/issues/203#issuecomment-268241501>,
or mute the thread

**Comment by DjalmaPessoa** [comment]
I'm using lingini! You mean I'm not using vardpoor function???

vardpoor_ginid <- lingini(Y = "eqincome", id = "IDd", weight = "rb050", Dom = c("hsize"),    dataset = dati)

**Comment by DjalmaPessoa** [comment]
There are two things we should check:

1. point estimates of the gini
2. linearized variable of gini to compute the variance.

With 2 I just have to compute the variance of a total. In this case I trust
in survey rather than in vardpoor.

1 and 2 are the same for survey  and vardpoor!

**Comment by ajdamico** [comment]
it is only the same because you use your own `SE_lin2` i think? something in that computation differs from what vardpoor does by default.  could you figure out why the numbers in my minimal reproducible example differ?  thanks

**Comment by DjalmaPessoa** [comment]
Once we asked this question to the vardpoor people. 
They compute the variance of a **total** using a modified version of the ultimate cluster method. 
I mentioned that the library survey does it in a  different way  using the formula  we find in all  textbooks. Their answer was that in the Statistics Office they work it is used some sort of correction. I don't think this is a good reason to explain anything!
But if you wish we can adopt their way. Its an easy modification and once I've matched exactly their results using this variance function. I just have have to recover it in some old file. But I'd be glad to do it if it makes you happy.

**Comment by ajdamico** [comment]
hi, we do not need to match others by default.  we just need to demonstrate that we can match the default output of someone else's gini calculation.  if you can add an ultimate cluster parameter to `svygini` that defaults to `FALSE` but matches vardpoor when it's set to `TRUE` then that would solve this problem.  alternatively, if you can match any other gini coefficient and standard error, that would be enough.  i've tried two different replication scripts, and neither have lined up (other here: https://github.com/DjalmaPessoa/convey/issues/201) thanks djalma

**Comment by DjalmaPessoa** [comment]
In order to get the same variance of a total as vardpoor, using the library survey,  we need to introduce in the design definition  a fpc. argument  Just create a variable N that defines the size of the population strata.  They used the sum of weights of the units in the stratum to define N.  So, if you wish, you just create this  N and define the design object:

des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , fpc=~ N, data = eusilc )

Using this, you match the results with vardpoor not only for gini but also for all the other measures.

Therefore it is not a matter of defining an option in the function svygini.  It is the problem of estimating the variance of the total of a variable (any variable). Ultimate Cluster means a different thing for the vardpoor library.

**Comment by ajdamico** [comment]
perfect
