### ISSUE TITLE
svyafcdec ignores subgroup parameter

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#211]
library(survey)
	library(convey)
	library(webuse)

	webuse("nlsw88")

	nlsw88 <- data.frame( nlsw88 )

	nlsw88$collgrad <- factor( as.numeric( nlsw88$collgrad ) , label = c( 'not college grad' , 'college grad' ) , ordered = TRUE )
	nlsw88$psu <- 1

	# linearized design
	des_nlsw88 <- svydesign( ids = ~1 , data = nlsw88 )
	des_nlsw88 <- convey_prep(des_nlsw88)

	# looks correct
	svyafcdec(~wage+collgrad+hours, ~1, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T )

	# looks incorrect
	svyafcdec(~wage+collgrad+hours, ~married, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T )

**Comment by guilhermejacob** [comment]
it's another issue with labelled variables. do:
```
svyafcdec(~wage+collgrad+hours, ~factor(married), design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T )
```

**Comment by guilhermejacob** [comment]
last commit issues an error if subgroup variable is of class 'labelled'.

**Comment by ajdamico** [comment]
thanks
