### ISSUE TITLE
Why is Travis timing out?

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#215]
@ajdamico , check [this](https://travis-ci.org/DjalmaPessoa/convey/builds/186650383).
Can you extend the time? Or is it something with the tests?
Thanks!

**Comment by ajdamico** [comment]
hi, it's a monetdblite bug that's causing it to hang (happens occasionally on sisyphus), not worth your time worrying about.  hannes will surely update on cran long before we are ready with 0.2.0

http://monetdb.cwi.nl/testweb/web/sisyphus/
