### ISSUE TITLE
svybmi linearized & replication design results do not always match

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#217]
library(survey)
	library(convey)

	n <- 50

	set.seed( n )

	dist_frame <-
		data.frame( 
			wt_binom_two = rbinom( n , 1 , .5 ) ,
			wt_binom = rbinom( n , 1 , .5 ) ,
			wt_unif = runif( n ) ,
			beta_050_050 = rbeta( n , 0.5 , 0.5 ) ,
			beta_500_100 = rbeta( n , 5 , 1 ) ,
			beta_100_300 = rbeta( n , 1 , 3 ) ,
			beta_200_200 = rbeta( n , 2 , 2 ) ,
			beta_200_500 = rbeta( n , 2 , 5 ) ,
			pois1 = rpois( n , 1 ) ,
			pois100 = rpois( n , 100 ) ,
			sex = ifelse( rbinom( n , 1 , 0.5 ) , "male" , "female" ) ,
			age = sample( 0:99 , n , replace = TRUE )
		)
		
	dist_frame[ -which( names( dist_frame ) == 'sex' ) ] <- sapply( dist_frame[ -which( names( dist_frame ) == 'sex' ) ] , as.numeric )
		
	lin_des <- convey_prep( svydesign( ~ 1 , data = dist_frame , weight = ~ wt_binom ) )

	rep_des <- convey_prep( as.svrepdesign( lin_des , type = 'bootstrap' ) )

	lin_des <- subset( lin_des , pois100 > 0 )
	rep_des <- subset( rep_des , pois100 > 0 ) 

	lin_res <- svybmi( ~ pois100 + wt_binom_two , lin_des )
	rep_res <- svybmi( ~ pois100 + wt_binom_two , rep_des )

	# coefficients should be equal
	stopifnot( coef( lin_res ) == coef( rep_res ) )

**Comment by guilhermejacob** [comment]
commit 070d5699f5011c8db205ecd0ca4e9ab8b552ed5a fixed it

**Comment by ajdamico** [comment]
just ran the skewed distributions testthat and got this?

	[1] "testing functions work on weird distributions binom pois100"
	 Show Traceback
	 
	 Rerun with Debug
	 Error: Test failed: 'functions work on weird distributions binom pois100'
	* coef(lin_res) not equal to coef(rep_res).
	1/1 mismatches
	[1] 0.684 - 0.69 == -0.00631 In addition: There were 37 warnings (use warnings() to see them)
	> 
	> 
	> FUN
	function( formula, design, ...) {

	  UseMethod("svybmi", design)

	}
	<environment: namespace:convey>

**Comment by ajdamico** [comment]
nvm sorry didn't reload my bad
