### ISSUE TITLE
why does svyrmir not match vardpoor when using ultimate cluster?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#219]
minimal reproducible example of the discrepancy.  i was under the impression that the last two pairs of statistics would be the same?  the coefficients do match, just not the standard errors or variances.  thanks!

	# load the convey package
	library(convey)

	# load the survey library
	library(survey)

	# load the vardpoor library
	library(vardpoor)

	# load the synthetic european union statistics on income & living conditions
	data(eusilc)

	# make all column names lowercase
	names( eusilc ) <- tolower( names( eusilc ) )

	# add a column with the row number
	dati <- data.table(IDd = 1 : nrow(eusilc), eusilc)

	# calculate the rmir coefficient
	# using the R vardpoor library
	varpoord_rmir_calculation <-
		varpoord(
		
			# analysis variable
			Y = "eqincome", 
			
			# weights variable
			w_final = "rb050",
			
			# row number variable
			ID_level1 = "IDd",
			
			# strata variable
			H = "db040", 
			
			N_h = NULL ,
			
			# clustering variable
			PSU = "rb030", 
			
			# data.table
			dataset = dati, 
			
			# rmir coefficient function
			type = "linrmir" ,
			
			# age variable
			age = "age"
		)

	# all calculations produced by vardpoor::linrmir
	varpoord_rmir_calculation$all_result

	# construct a survey.design
	# using our recommended setup
	des_eusilc <- 
		svydesign( 
			ids = ~ rb030 , 
			strata = ~ db040 ,  
			weights = ~ rb050 , 
			data = eusilc
		)

	# immediately run the convey_prep function on it
	des_eusilc <- convey_prep( des_eusilc )

	# coefficients do match
	varpoord_rmir_calculation$all_result$value
	coef( svyrmir( ~ eqincome , des_eusilc , age = ~ age ) )

	# variances do not match exactly
	attr( svyrmir( ~ eqincome , des_eusilc , age = ~ age ) , 'var' )
	varpoord_rmir_calculation$all_result$var

	# standard errors do not match exactly
	varpoord_rmir_calculation$all_result$se
	SE( svyrmir( ~ eqincome , des_eusilc , age = ~ age ) )

	# within each strata, sum up the weights
	cluster_sums <- aggregate( eusilc$rb050 , list( eusilc$db040 ) , sum )

	# name the within-strata sums of weights the `cluster_sum`
	names( cluster_sums ) <- c( "db040" , "cluster_sum" )

	# merge this column back onto the data.frame
	eusilc <- merge( eusilc , cluster_sums )

	# construct a survey.design
	# with the fpc using the cluster sum
	des_eusilc_ultimate_cluster <- 
		svydesign( 
			ids = ~ rb030 , 
			strata = ~ db040 ,  
			weights = ~ rb050 , 
			data = eusilc , 
			fpc = ~ cluster_sum 
		)

	# again, immediately run the convey_prep function on the `survey.design`
	des_eusilc_ultimate_cluster <- convey_prep( des_eusilc_ultimate_cluster )

	# DOES NOT MATCH
	attr( svyrmir( ~ eqincome , des_eusilc_ultimate_cluster , age = ~ age ) , 'var' )
	varpoord_rmir_calculation$all_result$var

	# DOES NOT MATCH
	varpoord_rmir_calculation$all_result$se
	SE( svyrmir( ~ eqincome , des_eusilc_ultimate_cluster , age = ~ age ) )

**Comment by DjalmaPessoa** [comment]
To see the reason why the variances are different, we have to compare the linearized variables by convey and by vardpoor:

library(survey)
      library(vardpoor)
      library(convey)
      data(eusilc)
      des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
      des_eusilc <- convey_prep( des_eusilc)
      
      # get the linearized variable using vardpoor:
      
      dati <- data.frame(IDd = 1:nrow(eusilc), eusilc)
      
      vardpoor_rmirw <- linrmir(Y="eqIncome", id="IDd",  age="age", weight="rb050",
        Dom=NULL, dataset=dati, order_quant=50)
      
      # get the linearized variable using convey:
      
      convey_eusilc_rmir <-svyrmir(~eqIncome, des_eusilc,  age=~age, agelim=65 )
      
      # compare the linearized variable from the two libraries:
      
      all.equal(vardpoor_rmirw$lin$lin_rmir, attr(convey_eusilc_rmir,"lin")[,1])
      
      summary(vardpoor_rmirw$lin$lin_rmir)
      summary(attr(convey_eusilc_rmir,"lin")[,1])
      
      # there is a small difference in the linearized variables.  I'll try to figure out why.

**Comment by ajdamico** [comment]
thanks djalma

**Comment by DjalmaPessoa** [comment]
For some reason I don't recall in the file test-svymir.R there are only tests comparing the estimates. No tests for variances!

**Comment by ajdamico** [comment]
i don't understand what you mean?  `test-svyrmir.R` has all of the tests i'd expect it to?  these are supposed to be tests btw svydesign and svrepdesign not tests against vardpoor.  replicating external software is only in the textbook..

**Comment by DjalmaPessoa** [comment]
There are 2 files for each function test extracts and test. The first compares btw svydesign and svyrep the second, test-svyrmir.R, compares btw convey and vardpoor

**Comment by ajdamico** [comment]
ahh right, gotcha

**Comment by DjalmaPessoa** [comment]
I found out the reason why vardpoor and convey get different linearized variables in rmir:

          library(vardpoor)
          data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
          library(survey)
          des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
          library(convey)
          des_eusilc <- convey_prep(des_eusilc)
          ## no missing in age !
          sum(is.na(eusilc$age))
          
          
          
          quant_under_65 <- survey::svyquantile(~eqincome, design =subset(des_eusilc, age<65), quantiles = .5,method = "constant")
          
          quant_over_65 <- survey::svyquantile(~eqincome, design =subset(des_eusilc, age>=65), quantiles = .5,method = "constant")
          
          ## this function computes the linearized variable in vardpoor
          
          lin_vardpoor_rmir <- vardpoor:::rmirlinCalc(
            Y1 = eusilc$eqincome,
            ids= 1:nrow(eusilc),
            wght=eusilc$rb050,
            indicator= rep(1, nrow(eusilc)),
            order_quants = 50,
            age_under_65 = eusilc$age <65,
            quant_under_65 = as.vector(quant_under_65),
            quant_over_65 = as.vector(quant_over_65)
             )
          
          
          
          
          
          ###  compute the linearized variable in  convey
          
          incvar <-eusilc$eqincome
          w <- eusilc$rb050
          
          h <- h_fun(incvar,w)
          
          ind1<- eusilc$age <65
          
          h1<- h_fun(incvar*ind1, w*ind1)
          dsub1 <- subset(des_eusilc, age<65)
          q_alpha1 <- survey::svyquantile(~eqincome, design = dsub1, quantiles = .50,method = "constant")
          q_alpha1 <- as.vector(q_alpha1)
          
          
          # Fprime1 <- densfun(~eqincome, design = dsub1, q_alpha1, h=h1, FUN = "F") # convey
          Fprime1 <- densfun(~eqincome, design = dsub1, q_alpha1, h=h, FUN = "F") # vardpoor
          N1 <- sum(w*ind1)
          linquant1 <- -( 1 / ( N1 * Fprime1 ) ) *ind1* ( ( incvar <= q_alpha1 ) - .5 )
          
          ind2<- eusilc$age >= 65
          dsub2 <- subset(des_eusilc, age>= 65)
          
          
          h2<- h_fun(incvar*ind2, w*ind2)
          
          q_alpha2 <- survey::svyquantile(~eqincome, design = dsub2, quantiles = .5, method = "constant")
          q_alpha2 <- as.vector(q_alpha2)
          
          
          # Fprime2 <- densfun(~eqincome, design = dsub2, q_alpha2, h=h2, FUN = "F") ## convey
          Fprime2 <- densfun(~eqincome, design = dsub2, q_alpha2, h=h, FUN = "F") # vardpoor
          N2 <- sum(w*ind2)
          
          linquant2 <- -( 1 / ( N2 * Fprime2 ) ) *ind2* ( ( incvar <= q_alpha2 ) - .5 )
          # linearize ratio of medians
          
          MED1 <- list(value = q_alpha1 , lin = linquant1 )
          MED2 <- list(value = q_alpha2 , lin = linquant2 )
          list_all<- list(MED1=MED1, MED2=MED2)
          
          RMED <- contrastinf(quote(MED2/MED1),list_all)
          rval <- as.vector(RMED$value)
          lin <- RMED$lin
          
          lin_vardpoor <- lin_vardpoor_rmir$lin$lin
          attributes(lin_vardpoor)<- NULL
          
          all.equal(lin[,1],lin_vardpoor)
          
            # Note that in vardpoor **h** is computed using the whole sample.
            #  in convey it is used **h1**  and  **h2**  based on the subsamples  age<65 and age>=65

**Comment by ajdamico** [comment]
great, thanks!  are you going to edit svyrmir or is the current behavior
what you expect to keep as the default?

**Comment by DjalmaPessoa** [comment]
It is not so clear what do do. The  h  is the bandwidth value used to estimate the density function. In our case we have the estimaion of two densities using unit weights.  One for people with age < 65 and the other for people with age>=65. 
The problem is: should we use the h estimated from the whole population or to use one h for each group? 
In convey we adopted the second option.  Right now, I'm not able to give a strong justification for that.

**Comment by ajdamico** [comment]
my general preference is to match other software unless we have a good
justification for not doing so (for example, you have a good justification
for not using ultimate cluster by default).  which calculation results in a
larger variance?  if vardpoor's technique is more conservative (larger
error terms), that's another reason we should consider switching

**Comment by DjalmaPessoa** [comment]
I don't think it is possible to say that vardpoor's technique is more conservative. 
I have to consult reliable sources to justify our choice.

**Comment by DjalmaPessoa** [comment]
I just fixed svyrmir. I believe now the linearized variable matches the result in vardpoor. Could you please run the initial script?

**Comment by ajdamico** [comment]
perfect.  thanks djalma!
