### ISSUE TITLE
?svyrmir help page examples do not have all of the necessary parameters

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#22]
see the examples at

https://github.com/DjalmaPessoa/convey/blob/master/R/svyrmir.R#L42-L52

could you update these with a variable that makes sense?  thanks!  each of these break with

	> svyrmir( ~eqIncome , design = des_eusilc_rep )
	Error in terms.formula(age) : argument "age" is missing, with no default
	> 
	> # linearized design using a variable with missings
	> svyrmir( ~ py010n , design = des_eusilc )
	Error in terms.formula(age) : argument "age" is missing, with no default
	> svyrmir( ~ py010n , design = des_eusilc , na.rm = TRUE )
	Error in terms.formula(age) : argument "age" is missing, with no default
	> # replicate-weighted design using a variable with missings
	> svyrmir( ~ py010n , design = des_eusilc_rep )
	Error in terms.formula(age) : argument "age" is missing, with no default
	> svyrmir( ~ py010n , design = des_eusilc_rep , na.rm = TRUE )
	Error in terms.formula(age) : argument "age" is missing, with no default
	>

**Comment by DjalmaPessoa** [comment]
What's py010n? Should we exclude this example?

This function should have an argument sex. It measures the  gender pay
(wage) gap.

**Comment by ajdamico** [comment]
i just picked it randomly.. you could use whatever variables make sense to
you

**Comment by DjalmaPessoa** [comment]
Before, I'd like to test NA treatment for svyrep

**Comment by DjalmaPessoa** [comment]
I've included tests for svyrep designs with NA treatment. In the examples
all functions are working ok.

**Comment by ajdamico** [comment]
radical

**Comment by ajdamico** [comment]
closing because i believe this issue is resolved?  but re-open if i'm making a mistake..thanks
