### ISSUE TITLE
test-svyqsr.R   is not passing

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#220]
I dont't understand how convey is passing in Travis:

just check:

library(testthat)
source('~/GitHub/convey/tests/testthat/test-svyqsr.R')

**Comment by ajdamico** [comment]
works fine for me..what error do you get?

	> library(convey)
	> library(testthat)
	> source( "C:\\Users\\anthonyd\\Documents\\GitHub\\convey\\tests\\testthat\\test-svyqsr.R" )
	Loading required package: grid
	Loading required package: Matrix
	Loading required package: survival

	Attaching package: ‘survey’

	The following object is masked from ‘package:graphics’:

		dotchart

	Loading required package: data.table
	data.table 1.10.5 IN DEVELOPMENT built 2017-02-06 09:01:22 UTC
	  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
	  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
	  Release notes, videos and slides: http://r-datatable.com
	Loading required package: laeken
	Loading required package: boot

	Attaching package: ‘boot’

	The following object is masked from ‘package:survival’:

		aml

	Loading required package: MASS
	Loading required package: stringr

**Comment by DjalmaPessoa** [comment]
I just installed the last version of vardpoor from github and it worked fine!
