### ISSUE TITLE
additional svygpg and svyqsr text detail

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#228]
migrated from https://github.com/guilhermejacob/context/issues/9

ajdamico commented on Dec 18, 2016

https://github.com/guilhermejacob/context/search?utf8=%E2%9C%93&q=djalmapessoa_look

@ajdamico
@DjalmaPessoa could you look at these before we send convey 0.2.0 to cran? thanks

DjalmaPessoa commented on Feb 17

the question:
do any of the other functions need to be moved to this wellbeing chapter?
could have a better answer from Guilherme.
The important thing is to include all major functions somewhere.

ajdamico commented on Feb 17

@guilhermejacob

**Comment by DjalmaPessoa** [comment]
I think Guilherme would would be more qualified to answer to this question. I don't know who gave the  name wellbeing for the chapter and why the svygpg and svyqsr  funcctions are in there.

**Comment by guilhermejacob** [comment]
The gender pay gap is not a measure of inequality in the classical sense. It is mostly a comparison across two populations; it does not depend only on income. But svyqsr is an inequality measure and should be described in the chapter.
Finally, I'd suggest adding both to back the inequality chapter (sorry about that). I'll write an explanation for the svygpg in inequality measures.
And get rid of this chapter.

@ajdamico , can you do that and assign the write up back to me?

**Comment by ajdamico** [comment]
@guilhermejacob i've just moved the chapters and fixed a few things because of some vardpoor problems.  we will not be able to build the book until they fix this, so not worth bothering with building the book until that's done.  https://github.com/CSBLatvia/vardpoor/pull/14

**Comment by ajdamico** [comment]
the vardpoor people fixed the bugs this morning so i've uploaded a newly built book..  this issue is back to you

**Comment by guilhermejacob** [comment]
b2ded77bdfc5dc146fd65171ebb38211ac37cbcf solves this. 
Closing it, ok?

**Comment by ajdamico** [comment]
thanks guilherme!
