### ISSUE TITLE
break testthats into smaller chunks so we stop flirting with >5 secs on cran checks

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#229]

**Comment by DjalmaPessoa** [comment]
I've already uploaded the way its!

**Comment by ajdamico** [comment]
milestone for this is `0.3.0`

**Comment by ajdamico** [comment]
fixed by https://github.com/DjalmaPessoa/convey/commit/79bf31bac19c0fb1d3b6a5d1149c9e7db7214e92
