### ISSUE TITLE
Error in UseMethod("SE_lin2", design) :    no applicable method for 'SE_lin2' applied to an object of class "c('survey.design2', 'survey.design')"

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#23]
library(vardpoor)
    data(eusilc)
    dati = data.frame(1:nrow(eusilc), eusilc)
    colnames(dati)[1] <- "IDd"
    library(survey)
    
    # create a design object
    
    des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
    des_eusilc_rep <- as.svrepdesign(des_eusilc, type = "bootstrap")
    
    library(convey)
    des_eusilc <- convey_prep(des_eusilc)
    des_eusilc_rep<- convey_prep(des_eusilc_rep)
    
    # svyfgt for a domain:
    svyfgt(~eqIncome,  subset(des_eusilc, db040=="Tyrol"),  alpha=0)

**Comment by ajdamico** [comment]
when i run the example code you've provided, i do not hit an error?  if i'm missing something, please re-open this issue  :)

	> devtools::install_github("djalmapessoa/convey")
	Downloading github repo djalmapessoa/convey@master
	Installing convey
	"C:/PROGRA~1/R/R-32~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
	  "C:/Users/anthonyd.KFF/AppData/Local/Temp/RtmpeMtI43/devtools11547747170/DjalmaPessoa-convey-0025539"  \
	  --library="C:/Users/anthonyd.KFF/Documents/R/win-library/3.2" --install-tests 

	* installing *source* package 'convey' ...
	** R
	** tests
	** preparing package for lazy loading
	** help
	*** installing help indices
	** building package indices
	** installing vignettes
	** testing if installed package can be loaded
	*** arch - i386
	*** arch - x64
	* DONE (convey)
	> library(vardpoor)
	Loading required package: data.table
	data.table 1.9.6  For help type ?data.table or https://github.com/Rdatatable/data.table/wiki
	The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
	Loading required package: laeken
	Loading required package: boot
	Loading required package: MASS
	Loading required package: stringr
	> data(eusilc)
	> dati = data.frame(1:nrow(eusilc), eusilc)
	> colnames(dati)[1] <- "IDd"
	> library(survey)
	Loading required package: grid

	Attaching package: ‘survey’

	The following object is masked from ‘package:graphics’:

		dotchart

	> 
	> # create a design object
	> 
	> des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	> des_eusilc_rep <- as.svrepdesign(des_eusilc, type = "bootstrap")
	> 
	> library(convey)
	> des_eusilc <- convey_prep(des_eusilc)
	preparing your full survey design to work with R convey package functions

	note that this function must be run on the full survey design object immediately after the svydesign() or svrepdesign() call.

	> des_eusilc_rep<- convey_prep(des_eusilc_rep)
	preparing your full survey design to work with R convey package functions

	note that this function must be run on the full survey design object immediately after the svydesign() or svrepdesign() call.

	> 
	> # svyfgt for a domain:
	> svyfgt(~eqIncome,  subset(des_eusilc, db040=="Tyrol"),  alpha=0)
				 fgt     SE
	eqIncome 0.14444 0.0028
	>
