### ISSUE TITLE
Add function names to test-skewed.R

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#233]
17aa7f944d229a9088b27c2da1a34ad528bc88e7 is a start, but uses the the `statistic` attribute instead.
@ajdamico , can you help with that? Thanks!

**Comment by ajdamico** [comment]
using `statistic` is pretty sneaky!  @guilhermejacob please reopen if this is not what you were looking for?  thanks

https://github.com/DjalmaPessoa/convey/commit/87769c2b7b23a3e4c367fc6334bb5118784f59b3
