### ISSUE TITLE
write an introduction to the poverty chapter

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#234]
https://guilhermejacob.github.io/context/2-poverty.html

**Comment by guilhermejacob** [comment]
I can help you with those

**Comment by ajdamico** [comment]
haha i am turning to other things but intend to do it if it doesn't get done in the next six months  ;)

**Comment by guilhermejacob** [comment]
closed by guilhermejacob/context@76b86452ae44c0a05e7ea4cf9fb66e4d43587285
@ajdamico , reopen if unsatisfied, ok?
