### ISSUE TITLE
how should the references be incorporated into the poverty chapter?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#243]
hi, ctrl+F search for the text "here are the references"  --  that text occurs six times.  should we just add those references at the end of the introductory paragraph of each sub-chapter, or do you want to include a sentence about how you used each source?  thanks!

https://raw.githubusercontent.com/guilhermejacob/context/master/01-poverty.Rmd

**Comment by DjalmaPessoa** [comment]
I believe we have to change the order of presentation. The arpt should come first. I'm tryng to insert the references in a more natural way

**Comment by DjalmaPessoa** [comment]
I've already taken care of "here are the references" . See if you agree and we can close this issue.

**Comment by DjalmaPessoa** [comment]
I have tried to change the order of svyarpt and svyapr and it did not worked.
The natural is to introduce  the arpt first since the arpr is defined in terms of the arpt.

**Comment by ajdamico** [comment]
yes, i made a mistake- see my recent commits.  try refreshing the page?
should be fixed?  i think this issue can be closed..

**Comment by DjalmaPessoa** [comment]
done
