### ISSUE TITLE
NA treatment in variable age in the function svyrmir

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#25]
library(vardpoor)
    data(eusilc)
    dati = data.frame(1:nrow(eusilc), eusilc)
    colnames(dati)[1] <- "IDd"
    library(survey)
    library(convey)

#create a design object
    des_eusilc <- svydesign(ids = ~db040, weights = ~rb050, data = eusilc)
    
    set.seed(123)
    nas<-sample(rownames(eusilc),100,replace=FALSE)
    eusilc$eqIncome0<-eusilc$eqIncome
    eusilc[nas, "eqIncome0"]<-NA
    nas1<-sample(rownames(eusilc),50,replace=FALSE)
    eusilc$age0<-eusilc$age
    eusilc[nas1, "age0"]<-NA

    des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
    des_eusilc_rep <- as.svrepdesign(des_eusilc, type = "bootstrap")
    
    library(convey)
    des_eusilc <- convey_prep(des_eusilc)
    des_eusilc_rep<- convey_prep(des_eusilc_rep)

#test NA treatment for variables eqIncome0 and age
    svyrmir.survey.design( ~eqIncome0 , design = des_eusilc ,age = ~age0, agelim=65, na.rm=TRUE)
    
#function breaks when calling iqalpha. The full_design for iqalpha discards only the NAS from eqIncome0,
#and not the NAs from age0.

**Comment by ajdamico** [comment]
this does not break for me at iqalpha, it breaks at SE_lin2 because the `lin` variable is longer than full_design

	debug: variance <- (SE_lin2(lin, full_design))^2
	Browse[3]> length(lin)
	[1] 14727
	Browse[3]> nrow(full_design)
	[1] 14677
	Browse[3]> 

i believe this is happening because inside of the iqalpha function, you are only excluding missings from the incvar.

	debug: nas <- is.na(incvar)
	Browse[5]> 
	debug: design <- design[!nas, ]
	Browse[5]> 
	debug: df <- model.frame(design)
	Browse[5]> 
	debug: incvar <- incvar[!nas]


you need to extend the missingness removal to the other variables (age in this case) passed in to functions like `svyrmir`  :)

**Comment by DjalmaPessoa** [comment]
The error is derived from the attribute "lin" in the iqalpha function. In the function iqalpha the subsets of design and full_design both exclude the missings in eqIncome. This ok for design but for full_design. This last should ecxlude also the missings in age.  

Possible solutions:

1. To change the function iqalpha (and other functions)  making possible to use more than one variable in the argument formula. In this case,  the function should produce estimates for all the variables and also treat the NAs for all the variables in the argument formula, ( much work)
2. To correct the output of attribute lin of qalpha eliminating the elements corresponding to the NAs in age. (simple solution)
3. To pass to the function iqalpha the appropriate  attribute "full_design", that might not be possible. 

What do you suggest?

**Comment by DjalmaPessoa** [comment]
Treatment of missings in age variable fixed for svyrmir.survey.design. I am going to check if it is working for  svyrmir.svyrep.design.

**Comment by DjalmaPessoa** [comment]
Treatment of missings in age variable fixed for svyrmir.svrep.design.
