### ISSUE TITLE
missing values

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#26]
#Examples in the function svyarpr:      
      library(survey)
      library(vardpoor)
      data(eusilc)
      
#linearized design
      des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
      des_eusilc <- convey_prep( des_eusilc )
      
      
#linearized design using a variable with missings
      svyarpr( ~ py010n , design = des_eusilc )
       svyarpr( ~ py010n , design = des_eusilc , na.rm = TRUE )
#replicate-weighted design using a variable with missings
      svyarpr( ~ py010n , design = des_eusilc_rep )
      svyarpr( ~ py010n , design = des_eusilc_rep , na.rm = TRUE )

#for the third we get an error message and for the second we get (NA NA). Perharps we should change to get also NA NA  in the third example?

**Comment by ajdamico** [comment]
i do not think we should change anything (but please re-open this issue if i am overlooking something).  this behavior mirrors the survey package exactly, which i believe should be our general strategy  :)  here is the output of the same designs and variables passed through `svymean` --

	> svymean( ~ py010n , design = des_eusilc )
		   mean SE
	py010n   NA NA
	> svymean( ~ py010n , design = des_eusilc_rep )
	Error in svrVar(repmeans, scale, rscales, mse = design$mse, coef = rval) : 
	  All replicates contained NAs
