### ISSUE TITLE
An Error: no applicable method for 'svyiqalpha' applied to an object of class "c('convey.design', 'svyimputationList')"

### ISSUE THREAD

**Issue by roman-bm** [DjalmaPessoa/convey#266]
Dear Djalma,

thank you for your great package!

Unfortunately I have the following issue with its usage, i.e., 
> Survey.design2 <- convey_prep( Survey.design1 )
> g <- svygini(~DA1, design = Survey.design2)
Error in UseMethod("svygini", design) : 
  no applicable method for 'svygini' applied to an object of class "c('convey.design', 'svyimputationList')"

my survey design is as follows:
> Survey.design1 = svrepdesign(weights=~HW1,repweights=w,
                          data = imputationList( list( imp1 , imp2 , imp3 , imp4 , imp5 ) ) ,
                          scale = 1, rscales = rep(1/999,1000), mse = FALSE, type = "bootstrap", 
                          combined.weights = TRUE)
It works perfectly with svyquantile, svyby etc. 

thank you.

best regards,
roman

**Comment by ajdamico** [comment]
http://asdfree.com/survey-of-consumer-finances-scf.html
