### ISSUE TITLE
please re-write test-svyatk.R to remove library(plyr)

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#268]
here's the code with the problem:

https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-svyatk.R

from CRAN maintainers:

	These seem to have undeclared package dependencies in their unit test
	code (R files in tests subdirs), see below.

	Can you pls fix as necessary?  (Add the missing package dependencies to
	Suggests, I guess.)

	Please note that these issues are currently not yet detected by the CRAN
	incoming (or regular) checks.

	Best
	-k
	
	

	$convey
	'library' or 'require' call not declared from: ‘plyr’

**Comment by guilhermejacob** [comment]
I wrote this one. Fixing it right now.

**Comment by guilhermejacob** [comment]
Breaks build. Trying another.

**Comment by ajdamico** [comment]
@DjalmaPessoa this issue looks fixed in the development version.  i don't think we need to re-submit to cran urgently
