### ISSUE TITLE
example from  pnad2011

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#27]
library(RSQLite)
    library(downloader)
    library(survey)
    library(convey)

    setwd('C:\\Djalma\\PNAD2012')
    pnad.dbname <- "pnad.db"

    db<- dbConnect(SQLite(),pnad.dbname )
    dbListTables(db)
    dbListFields(db, "pnad2011")

    options( survey.lonely.psu = "adjust" )
    source_url( "https://raw.github.com/ajdamico/usgsd/master/Pesquisa Nacional por Amostra de Domicilios/pnad.survey.R" , prompt = FALSE )

create design: 

      sample.pnad <-
        svydesign(
          id = ~v4618 ,
          strata = ~v4617 ,
          data = "pnad2011" ,
          weights = ~pre_wgt ,
          nest = TRUE ,
          dbtype = "SQLite" ,
          dbname = "pnad.db"
        )

post-stratify:
      y <-
        pnad.postStratify(
          design = sample.pnad ,
          strata.col = 'v4609' ,
          oldwgt = 'pre_wgt'
        )

filter used by IBGE to define Gini index: 

    ysub<- subset(y, v4720!=0 & is.na(v4720)==FALSE & v8005>=15)
    ysub<-convey_prep(ysub)

estimate the mean of v4720: 

    svymean(~as.numeric(v4720), ysub, na.rm=TRUE )

estimate the arpt:

    svyarpt(~as.numeric(v4720), ysub, na.rm=TRUE )

got the error: 
Error in .subset2(x, i, exact = exact) : no such index at level 1

any idea?

**Comment by ajdamico** [comment]
this bug is unrelated to pnad..opening a separate bug report
