### ISSUE TITLE
Dúvida sobre os efeitos do desenho amostral da PNAD

### ISSUE THREAD

**Issue by josimargj** [DjalmaPessoa/convey#270]
Boa noite Djalma,
Se possível, me esclareça uma dúvida: Em se tratando de estimativas de medidas de desigualdade  com base nos dados da PNAD, se se levar em consideração apenas os  pesos amostrais (v1032), mas não a conglomeração e a estratificação (variáveis UPA e estrato), isso afeta os valores das estimativas das medidas ou apenas a variância das estimativas?
Pergunto isso porque tenho utilizado pacotes do STATA (pshare e svylorenz) para estimar diversas medidas de desigualdade de rendimento.  Estes pacotes permitem levar em consideração esses aspectos relevantes do plano amostral (conglomeração, estratificação). Porém, os valores das estimativas são os mesmos que são obtidos se se considera apenas os pesos amostrais. O que muda é a variância das estimativas. É isso mesmo?
Desde já, muito obrigado!

**Comment by DjalmaPessoa** [comment]
Para as estimativas pontuais basta considerar os pesos. 
Para estimar erros-padrão é preciso considerar, além dos pesos,  a estrutura do plano amostral. Para isso deve usar uma library especializada, como  a survey ou a convey. Estimativas de erro-padrão são usadas na construção de intervalos de confiança e na comparação de resultados. Por exemplo, para verificar se há diferença significante entre os valores dos índices para duas Unidades da Federação. Dessa forma, é essencial ter ao lado das estimativas pontuais suas respectivas medidas de precisão.
