### ISSUE TITLE
dynamic statements do not currently work inside any of the functions

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#28]
the way that you are slimming the data.frame object inside of all of the functions down to only the variables for the current computation will not work if the variable is constructed on-the-fly.

here is a reproducible example that produces the bug.  notice the as.numeric() causes the problem.  this should work if we are going to align with the survey package

	library(convey)
	library(survey)
	library(vardpoor)
	data(eusilc)

	# linearized design

	des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
	des_eusilc <- convey_prep( des_eusilc )

	# works
	svyarpt( ~eqIncome , design = des_eusilc )
	# breaks
	svyarpt( ~as.numeric(eqIncome) , design = des_eusilc )

	
you can view the point that this breaks by typing

	debug(convey:::svyarpt.survey.design)

here are the lines leading up the error
	
	Browse[2]> 
	debug: inc <- terms.formula(formula)[[2]]
	Browse[2]> 
	debug: df <- model.frame(design)
	Browse[2]> 
	debug: incvar <- df[[as.character(inc)]]
	Browse[2]> 
	Error in .subset2(x, i, exact = exact) : no such index at level 1

look at the code inside

	survey:::svymean.survey.design
	
and also
	
	survey:::svymean.survey.design2

for ideas about how to work around this issue?

**Comment by DjalmaPessoa** [comment]
survey:::svymean.survey.design treats the case where the formula might have
more than on term like ~var1+var2+... .

The formula argument in convey has only one term.
To fix for this case is very simple:

change

inc <- terms.formula(formula)[[2]] df <- model.frame(design) incvar <-
df[[as.character(inc)]]

to

mf <- model.frame(formula, design$variables, na.action = na.pass) incvar <-
(mf[[1]])

the same for incvec using full_design.

or should we change for the case where formula could be ~var1+var2+...?

**Comment by ajdamico** [comment]
i think the former?  i e-mailed you about why i thought supporting `~var1+var2` was not a good idea?

**Comment by DjalmaPessoa** [comment]
You are concerned about the treatment of NAs considering both variables.
But we could be interested in getting the estimates for var1 and var2  and
even the estimate something like cov(gini(var1), gini(var2)). In this case
we would have to work like in the svymean.

**Comment by ajdamico** [comment]
but cov( svymean(var1) , svymean(var2) ) isn't really much more typing?

**Comment by DjalmaPessoa** [comment]
What I meant was
cov(mean(var1), mean(var2))

**Comment by DjalmaPessoa** [comment]
consider:
data(api)
dclus1<-svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
vcov(svymean(~api00+api99,dclus1))

**Comment by ajdamico** [comment]
i think: this will be a lot of work for you to get it working, users often
get the wrong answer, and the use cases you're presenting probably have
straightforward alternatives?

**Comment by DjalmaPessoa** [comment]
Ok, I'll try to implement the first alternative.

> Em 26/10/2015, às 18:04, Anthony Damico <notifications@github.com> escreveu:
> 
> i think: this will be a lot of work for you to get it working, users often
> get the wrong answer, and the use cases you're presenting probably have
> straightforward alternatives?
> 
> On Mon, Oct 26, 2015 at 4:00 PM, DjalmaPessoa <notifications@github.com>
> wrote:
> 
> > consider:
> > data(api)
> > dclus1<-svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
> > vcov(svymean(~api00+api99,dclus1))
> >
> >

**Comment by DjalmaPessoa** [comment]
all functions changed and working with ~as.numeric(eqIncome)

**Comment by ajdamico** [comment]
awesome!

**Comment by DjalmaPessoa** [comment]
svygini.DBIsvydesign is working for the panad2011 data, but  for svyarpt I
got an error. I just created an issue on that. I know where is breaks but
don't see why.
