### ISSUE TITLE
svyarpt.DBIsvydesign is breaking with pnad data

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#29]
example using pnad2011
        library(RSQLite)
        library(downloader)
        library(survey)
        library(convey)
    
        setwd('C:\\Djalma\\PNAD2012')
        pnad.dbname <- "pnad.db"
    
        db<- dbConnect(SQLite(),pnad.dbname )
        dbListTables(db)
        dbListFields(db, "pnad2011")
    
    
    
        options( survey.lonely.psu = "adjust" )
        source_url( "https://raw.github.com/ajdamico/usgsd/master/Pesquisa Nacional por Amostra de Domicilios/pnad.survey.R" , prompt = FALSE )
    
    
    
 create design
          sample.pnad <-
            svydesign(
              id = ~v4618 ,
              strata = ~v4617 ,
              data = "pnad2011" ,
              weights = ~pre_wgt ,
              nest = TRUE ,
              dbtype = "SQLite" ,
              dbname = "pnad.db"
            )
    
    
          y <-
            pnad.postStratify(
              design = sample.pnad ,
              strata.col = 'v4609' ,
              oldwgt = 'pre_wgt'
            )
    
  filter used by IBGE to define Gini index
    
        ysub<- subset(y, v4720!=0 & is.na(v4720)==FALSE & v8005>=15)
        ysub<-convey_prep(ysub)
    
 estimate the mean of v4720
    
        svymean(~as.numeric(v4720), ysub, na.rm=TRUE )
        svyquantile(~as.numeric(v4720), ysub, .5, na.rm=TRUE )
    
 estimate the arpt:
    
    svyarpt(~as.numeric(v4720), ysub, na.rm=TRUE ) 
        
    svygini(~as.numeric(v4720), ysub, na.rm=TRUE)
    
svyarpt is breaking. After some debuging,  it first breaks at  htot <- h_fun(incvec, wf)
invec and wf have different length. I don't see why?

**Comment by ajdamico** [comment]
is this problem related to the e-mail i sent you titled "bug in missing handling on database-backed designs"  ?  here is the point that the code breaks, and the lengths of the two objects


	Browse[2]> length(iq)
	[1] 351383
	Browse[2]> length(ind)
	[1] 358919
	Browse[2]> length(ind)-length(iq)
	[1] 7536
	Browse[2]> table( is.na( ysub$variables$v4720 ) )

	 FALSE   TRUE 
	351383   7536 
	Browse[2]> 
	Error in names(iq) <- ind : 
	  'names' attribute [358919] must be the same length as the vector [351383]
	>

**Comment by DjalmaPessoa** [comment]
Yes I knew the error was that. I don't see why  those lengths are different? The example with NAs in the documentation is working.

**Comment by DjalmaPessoa** [comment]
I think this has to do with subset of pos-stratified design, please see the example: 

data(api)
    dclus1<-svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
    pop.types <- data.frame(stype=c("E","H","M"), Freq=c(4421,755,1018))
    dclus1p<-postStratify(dclus1, ~stype, pop.types)
    
    dsub<- subset(dclus1p, stype=="E")
    
    dim(dclus1p)
    
    dim(dsub)
    
    dim(model.frame(dsub)[weights(lixo)!=0,])
    
    table(apiclus1$stype) 

I'm going to try to use the zero weights to get the correct df.
But I have to do this just for post-stratified designs.

**Comment by ajdamico** [comment]
the lines

    incvar <- model.frame(formula, design$variables, na.action = na.pass)[[1]]

are the cause, i'm not yet sure of the solution

**Comment by DjalmaPessoa** [comment]
Perhaps it is better to revert?

**Comment by ajdamico** [comment]
no, we have to support ~as.numeric(var1).  if you can't figure it out,
maybe move on to the other issues?  i'll look again next week..

**Comment by DjalmaPessoa** [comment]
working with data frame

    pnad2011<- dbGetQuery( db , 'select v4618 , v4617 , pre_wgt , v4609 , v4720, v8005 from pnad2011' )
    
    pnad2011_des <- svydesign(
      id = ~v4618 ,
      strata = ~v4617 ,
      data = pnad2011 ,
      weights = ~pre_wgt ,
      nest = TRUE
      )
    
    pop.post<- data.frame(v4609= as.character(unique(pnad2011$v4609)), Freq= unique(pnad2011$v4609))
    
    pnad2011_des_pos <- postStratify(pnad2011_des, ~v4609, pop.post)
    
    pnad2011_des_pos_sub <- subset(pnad2011_des_pos, v4720!=0 & is.na(v4720)==FALSE & v8005>=15 )
    
    library(convey)
    pnad2011_des_pos_sub<-convey_prep(pnad2011_des_pos_sub)

    densfun (~as.numeric(v4720), pnad2011_des_pos_sub, 1000, fun = "F", na.rm=TRUE) 
    svyarpt(~as.numeric(v4720),pnad2011_des_pos_sub, na.rm=TRUE )
     svygini (~as.numeric(v4720),pnad2011_des_pos_sub, na.rm=TRUE)
The only function that works is svygini

**Comment by ajdamico** [comment]
i think this is a different issue?  open up a new issue and try to solve it
there?  if you figure out this problem, i do not think the model.frame()
problem will be solved?

**Comment by DjalmaPessoa** [comment]
I included a comment inthe issue considering the pnad 2011 in the form of
data frame. It is the same, all wrong!
All functions, including the basic like densfun, icdf, iqalpha and isq have
to be fixed, because they are called in the other functions.

**Comment by ajdamico** [comment]
i think the issue with model.frame is that it is calling
stats:::model.frame.default instead of survey:::model.frame.survey.design
and something about that is not being subsetted.

i think that if you solve this issue that you've just now described, the
prior issue will not be solved -- which is why i believe they deserve
separate github issue #s  :)

**Comment by ajdamico** [comment]
no longer relevant

**Comment by DjalmaPessoa** [comment]
with:

install_github("djalmapessoa/convey", build_vignettes=TRUE)

everything was ok, but I got the warnings:

Warning:  S3 methods 'svyarpr.DBIsvydesign', 'svyarpt.DBIsvydesign',
'svyfgt.DBIsvydesign', 'svygini.DBIsvydesign', 'svygpg.DBIsvydesign',
'svypoormed.DBIsvydesign', 'svyqsr.DBIsvydesign', 'svyrmir.DBIsvydesign',
'svyrmpg.DBIsvydesign' were declared in the NAMESPACE but  not found
*** arch - x64
Warning: S3 methods 'svyarpr.DBIsvydesign',
'svyarpt.DBIsvydesign', 'svyfgt.DBIsvydesign', 'svygini.DBIsvydesign',
'svygpg.DBIsvydesign', 'svypoormed.DBIsvydesign', 'svyqsr.DBIsvydesign',
'svyrmir.DBIsvydesign', 'svyrmpg.DBIsvydesign' were declared in
the NAMESPACE  but  not found

**Comment by DjalmaPessoa** [comment]
when installing, please use

> library(devtools)
> install_github("djalmapessoa/convey", build_vignettes=TRUE)

**Comment by ajdamico** [comment]
that works, and looks great!
