### ISSUE TITLE
calling stats:::model.frame.default instead of survey:::model.frame.survey.design

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#30]
working with data frame

    pnad2011<- dbGetQuery( db , 'select v4618 , v4617 , pre_wgt , v4609 , v4720, v8005 from pnad2011' )
    
    pnad2011_des <- svydesign(
      id = ~v4618 ,
      strata = ~v4617 ,
      data = pnad2011 ,
      weights = ~pre_wgt ,
      nest = TRUE
      )
    
    pop.post<- data.frame(v4609= as.character(unique(pnad2011$v4609)), Freq= unique(pnad2011$v4609))
    
    pnad2011_des_pos <- postStratify(pnad2011_des, ~v4609, pop.post)
    
    pnad2011_des_pos_sub <- subset(pnad2011_des_pos, v4720!=0 & is.na(v4720)==FALSE & v8005>=15 )
    
    library(convey)
    pnad2011_des_pos_sub<-convey_prep(pnad2011_des_pos_sub)
    
    svypoormed(~as.numeric(v4720),pnad2011_des_pos_sub, na.rm=TRUE )
    
    svygini (~as.numeric(v4720),pnad2011_des_pos_sub, na.rm=TRUE)
    densfun (~as.numeric(v4720), pnad2011_des_pos_sub, 1000, fun = "F", na.rm=TRUE)

**Comment by ajdamico** [comment]
no, the prior problem is the stats:::model.frame.default problem..  i'm not
sure what this new one is..

**Comment by DjalmaPessoa** [comment]
Sorry, I messed things up.

**Comment by ajdamico** [comment]
it's no big deal, that's why we use github to track our progress :)  can
you close this issue and open a new one that accurately describes this
particular problem?  that way, we can work through solving it without
disrupting the previous model.frame-related issue
