### ISSUE TITLE
additional information in the svyfgt output

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#31]
Perhaps it would be useful to include the following information:
1. type of threshold: abs, relq, relm
2. value of threshold
3. Instead of fgt could be fgt0 or fgt1 or in general : paste0("fgt", g)

**Comment by ajdamico** [comment]
could they just be include the same way that most functions include both
coef and SE objects in the cvystat object?

**Comment by DjalmaPessoa** [comment]
To add the additional information, do I have to create a new class and a
new  print for this class?

**Comment by ajdamico** [comment]
i believe this is a duplicate of https://github.com/DjalmaPessoa/convey/issues/33 but reopen if you disagree :)
