### ISSUE TITLE
additional information in the functions output

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#33]
There are some useful information not yet contained in the output of the functions.
One possibility would to include additional attributes like for instance:
 svyarpr - threshold , quantile
svyarpt - quantile, order, percent
svypoormed - arpr
svyqsr - upper quantile, lower quantile, upper total, lower total
svyrmir - median of income of people older than 65, median of people younger than 65
svyrmpg - median poor
svyfgt - type of  poverty threshold, value of threshold

this is what recall for the moment.

**Comment by DjalmaPessoa** [comment]
I wonder what is the best way to do it?

**Comment by ajdamico** [comment]
remember that most of your functions return objects with class `cvystat` and remember you do have a `print.cvystat` method already written that formats things nicely.  that `print.cvystat` can check for specific attributes and print them if they are available and ignore them if they are not

for an example, see how `hasdeff` gets accessed inside of `survey:::print.svystat`

**Comment by ajdamico** [comment]
@DjalmaPessoa has this been solved by your edits to `print.cvystat`?  if so, you can close?

**Comment by DjalmaPessoa** [comment]
Yes, but I have to change the documentation for the functions.

**Comment by DjalmaPessoa** [comment]
> svyrmpg( ~eqincome , design = des_eusilc )
               rmpg         SE     thresh poor_median
eqincome 1.8929e-01 5.7640e-03 1.0859e+04      8803.7
> svyrmir( ~eqincome , design = des_eusilc , age = ~age , agelim = 65 )
               rmir         SE    med_old med_young
eqincome 9.3304e-01 2.0906e-03 1.7144e+04     18375
> svyqsr( ~eqincome , design = des_eusilc )
                qsr         SE upper_quant lower_quant  upper_tot  lower_tot
eqincome 3.9700e+00 4.2550e-02  2.5998e+04  1.2213e+04 5.7757e+10 1.4548e+10

in the documentation of these functions where should I explain the meaning of thresh, poor_median, med_old, med_young ....?

**Comment by ajdamico** [comment]
these should be documented in the @return line, like https://github.com/DjalmaPessoa/convey/blob/master/R/svyarpr.R#L14

**Comment by DjalmaPessoa** [comment]
Please check the change I just made in the function svyrmir. I could introduce this easily in all the other functions. Is it ok?

**Comment by ajdamico** [comment]
yes, this looks great!  be sure to also get the replicate-weighted functions when you modify everything :)
