### ISSUE TITLE
in order for sqlite & monetdblite to work with convey, this line needs to change

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#34]
https://github.com/DjalmaPessoa/convey/blob/master/R/all_funs.R#L225

rather than passing in an `object` you will need to pass in an `expression` that will then update the survey design.  remember all the trouble we had with `t=` expecting one length and `object` being a different length?  this is the root of the problem..

does it make sense to _eliminate_ `SE_lin2` and write the appropriate code directly into each of the main functions?  appropriate code means keeping everything within the data set, never creating an external `object` that is separated from the design

this might mean you need to use `bquote` and `model.matrix` more often (which is what lumley does) but i am not sure

**Comment by DjalmaPessoa** [comment]
In all the functions we deal with two things:

1. the value of an estimate;
2. a new variable that has to be build in order to estimate the variance of
the estimate in 1.

The variable in 2. is not in the `data` argument of the original design.

It is not clear how to include this new variable without using some form of
 updating either of the data frame or of the design.

In the library survey this new variable is not needed to compute the
variances.

**Comment by ajdamico** [comment]
right, i think you need to store the expression to create that column.  so
if the column were created with

`as.numeric( col1 == 1 & col2 == 4 )`

then you need to carry all of that information alongside the design somehow?

**Comment by DjalmaPessoa** [comment]
It is possible to avoid the function SE_lin2 just replacing

variance <- (SE_lin2(lin, design))^2

by

variance <- vcov(svytotal(lin, design))

where lin is the linearized variable

**Comment by ajdamico** [comment]
hi, that does not solve the issue because `variance` is a separate object
from `design` still.  you need to figure out a way not to create a separate
object `variance` -- you need to somehow store the variance information
directly in the design each time.  you might be able to do that by adding
another attribute (the way we added `full_design`) but when lumley does
this kind of thing, i believe he stores the expression to re-compute the
estimate..

**Comment by DjalmaPessoa** [comment]
this is not clear. Why the estimate itself is not a separate object from
the design?

**Comment by ajdamico** [comment]
might be easier to explain over skype...

you know how `transform` and `update` are equivalent?  you are essentially
doing this inside of `SE_lin2()`

    x <- 1:4
    y <- transform( mtcars , newcol = x )


where `x` actually has no relationship to `y` -- in order for
database-backed designs to work, `newcol` would need to be calculated off
of *only* other columns within `mtcars` and not from an external data set..

**Comment by DjalmaPessoa** [comment]
I understand the example, but not what would be *mtcars* in our case.

In our case, the new variable *lin* depends only on the *income* variable
defined by the formula and on the *weights*. If we could include both in
the data frame this would work.

**Comment by ajdamico** [comment]
`mtcars` is the original design and `y` is the design containing the new
information

**Comment by DjalmaPessoa** [comment]
Still don''t understand in

variance<- vcov(svytotal(lin, design)

design is the original design and does not contain the new information!

**Comment by ajdamico** [comment]
`variance` is a distinct object.  you need to somehow keep all necessary
information with `design`

    design <- some_set_of_functions( design )

**Comment by DjalmaPessoa** [comment]
as I uderstand the final goal is to compute:

1. an estimate;
2. the se of the estimate.

 it is not clear how to do that using only the information in design.

**Comment by ajdamico** [comment]
hi, try this:


    # i made some edits so reload
    devtools::install_github("djalmapessoa/convey")
    library(convey)
    debug(convey::svyarpt.survey.design)
    # then run the **full** examples script at
    # ?svyarpt
    # the very last line will break


Browse[2]>
debug: variance <- (SE_lin2(lin, full_design))^2
Browse[2]>
Error in sqliteSendQuery(con, statement, bind.data) :
  error in statement: no such column: object

if you can figure out a way to solve this, then we can get `convey` working
on database-backed designs!

**Comment by DjalmaPessoa** [comment]
Thank you.
I'm beginning to understand. A basic question:
In all the functions I used

incvar <- model.frame(formula, design$variables, na.action = na.pass)[[1]]

design$variables is not defined in this case. So how to recover incvar? Any
suggestion?

**Comment by ajdamico** [comment]
hi, `design$variables` is defined.  when you run `svyarpt( ~ eqIncome , design = dbd_eusilc )` to walk through the final line in the examples script on `?svyarpt`, note the debug should be ` debug(convey:::svyarpt.survey.design)` and not ` debug(convey::svyarpt.survey.design)`

**Comment by DjalmaPessoa** [comment]
It is better to start with simpler things:

incvar <- model.frame(~eqIncome, dbd_eusilc$variables, na.action =
na.pass)[[1]]
Error in eval(expr, envir, enclos) : object 'eqIncome' not found
????

**Comment by ajdamico** [comment]
that line works for me..make sure you have the latest version from github?

**Comment by DjalmaPessoa** [comment]
github??
I have:

# database-backed design

library(survey
library(convey)
library(vardpoor)
data(eulsilc)
require(RSQLite)
tfile <- tempfile()
conn <- dbConnect( SQLite() , tfile )
dbWriteTable( conn , 'eusilc' , eusilc )
dbd_eusilc <- svydesign(ids = ~rb030 , strata = ~db040 ,  weights = ~rb050
, data="eusilc", dbname=tfile, dbtype="SQLite")
dbd_eusilc <- convey_prep( dbd_eusilc )
incvar <- model.frame(~eqIncome, dbd_eusilc$variables,na.action =
na.pass)[[1]]

**Comment by ajdamico** [comment]
what you have definitely won't work.  `dbd_eusilc` is a DBIsvydesign object so the code in `convey:::svyarpt.DBIsvydesign` must run before you can try that.  you will have more success troubleshooting this if you run `svyarpt( ~eqIncome , dbd_eusilc )` after you set `debug(convey:::svyarpt.survey.design)`  ..call on skype if i can help more?

**Comment by DjalmaPessoa** [comment]
I made a commit fixing the functions svyiqalpha and svyisq. They are now
working with DBIsvydesign object.
Could you please suggest possible simplifications?

**Comment by ajdamico** [comment]
hi, i think your changes are quite good!  i am not sure how to improve them -- if you find yourself writing the same code over and over again as you edit each of the functions, then maybe make some smaller functions?  but it looks great!  and compatible with dbi-backed designs!

**Comment by DjalmaPessoa** [comment]
It is not so simple to implement the changes in some of the functions. I'm
having hard time to do it in the functions where the full_design is used.
This is so because it is needed to complete the lin vector with 0's. So
far, I don't know how to include this step in an expression. One idea might
be to use an indicator vector.

**Comment by DjalmaPessoa** [comment]
The solution used in svyarpt is much simpler. It works for designs of class
survey.design2. Peharps we need to write svyarpt.survey.design
and svyarpt.survey.design2???

**Comment by DjalmaPessoa** [comment]
In the function svyrmir we work with two formulas:

svyrmir( ~eqIncome , design = dbd_eusilc , age = ~age , agelim = 65 )

how to include the variables eqIncome  and age in design$variables in the
DBIsvydesign case.

If I use ~eqIncome+ age instead I'll have to change quite a lot the actual
program. Any suggestion ?

**Comment by ajdamico** [comment]
hi, copy the strategy inside of `survey:::svyratio.DBIsvydesign`

**Comment by DjalmaPessoa** [comment]
you rule!

**Comment by ajdamico** [comment]
haha lumley does

**Comment by DjalmaPessoa** [comment]
In the function svygpg we also have to work with two formula. I just mimic
what was done for svyrmir, which is working, and svygpg breaks.
I can't see what is wrong.  Would you please check.

**Comment by DjalmaPessoa** [comment]
fixed svygpg!

**Comment by DjalmaPessoa** [comment]
I believe all functions are now working with dbi-backed design.
The function SE_lin2 is not used anymore and can be deleted.

**Comment by ajdamico** [comment]
great!  could you delete SE_lin2 and re-oxygenize and close this issue?
thanks djalma
