### ISSUE TITLE
should this line #46 also mention svrepdesign objects?  or only survey.design objects?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#35]
https://github.com/DjalmaPessoa/convey/blob/master/R/all_funs.R#L46

i am not sure if it should look like line #96 in the same script?

https://github.com/DjalmaPessoa/convey/blob/master/R/all_funs.R#L94

**Comment by DjalmaPessoa** [comment]
The function densfun is only used with survey.design objects.
The function icdf was intended to be an auxiliary function to linearize
indicators and used only with survey.design.
I believe now all the commands in icdf are already inserted as needed  in
the functions *.survey.design

**Comment by ajdamico** [comment]
great!  if you think that it is correct then please close the issue..  i
was just checking  :)
