### ISSUE TITLE
add `income concentration examples.R` script to censo demografico

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#37]
showing simple usage of main `convey` functions

https://github.com/ajdamico/asdfree/tree/master/Censo%20Demografico

after you write the first draft, please change the assignee to me and i will clean up

**Comment by DjalmaPessoa** [comment]
I have to ask people from IBGE which income variable they use to compute
the gini and also the filters used.

**Comment by ajdamico** [comment]
consider a templating package for this http://stackoverflow.com/questions/37537863/most-efficient-technique-to-build-a-series-of-r-vignettes-with-one-for-each-exa?noredirect=1#comment62988349_37537863

**Comment by ajdamico** [comment]
these will be included in the book.  for example: https://ajdamico.github.io/asdfreebook/pesquisa-nacional-por-amostra-de-domicilios-pnad.html#pnad_convey
