### ISSUE TITLE
what should happen if NA values are passed into h_fun?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#4]
https://github.com/DjalmaPessoa/convey/blob/master/R/all_funs.R#L35

should h_fun include a  na.rm=`  parameter to deal with this possibility?

**Comment by DjalmaPessoa** [comment]
Probabily it is going to needed in all funtions. I've not thought about
that yet.

**Comment by DjalmaPessoa** [comment]
I've implement the NA treatment in all functions. For some are working ok for some needs some fixing.
Here is a test:

library(vardpoor)
data(eusilc)
dati = data.frame(1:nrow(eusilc), eusilc)
colnames(dati)[1] <- "IDd"
library(survey)
library(convey)
# create a design object
#des_eusilc <- svydesign(ids = ~db040, weights = ~rb050, data = eusilc)

set.seed(123)
nas<-sample(rownames(eusilc),100,replace=FALSE)
eusilc$eqIncome0<-eusilc$eqIncome

eusilc[nas, "eqIncome0"]<-NA


des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
des_eusilc_rep <- as.svrepdesign(des_eusilc, type = "bootstrap")

library(convey)
des_eusilc <- convey_prep(des_eusilc)
des_eusilc_rep<- convey_prep(des_eusilc_rep)

# tests
## icdf

icdf(~eqIncome,des_eusilc,10000)
icdf(~eqIncome0,des_eusilc,10000, na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=icdf, x=10000, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=icdf, x=10000, na.rm=TRUE, deff=FALSE )


## densfun
densfun(~eqIncome0,des_eusilc,10000,fun="F",na.rm=TRUE)
densfun(~eqIncome0,des_eusilc,10000,fun="F",na.rm=TRUE)

# iqalpha
iqalpha(~eqIncome,des_eusilc,.50, na.rm=TRUE)
iqalpha(~eqIncome0,des_eusilc,.50, na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=iqalpha, .50, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=iqalpha,.50, na.rm=TRUE, deff=FALSE )

# isq not working
isq(~eqIncome, design=des_eusilc, .20, compinc= FALSE, na.rm = TRUE)
isq(~eqIncome0, design=des_eusilc, .20, compinc= FALSE, na.rm = TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=isq, .20, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=isq, .20, na.rm=TRUE, deff=FALSE )

# svyarpr
svyarpr( ~eqIncome , design = des_eusilc , na.rm=TRUE)
svyarpr( ~eqIncome0 , design = des_eusilc , na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyarpr, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyarpr, na.rm=TRUE, deff=FALSE )

# svyarpt
svyarpt( ~eqIncome , design = des_eusilc , na.rm=TRUE)
svyarpt( ~eqIncome0 , design = des_eusilc , na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyarpt, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyarpt, na.rm=TRUE, deff=FALSE )

# svyfgt needs to be fixed
svyfgt( ~eqIncome , design = des_eusilc ,alpha=1, na.rm=TRUE)
svyfgt( ~eqIncome0 , design = des_eusilc , alpha=1,na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyfgt, alpha=1, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyfgt,alpha=1, na.rm=TRUE, deff=FALSE )

# svygini
svygini( ~eqIncome , design = des_eusilc , na.rm=TRUE)
svygini( ~eqIncome0 , design = des_eusilc ,na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svygini, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svygini, na.rm=TRUE, deff=FALSE )

###################################################################################################

# svypoormed not working
svypoormed( ~eqIncome , design = des_eusilc , na.rm=TRUE)
svypoormed( ~eqIncome0 , design = des_eusilc ,na.rm=TRUE)

# Error in UseMethod("SE_lin2", design) :
#  no applicable method for 'SE_lin2' applied to an object of class "c('survey.design2', 'survey.design')"



svyby(~eqIncome, by=~db040, design=des_eusilc,  FUN=svypoormed, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svypoormed, na.rm=TRUE, deff=FALSE )

# svyqsr
svyqsr( ~eqIncome , design = des_eusilc , na.rm=TRUE)
svyqsr( ~eqIncome0 , design = des_eusilc ,na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyqsr, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyqsr, na.rm=TRUE, deff=FALSE )

# svyrmir
svyrmir( ~eqIncome , design = des_eusilc , age = ~age, na.rm=TRUE)
svyrmir( ~eqIncome0 , design = des_eusilc ,age = ~age, na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyrmir,age = ~age, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyrmir,age = ~age, na.rm=TRUE, deff=FALSE )

# svyrmpg
svyrmpg( ~eqIncome , design = des_eusilc , na.rm=TRUE)
svyrmpg( ~eqIncome0 , design = des_eusilc , na.rm=TRUE)
svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyrmpg, na.rm=TRUE, deff=FALSE )
svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyrmpg, na.rm=TRUE, deff=FALSE )

**Comment by ajdamico** [comment]
excellent!

**Comment by DjalmaPessoa** [comment]
Not all working properly. I'll need some debug and fixing.

**Comment by ajdamico** [comment]
`isq` does need to be debugged, because it looks like you're sending the pre-subsetted vector to it..

>     isq(~eqIncome, design=des_eusilc, .20, compinc= FALSE, na.rm = TRUE)
         isq        SE
t 1.4548e+10 126027235
>     isq(~eqIncome0, design=des_eusilc, .20, compinc= FALSE, na.rm = TRUE)
Error in `[<-.data.frame`(`*tmp*`, , newnames[j], value = c(2445.03268582255,  : 
  replacement has 14827 rows, data has 14727
In addition: Warning message:
In incvec * ((incvec <= q_alpha)) + Fprime * iq :
  longer object length is not a multiple of shorter object length
>


but the other two examples that you say did not work do work for me?


	> svypoormed( ~eqIncome0 , design = des_eusilc)
	Error in approxfun(cum.w, xx[oo], method = method, f = f, yleft = min(xx),  : 
	  zero non-NA points
	> svypoormed( ~eqIncome0 , design = des_eusilc ,na.rm=TRUE)
			  poormed     SE
	eqIncome0    8791 73.176
	> svypoormed( ~eqIncome , design = des_eusilc ,na.rm=TRUE)
			 poormed    SE
	eqIncome  8803.7 72.88
	> svypoormed( ~eqIncome , design = des_eusilc ,na.rm=FALSE)
			 poormed    SE
	eqIncome  8803.7 72.88
	> 


	>     svyfgt( ~eqIncome , design = des_eusilc ,alpha=1, na.rm=TRUE)
				  fgt     SE
	eqIncome 0.039809 0.0011
	>     svyfgt( ~eqIncome0 , design = des_eusilc , alpha=1,na.rm=TRUE)
				   fgt     SE
	eqIncome0 0.039849 0.0011
	>     svyby(~eqIncome,by=~db040, design=des_eusilc, FUN=svyfgt, alpha=1, na.rm=TRUE, deff=FALSE )
						  db040     eqIncome se.eqIncome
	Burgenland       Burgenland -0.006811858 0.068235030
	Carinthia         Carinthia  0.038223877 0.030025786
	Lower Austria Lower Austria  0.042828628 0.009328204
	Salzburg           Salzburg  0.053534299 0.032108441
	Styria               Styria  0.036473549 0.013319523
	Tyrol                 Tyrol  0.028796213 0.023918660
	Upper Austria Upper Austria  0.066995258 0.010587129
	Vienna               Vienna  0.026348105 0.008992621
	Vorarlberg       Vorarlberg  0.027868821 0.046361493
	>     svyby(~eqIncome0,by=~db040, design=des_eusilc, FUN=svyfgt,alpha=1, na.rm=TRUE, deff=FALSE )
						  db040    eqIncome0 se.eqIncome0
	Burgenland       Burgenland -0.005010065  0.068753924
	Carinthia         Carinthia  0.042673170  0.030141067
	Lower Austria Lower Austria  0.042470034  0.009350316
	Salzburg           Salzburg  0.053428617  0.032223853
	Styria               Styria  0.036326880  0.013340670
	Tyrol                 Tyrol  0.028453915  0.023882623
	Upper Austria Upper Austria  0.066760522  0.010625423
	Vienna               Vienna  0.025463826  0.009029783
	Vorarlberg       Vorarlberg  0.028107179  0.046423000
	>

**Comment by DjalmaPessoa** [comment]
I didn't check for the svrep functions. I'll do it tomorrow. I'd like to talk to you on skype tomorrow. Bye now.

**Comment by DjalmaPessoa** [comment]
In order to make SE_lin2 work in the function svyarpt I had to
use SE_lin2.default instead. Do you know why? Do I have to use it in the
other functions?

**Comment by ajdamico** [comment]
i broke them apart because SE_lin2 needs to behave differently for
DBIsvydesign objects, but you should not need to type SE_lin2.default.  it
should be able to figure out which function to use

**Comment by DjalmaPessoa** [comment]
I also had to do the same thing for the function svyrmpg. It only worked
when I replaced SE_lin2 by convey:::SE_lin2.default. I'm going to make a
commit updating the functions. Could you please check this?

**Comment by ajdamico** [comment]
i just made a commit to fix that..  you can re-install and synch

but the examples in ?svyrmpg are not working because something is behaving
incorrectly with na.rm=TRUE

**Comment by DjalmaPessoa** [comment]
The functions svygpg has the sex and svyrmir has the age as extra
arguments. Perhaps the NA treatment has to be extended also to these
variables.

For svyrmir:

svyrmir( ~eqIncome , subset(des_eusilc,db040=="Tyrol") , age = ~age,
agelim=65, na.rm=TRUE)

works, but for

svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyrmir, age = ~age,
agelim=65, na.rm=TRUE, deff=FALSE )

I got:

Error in svyrmir.survey.design(data, design[byfactor %in% byfactor[i],  :
  unused argument (deff = deff).  Any suggestion?

**Comment by DjalmaPessoa** [comment]
still get

Error in UseMethod("SE_lin2", design) :
  no applicable method for 'SE_lin2' applied to an object of class
"c('survey.design2', 'survey.design')"

in svyarpt.

**Comment by ajdamico** [comment]
time to open up new issues  :)
