### ISSUE TITLE
any idea why `svygini` produces a lower coefficient than this document?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#40]
i have attached an R file that attempts to reproduce the gini coefficient with the survey of consumer finances but fails..    any idea?

http://inequality.stanford.edu/_media/pdf/pathways/special_sotu_2014/Pathways_SOTU_2014_Wealth_Inequality.pdf

[20160312 gini coefficient comparisons.txt](https://github.com/DjalmaPessoa/convey/files/170475/20160312.gini.coefficient.comparisons.txt)

**Comment by DjalmaPessoa** [comment]
Have to make sure that the right income variable to use is `networth`. Also it is important to check if some filter was used. Sometimes 0 income variables are discarded before computing the Gini.

**Comment by DjalmaPessoa** [comment]
# simple example of income broken out by age categories using `svygini`
scf.MIcombine( with( scf.design , svyby( ~income , ~agecl , svyarpt ) ) )

you're not using svygini?

**Comment by ajdamico** [comment]
e-mail subject line `gini coefficient calculation for wealth in 2010 SCF?`

**Comment by ajdamico** [comment]
we are matching the 0.846 in this document precisely.  i also confirmed that the script above matches the 2004 and 2007 SCF gini coefficients.

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4200506/table/T5/
