### ISSUE TITLE
DBIsvydesign subsets

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#43]
library(convey)
      options( monetdb.debug.query = TRUE )
      setwd( "C:\\Djalma\\PnadMonetdb\\PNAD" )
      pnad.dbfolder <- paste0( getwd() , "/MonetDB" )
      db <- dbConnect( MonetDBLite() , pnad.dbfolder )
      dbListTables(db)
      
      options(survey.lonely.psu = "adjust")
      
      source_url( "https://raw.githubusercontent.com/ajdamico/asdfree/master/Pesquisa%20Nacional%20por%20Amostra%20de%20Domicilios/pnad.survey.R" , prompt = FALSE )
      
      sample.pnad <-
        svydesign(
          id = ~v4618 ,
          strata = ~v4617 ,
          data = 'pnad2011' ,
          weights = ~pre_wgt ,
          nest = TRUE ,
          dbtype = "MonetDBLite" ,
          dbname = pnad.dbfolder
        )
      
      y <-
        pnad.postStratify(
          design = sample.pnad ,
          strata.col = 'v4609' ,
          oldwgt = 'pre_wgt'
        )
      
      y.sub <- subset (y,  !is.na(v4720) & v4720!=0 & v8005>=15)

dim(y)

dim(y.sub)

Now check:

dim.des <-function (formula, design, na.rm = FALSE, ...) 
    {
      incvar <- model.frame(formula, design$variables, na.action = na.pass)[[1]]
      w <- 1/design$prob
      ncom <- names(w)
      if (na.rm) {
        nas <- is.na(incvar)
        design <- design[!nas, ]
        incvar <- incvar[!nas]
        w <- w[!nas]
      }
      
     list(dim(design), length(incvar))
      
    }

dim.des(~ v4720,y.sub, na.rm=TRUE)

**Comment by ajdamico** [comment]
hi djalma, you can get the appropriate records with

    1 / design$prob > 0

so this length gives you the same records as `dim(design)`

    length( x[ 1 / design$prob > 0 , ] )

i think your strategy should follow what happens inside this function..  it is a bit complicated, but i think it should work

	debug(survey:::svymean.survey.design2)

run this command

	svymean(~ v4720,y.sub, na.rm=TRUE)

especially watch what happens when these lines runs..

    pweights <- 1/design$prob
    psum <- sum(pweights)
    average <- colSums(x * pweights/psum)
    x <- sweep(x, 2, average)

during the debug, you can see that the design _does_ have the full data set

    length( design$prob )
    [1] 358919

..but at any point, you can isolate down to the appropriate subset with this..

    table(pweights==0,useNA='always')

     FALSE   TRUE   <NA> 
    201741 157178      0 


hope this is helpful?  :)

**Comment by ajdamico** [comment]
@DjalmaPessoa are you sure this is working exactly how you want it to?  i did not expect you to finalize it before 0.1.0 but thought was still incomplete?  but if you think the current behavior is correct, great!

**Comment by ajdamico** [comment]
@DjalmaPessoa i will add these tests after CRAN submission to confirm--

https://github.com/DjalmaPessoa/convey/issues/99

**Comment by guilhermejacob** [comment]
I think that the different behavior happens during `getvars` or something like.
When running a function over a DBI-backed design, we're usually dealing with a large dataset. Passing unnecessary observations increases the volume of data.
Besides, it creates problems when writing the functions, as you have to deal with `1/design$prob == 0` and length checking every now and then.

I'll explore this on another branch, ok?

**Comment by ajdamico** [comment]
hi, do you have a use case where this makes a big difference?  if it's unnecessarily keeping more rows in memory than necessary but it doesn't break, i'm not sure whether it's worth your time trying to improve?  most large datasets don't have much missingness in their weight+cluster+strata variables (the non-missing records are read into memory, even for db-backed designs), so i doubt this will be the tipping point for many users?
