### ISSUE TITLE
database-backed design examples in convey could use MonetDBLite instead of RSQLite?

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#44]
just replacing does not work:

 # database-backed design
#' require(MonetDBLite)
#' tfile <- tempfile()
#' conn <- dbConnect( MonetDBLite() , tfile )
#' dbWriteTable( conn , 'eusilc' , eusilc )
#'
#' dbd_eusilc <- svydesign(ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data="eusilc", dbname=tfile, dbtype="MonetDBLite")
#'
#' dbd_eusilc <- convey_prep( dbd_eusilc )
#' svyrmpg( ~ eqIncome , design = dbd_eusilc )

**Comment by ajdamico** [comment]
look at my examples again?  you need DBI and MonetDB.R loaded..

**Comment by DjalmaPessoa** [comment]
changing as you suggested, I got the error: 

# database-backed design
#' require (DBI)
#' require(MonetDB.R)
#' require(MonetDBLite)
#' tfile <- tempfile()
#' conn <- dbConnect( MonetDBLite() , tfile )
#' dbWriteTable( conn , 'eusilc' , eusilc )


Identifier(s) "eqSS", "eqIncome" contain uppercase or reserved SQL characters and need(s) to be quoted in queries.
[1] TRUE



#' dbd_eusilc <- svydesign(ids = ~rb030 , strata = ~db040 , weights = ~rb050 , data="eusilc", dbname=tfile, dbtype="MonetDBLite")
#'
#' dbd_eusilc <- convey_prep( dbd_eusilc )
#' svyrmpg( ~ eqIncome , design = dbd_eusilc )

Error in .local(conn, statement, ...) : 
  Unable to execute statement 'select eqIncome from eusilc'.
Server says 'ParseException:SQLparser:SELECT: identifier 'eqincome' unknown'.
In addition: Warning message:
'isIdCurrent' is deprecated.
Use 'dbIsValid' instead.
See help("Deprecated")

**Comment by ajdamico** [comment]
coerce all variables to lowercase before you store them in monetdb.  use `names( eusilc ) <- tolower( names( eusilc ) )` before you run the `dbWriteTable`  :)

**Comment by DjalmaPessoa** [comment]
I used the last cran version and got:

> svypoormed(~v4720, y.sub,na.rm=TRUE)
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'select * from pnad2011 limit 1'.
Server says 'integer value too large or not a number (1) in: "select * from pnad2011 limit 1"
' [#22003].
In addition: There were 26 warnings (use warnings() to see them)

I thought this had been solved

**Comment by ajdamico** [comment]
see email for instructions to install the development version  :)
