### ISSUE TITLE
do we want to stick with `oldsvyquantile` for the foreseeable future?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#445]
it would be great if you could just glance at the list of places that we use `oldsvyquantile` and double-check whether it makes sense to keep using the deprecated version of the function?

https://github.com/ajdamico/convey/commit/5592eb7a28e00f39fb7fc489139fd25949dc1ae9

i doubt it matters much, but may be worth a quick look?

**Comment by guilhermejacob** [comment]
I would stick with that for now. Unless you can set up the exact same estimator in `oldsvyquantile` using the new `svyquantile`, that would mean changing estimators, which would likely require  other variance estimator(s).

**Comment by guilhermejacob** [comment]
Let's look at the estimators. As far as I know, `svyoldquantile` estimates the quantile using a linear interpolation on the CDF; the new `svyquantile` has a `qrule` parameter that implements several different estimators. The new ones might work just fine, but we would need some to (at least) run some simulations before making that change; that is why I suggest keeping it for now.

In fact, Langel & Tillé (2011) use another estimator, based on the 4th definition of Hyndman and Fan (1996), and another variance estimator -- that, unlike ours, does not rely on density estimation. I don't know if it matches Lumley's implementation of the H&F estimator; it might not.

Additionally, we need to make sure we can replicate results in `vardpoor`. As far as I know, its estimator is not the one in old `oldsvyquantile`, as it does not rely on that linear interpolation.
