### ISSUE TITLE
please add `svylorenz` and `svyatk` examples to testthat folder

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#47]
hi, you should be able to copy over what djalma has already done for the other functions pretty easily..  thanks!

https://github.com/DjalmaPessoa/convey/tree/master/tests/testthat

**Comment by ajdamico** [comment]
@guilhermejacob hi, did this commit solve the issue?  if so, please "close" it on github  :)  thanks again guilherme  https://github.com/DjalmaPessoa/convey/commit/bd410a260ac9e3e77ad9f2b81f3e4e7099e3e4ae

**Comment by guilhermejacob** [comment]
Solved. But it doesn't have a SE comparison.
