### ISSUE TITLE
check if the confidence levels for svylorenz should be alpha/2

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#49]

**Comment by guilhermejacob** [comment]
Checked. It is correct. Included 'add' and 'curve.col' parameters to compare different curves.

**Comment by ajdamico** [comment]
awesome, thanks!  don't forget to include the git commit link(s) when you close the issue so we can review..  https://github.com/DjalmaPessoa/convey/commit/791330c17dfaddb5c91907743d46b4f7cad2c53a
