### ISSUE TITLE
main user functions probably need an `na.rm=` argument

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#5]
it looks like the user-level functions  `svy*` should have the `na.rm=` parameter (default to FALSE like the survey package) and then that na.rm= parameter should get passed to the lower-level functions.

you can see how the `na.rm` object gets used in
survey:::svymean.survey.design

**Comment by ajdamico** [comment]
i have added the parameter to the functions & documentation, but it does not work yet.. you'll have to look closer at how you want to implement it :)

https://github.com/DjalmaPessoa/convey/commit/2365e9e2e8ee2430c2c858ad0717448447a93213

**Comment by DjalmaPessoa** [comment]
Included tests for svrep.design. They are all working!
library(vardpoor)
      data(eusilc)
      dati = data.frame(1:nrow(eusilc), eusilc)
      colnames(dati)[1] <- "IDd"
      library(survey)
      library(convey)
      # create a design object
      #des_eusilc <- svydesign(ids = ~db040, weights = ~rb050, data = eusilc)
      
      set.seed(123)
      nas<-sample(rownames(eusilc),100,replace=FALSE)
      eusilc$eqIncome0<-eusilc$eqIncome
      
      eusilc[nas, "eqIncome0"]<-NA
      
      
      des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
      des_eusilc_rep <- as.svrepdesign(des_eusilc, type = "bootstrap")
      
      library(convey)
      des_eusilc <- convey_prep(des_eusilc)
      des_eusilc_rep<- convey_prep(des_eusilc_rep)
      
      # tests
      ## icdf
      
      icdf(~eqIncome,des_eusilc,10000)
      icdf(~eqIncome0,des_eusilc,10000, na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=icdf, x=10000, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=icdf, x=10000, na.rm=TRUE, deff=FALSE )
      
      
      
      
      
      ## densfun
      densfun(~eqIncome0,des_eusilc,10000,fun="F",na.rm=TRUE)
      densfun(~eqIncome0,des_eusilc,10000,fun="F",na.rm=TRUE)
      
      # iqalpha
      iqalpha(~eqIncome,des_eusilc,.50, na.rm=TRUE)
      iqalpha(~eqIncome0,des_eusilc,.50, na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=iqalpha, .50, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=iqalpha,.50, na.rm=TRUE, deff=FALSE )
      
      # isq
      isq(~eqIncome, design=des_eusilc, .20, compinc= FALSE, na.rm = TRUE)
      isq(~eqIncome0, design=des_eusilc, .20, compinc= FALSE, na.rm = TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=isq, .20, compinc=FALSE, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=isq, .20, compinc= FALSE,na.rm=TRUE, deff=FALSE )
      
      # svyarpr
      svyarpr( ~eqIncome , design = des_eusilc , na.rm=TRUE)
      svyarpr( ~eqIncome0 , design = des_eusilc , na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyarpr, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyarpr, na.rm=TRUE, deff=FALSE )
      
      
      # svrep
      svyarpr( ~eqIncome , design = des_eusilc_rep , na.rm=TRUE)
      svyarpr( ~eqIncome0 , design = des_eusilc_rep , na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc_rep,  FUN=svyarpr, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc_rep,  FUN=svyarpr, na.rm=TRUE, deff=FALSE )
      
      
      
      
      # svyarpt
      svyarpt( ~eqIncome , design = des_eusilc , na.rm=TRUE)
      svyarpt( ~eqIncome0 , design = des_eusilc , na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyarpt, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyarpt, na.rm=TRUE, deff=FALSE )
      
      svyarpt( ~eqIncome , design = des_eusilc_rep , na.rm=TRUE)
      svyarpt( ~eqIncome0 , design = des_eusilc_rep , na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc_rep,  FUN=svyarpt, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc_rep,  FUN=svyarpt, na.rm=TRUE, deff=FALSE )
      
      
      
      
      
      
      
      # svyfgt depois de consertar
      svyfgt( ~eqIncome , design = des_eusilc ,alpha=1, na.rm=TRUE)
      svyfgt( ~eqIncome0 , design = des_eusilc , alpha=1,na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyfgt, alpha=1, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyfgt,alpha=1, na.rm=TRUE, deff=FALSE )
      
      
      
      # svygini
      svygini( ~eqIncome , design = des_eusilc , na.rm=TRUE)
      svygini( ~eqIncome0 , design = des_eusilc ,na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svygini, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svygini, na.rm=TRUE, deff=FALSE )
      
      # svrep
      svygini( ~eqIncome , design = des_eusilc_rep , na.rm=TRUE)
      svygini( ~eqIncome0 , design = des_eusilc_rep ,na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc_rep,  FUN=svygini, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc_rep,  FUN=svygini, na.rm=TRUE, deff=FALSE )
      
      
      ###################################################################################################
      
      # svypoormed not working
      svypoormed( ~eqIncome , design = des_eusilc , na.rm=TRUE)
      svypoormed( ~eqIncome0 , design = des_eusilc ,na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svypoormed, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svypoormed, na.rm=TRUE, deff=FALSE )
      
      # svrep
      
      svypoormed( ~eqIncome , design = des_eusilc_rep , na.rm=TRUE)
      svypoormed( ~eqIncome0 , design = des_eusilc_rep ,na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc_rep,  FUN=svypoormed, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc_rep,  FUN=svypoormed, na.rm=TRUE, deff=FALSE )
      
      
      
      
      # svyqsr
      svyqsr( ~eqIncome , design = des_eusilc , na.rm=TRUE)
      svyqsr( ~eqIncome0 , design = des_eusilc ,na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyqsr, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyqsr, na.rm=TRUE, deff=FALSE )
      #svrep
      svyqsr( ~eqIncome , design = des_eusilc_rep , na.rm=TRUE)
      svyqsr( ~eqIncome0 , design = des_eusilc_rep ,na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc_rep,  FUN=svyqsr, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc_rep,  FUN=svyqsr, na.rm=TRUE, deff=FALSE )
      
      
      
      # svyrmir
      svyrmir( ~eqIncome , design = des_eusilc , age = ~age, agelim=65, na.rm=TRUE)
      svyrmir( ~eqIncome0 , design = des_eusilc ,age = ~age, agelim=65, na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyrmir, age = ~age, agelim=65, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyrmir, age = ~age, agelim=65, na.rm=TRUE, deff=FALSE )
      
      #svrep
      svyrmir( ~eqIncome , design = des_eusilc_rep , age = ~age, agelim=65, na.rm=TRUE)
      svyrmir( ~eqIncome0 , design = des_eusilc_rep ,age = ~age, agelim=65, na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc_rep,  FUN=svyrmir, age = ~age, agelim=65, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc_rep,  FUN=svyrmir, age = ~age, agelim=65, na.rm=TRUE, deff=FALSE )
      
      
      # svyrmpg
      svyrmpg( ~eqIncome , design = des_eusilc , na.rm=TRUE)
      svyrmpg( ~eqIncome0 , design = des_eusilc , na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc,  FUN=svyrmpg, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc,  FUN=svyrmpg, na.rm=TRUE, deff=FALSE )
      
      # svrep
      svyrmpg( ~eqIncome , design = des_eusilc_rep , na.rm=TRUE)
      svyrmpg( ~eqIncome0 , design = des_eusilc_rep , na.rm=TRUE)
      svyby(~eqIncome,by=~db040, design=des_eusilc_rep,  FUN=svyrmpg, na.rm=TRUE, deff=FALSE )
      svyby(~eqIncome0,by=~db040, design=des_eusilc_rep,  FUN=svyrmpg, na.rm=TRUE, deff=FALSE )
      
      ## svygpg
      
      
      data(ses)
      
      set.seed(123)
      nas<-sample(rownames(ses),100,replace=FALSE)
      
      ses$earningsHour0<-ses$earningsHour
      
      ses[nas, "earningsHour0"]<-NA
      
      des_ses<- svydesign(id=~1, weights=~weights, data=ses,
        variables=~weights+sex+earningsHour+earningsHour0+ education)
      des_ses<- convey_prep(des_ses)
      
      des_ses_rep<- as.svrepdesign(des_ses, type="bootstrap")
      
      des_ses_rep<- convey_prep(des_ses_rep)
      
      svygpg(~earningsHour, des_ses, ~sex, na.rm=TRUE)
      svygpg(~earningsHour0, des_ses, ~sex, na.rm=TRUE)
      svyby(~earningsHour, by=~education, des_ses, FUN=svygpg, sex=~sex, na.rm=TRUE)
      svyby(~earningsHour0, by=~education, des_ses, FUN=svygpg, sex=~sex, na.rm=TRUE)
      
      # svrep
      svygpg(~earningsHour, des_ses_rep, ~sex, na.rm=TRUE)
      svygpg(~earningsHour0, des_ses_rep, ~sex, na.rm=TRUE)
      svyby(~earningsHour, by=~education, des_ses_rep, FUN=svygpg, sex=~sex, na.rm=TRUE)
      svyby(~earningsHour0, by=~education, des_ses_rep, FUN=svygpg, sex=~sex, na.rm=TRUE)

**Comment by ajdamico** [comment]
awesome!  could this issue be closed then?
