### ISSUE TITLE
svyrmir outputting zeroes 

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#52]
using the example code from ?svyrmir

	library(survey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	# linearized design
	des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )

	svyrmir( ~eqincome , design = des_eusilc , age = ~age , agelim = 65 , med_old = TRUE )

	# replicate-weighted design
	des_eusilc_rep <- survey:::as.svrepdesign( des_eusilc , type = "bootstrap" )
	svyrmir( ~eqincome , design = des_eusilc_rep, age= ~age, agelim = 65, med_old = TRUE )

	# linearized design using a variable with missings
	svyrmir( ~ py010n , design = des_eusilc,age= ~age, agelim = 65)
	svyrmir( ~ py010n , design = des_eusilc , age= ~age, agelim = 65, na.rm = TRUE )
	# replicate-weighted design using a variable with missings
	svyrmir( ~ py010n , design = des_eusilc_rep,age= ~age, agelim = 65 )
	svyrmir( ~ py010n , design = des_eusilc_rep ,age= ~age, agelim = 65, na.rm = TRUE )

are these zeroes expected?

> svyrmir( ~ py010n , design = des_eusilc , age= ~age, agelim = 65, na.rm = TRUE )
> 	   rmir     SE
> py010n    0 0.0013

> svyrmir( ~ py010n , design = des_eusilc_rep ,age= ~age, agelim = 65, na.rm = TRUE )
> 	   rmir SE
> py010n    0  0

**Comment by DjalmaPessoa** [comment]
with the new arguments it is possible to see that the numerator of the ratio is 0:

> svyrmir( ~ py010n , design = des_eusilc , age= ~age, agelim = 65, na.rm = TRUE, med_old=TRUE, med_young=TRUE )

            rmir        SE   med_old med_young
py010n 0.0000000 0.0013371 0.0000000    9266.6

so the ratio is 0.0000000/ 9266.6 = 0

**Comment by ajdamico** [comment]
then it's a bad example, right?  users will be confused.  could you use a different variable?  thanks

**Comment by DjalmaPessoa** [comment]
The definition of the variable is

"py010n
numeric; employee cash or near cash income (net)."

So that apparently older people don't earn it, because are retired.

No,  it is not a bad example!  It only shows that there a "mass point at zero", very common for incomes, depending upon the type. At IBGE we are very used to it.
