### ISSUE TITLE
change the variable py010n in the svyrmir example 

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#53]
If the goal is only to show the NA treatment, we could create a new variable inserting NA values in the variable eqincome:

indNA<- rbinom(nrow(eusilc),1, .10) 
eusilc$eqincome.miss <- eusilc$iqincome
eusilc$eqincome.miss[indNA==1] <- NA
 
and use the variable eqincome.miss instead of py010n in the svyrmir example?

**Comment by ajdamico** [comment]
you should do whatever you think will make the most sense for users..  i had thought the it looked weird to have a zero in the output, but if you think that's often expected, then i'm ok too

**Comment by DjalmaPessoa** [comment]
the example was changed!
