### ISSUE TITLE
tests for the library convey are not working

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#54]
It will be needed to revise all tests. Most of them used the function SE_lin2 which was deleted from convey

**Comment by DjalmaPessoa** [comment]
I just fixed most of them. I believe the only breaking is svyrmpg. I'm working to fix it

**Comment by DjalmaPessoa** [comment]
Please run:
testthat::test_example("C:/Users/owner/Documents/GitHub/convey/man/svygei.Rd")

and check the error message

**Comment by guilhermejacob** [comment]
Fixed. Bad example.
