### ISSUE TITLE
Missing value treatment not working for svrepdesign 

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#60]
When runing svyarpr example for missing values treatment we get:
library(survey)
library(vardpoor)
data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
des_eusilc <- convey_prep( des_eusilc )

svyarpr( ~eqincome , design = des_eusilc )

 # replicate-weighted design
des_eusilc_rep <- survey:::as.svrepdesign( des_eusilc , type = "bootstrap" )
des_eusilc_rep <- convey_prep( des_eusilc_rep )

svyarpr( ~ py010n , design = des_eusilc_rep )

Error in survey:::svrVar(qq, design$scale, design$rscales, mse = design$mse,  : 
  All replicates contained NAs

I thought we had fixed this before.

**Comment by DjalmaPessoa** [comment]
I just made I commit fixing the problem. Please see if you agree. If so, I'll introduce it in all functions

**Comment by ajdamico** [comment]
your fix for `svyarpr.svyrep.design` looks good!

please be more specific when you title your commits  ;)  "fix bugs" is not descriptive enough
