### ISSUE TITLE
svyatk produces error for eaxmple with missing values

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#61]
Error: Test failed: 'C:/Users/owner/Documents/GitHub/convey/man/svyatk.Rd'
* NA/NaN/Inf in foreign function call (arg 1)
1: svyatk(~py010n, design = des_eusilc_rep, epsilon = 0.5) at C:\Users\owner\AppData\Local\Temp\RtmpKyeZxx/svyatk.R:26
2: svyatk.svyrep.design(~py010n, design = des_eusilc_rep, epsilon = 0.5)
3: design[nps == 0]
4: `[.svyrep.design`(design, nps == 0)
5: degf(x)
6: degf.svyrep.design(x)
7: qr(weights(design, "analysis"), tol = 1e-05)
8: qr.default(weights(design, "analysis"), tol = 1e-05)

**Comment by DjalmaPessoa** [comment]
To check the errors in the examples, please run

library(testthat)
test_examples("C:/Users/owner/Documents/GitHub/convey/man")

**Comment by guilhermejacob** [comment]
Fixed it.

**Comment by ajdamico** [comment]
thanks guilherme!
