### ISSUE TITLE
fix missing values treatment for svypoormed

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#62]
I just fixed the missing value treatment for svypoormed, and noticed that

> svypoormed.survey.design( ~ py010n , design = des_eusilc, na.rm=TRUE)
       poormed     SE
py010n       0 11.166

should I change the example as in svyrmir???

**Comment by ajdamico** [comment]
@DjalmaPessoa i do think it's weird to show a `0` outputted result in the examples, but you have more familiarity with these statistics than i do so i think it's your choice.  cc @guilhermejacob
