### ISSUE TITLE
NAs should not be treated differently in db-backed designs

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#64]
@guilhermejacob could you give a minimal reproducible example of this?  you mentioned at https://github.com/DjalmaPessoa/convey/issues/63  thanks

**Comment by guilhermejacob** [comment]
The NAs work differently. Take a look:
```
library(survey)
library(vardpoor)
data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

# linearized design
des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
library(convey)
des_eusilc <- convey_prep(des_eusilc)
des_eusilc_rep <- survey:::as.svrepdesign( des_eusilc , type = "bootstrap" )
des_eusilc_rep <- convey_prep(des_eusilc_rep)

require(RSQLite)
tfile <- tempfile()
conn <- dbConnect( SQLite() , tfile )
dbWriteTable( conn , 'eusilc' , eusilc )

dbd_eusilc <- svydesign(ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data="eusilc", dbname=tfile, dbtype="SQLite")
dbd_eusilc <- convey_prep( dbd_eusilc )

svygei( ~py010n , design = subset( des_eusilc, py010n > 0 ), epsilon = 1, na.rm = FALSE )
svygei( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), epsilon = 1, na.rm = FALSE )
svygei( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), epsilon = 1, na.rm = TRUE )
```

**Comment by DjalmaPessoa** [comment]
Consider
> des_eusilc_posit <-subset( des_eusilc, py010n > 0 )
> sum(is.na(des_eusilc_posit$variables$py010n))
[1] 0

so the condition py010n > 0 discards all NA values from the variable py010n
in the subset design. The reason is the NA values of py010n > 0 are
considered in des_eusilc_posit

**Comment by guilhermejacob** [comment]
the database-backed one behaves differently: it keeps the NAs. What do you suggest? It's not a major issue, but it would be better if the results are consistent.

**Comment by DjalmaPessoa** [comment]
Yes, I noticed the same problems with other functions:

svyarpr( ~py010n , design = subset( des_eusilc, py010n > 0 ),  na.rm = FALSE )
svyarpr( ~py010n , design = subset( des_eusilc_rep, py010n > 0 ),  na.rm = FALSE )
svyarpr( ~py010n , design = subset( dbd_eusilc, py010n > 0 ),  na.rm = TRUE )

**Comment by ajdamico** [comment]
@guilhermejacob responding to your example: i don't see the difference?  that variable does not have any missings.  and `svymean` behaves the same way?

	svygei( ~py010n , design = subset( des_eusilc, py010n > 0 ), epsilon = 1, na.rm = FALSE )
	svygei( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), epsilon = 1, na.rm = TRUE )

	svygei( ~py010n , design = subset( des_eusilc, py010n > 0 ), epsilon = 1, na.rm = FALSE )
	svygei( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), epsilon = 1, na.rm = TRUE )

	svymean( ~py010n , design = subset( des_eusilc, py010n > 0 ), epsilon = 1, na.rm = FALSE )
	svymean( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), epsilon = 1, na.rm = TRUE )

	svymean( ~py010n , design = subset( des_eusilc, py010n > 0 ), epsilon = 1, na.rm = FALSE )
	svymean( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), epsilon = 1, na.rm = TRUE )

**Comment by ajdamico** [comment]
@DjalmaPessoa i don't understand the problem with the lines of code you've presented?  these results seem appropriate

	svyarpr( ~py010n , design = subset( des_eusilc, py010n > 0 ), na.rm = FALSE )
	svyarpr( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), na.rm = TRUE )

	svyarpr( ~py010n , design = subset( des_eusilc_rep, py010n > 0 ), na.rm = FALSE )
	svyarpr( ~py010n , design = subset( des_eusilc_rep, py010n > 0 ), na.rm = TRUE )

	svyarpr( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), na.rm = FALSE )
	svyarpr( ~py010n , design = subset( dbd_eusilc, py010n > 0 ), na.rm = TRUE )

**Comment by guilhermejacob** [comment]
Guess I solved this issue on svygei and svyatk by only performing calculations on observations with `weights != 0`. This condition ensures that the variables are used the same way across df and dbd backed designs.
I'll close this, but I'll update it if a better solution comes up.
