### ISSUE TITLE
does svyzenga compute statistics correctly?

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#66]
First, I need someone else to check if it's correct. I suggest this thesis: https://doc.rero.ch/record/29204/files/00002252.pdf.

Second, it takes too long on linearized samples. How can we improve its performance?

**Comment by ajdamico** [comment]
@DjalmaPessoa could you check guilherme's `svyzenga` function against the thesis link he provides?

ignore the performance improvement-- i have opened a separate issue (assigned to me) for that.  thanks

**Comment by ajdamico** [comment]
i believe there's some mistake.  here's a minimal reproducible example

	library(convey)
	library(vardpoor)
	library(survey)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )

	des_eusilc <- svydesign(ids = ~rb030, strata =~db040,  weights = ~rb050, data = eusilc)
	des_eusilc <- convey_prep(des_eusilc)

	a2 <- svyby(~eqincome, by = ~hsize, design = des_eusilc, FUN = svyzenga )

	options( scipen = 20 )

	# impossibly huge standard errors
	print( a2 )

	  # hsize   eqincome      se.eqincome
	# 1     1 0.61887033      0.032892063
	# 2     2 0.61906599      0.009976691
	# 3     3 0.58707925     15.499877089
	# 4     4 0.54745658      1.171675530
	# 5     5 0.53257826      7.803869927
	# 6     6 0.55111988    757.867215740
	# 7     7 0.50954836  10701.162401761
	# 8     8 0.28952194  26850.241336949
	# 9     9 0.07615316 449410.034040829

**Comment by DjalmaPessoa** [comment]
I believe the problem is the variable hsize. It doesn't make any sense to estimate things in such small domains!

**Comment by ajdamico** [comment]
well, only 8 and 9 have small Ns.  `hsize==3` has an N of `3147` and an absurd relative standard error of `2640%`

	table(eusilc$hsize)

	   1    2    3    4    5    6    7    8    9 
	1745 3624 3147 3508 1815  630  252   88   18

**Comment by ajdamico** [comment]
hi, here are two more examples with extreme standard errors..

	table(eusilc$db040)
	# Burgenland     Carinthia Lower Austria      Salzburg        Styria         Tyrol Upper Austria        Vienna    Vorarlberg 
	# 549          1078          2804           924          2295          1317          2805          2322           733 

	table(eusilc$pb220a)

	# AT    EU Other 
	# 11073   283   751 

	svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyzenga )
	# db040  eqincome  se.eqincome
	# Burgenland       Burgenland 0.6561318   0.42404430
	# Carinthia         Carinthia 0.5628407 113.97704457
	# Lower Austria Lower Austria 0.5825118   0.09252350
	# Salzburg           Salzburg 0.5770567   3.36263738
	# Styria               Styria 0.5495887   0.01649991
	# Tyrol                 Tyrol 0.5679019   0.28868959
	# Upper Austria Upper Austria 0.5753743   0.78697170
	# Vienna               Vienna 0.6277007   0.01945683
	# Vorarlberg       Vorarlberg 0.6192419 165.01871330
	# Warning message:
	# In svyzenga.survey.design(data, design[byfactor %in% byfactor[i],  :
	# The function is defined for strictly positive incomes only.


	svyby(~eqincome, by = ~pb220a, design = des_eusilc, FUN = svyzenga )
	# pb220a  eqincome  se.eqincome
	# AT        AT 0.5872891  0.003728843
	# EU        EU 0.6427791 69.879462717
	# Other  Other 0.5957618  0.108868599
	# Warning messages:
	# 1: In svyzenga.survey.design(data, design[byfactor %in% byfactor[i],  :
	# The function is defined for strictly positive incomes only.
	# 2: In svyzenga.survey.design(data, design[byfactor %in% byfactor[i],  :
	# The function is defined for strictly positive incomes only.

**Comment by DjalmaPessoa** [comment]
Just compare:
cv(svyby(~eqincome, by = ~db040, design = des_eusilc, FUN = svyzenga )) 

and

cv(svyby(~eqincome, by = ~db040, design = des_eusilc_rep, FUN = svyzenga ))

the cvs for the des_eusilc_rep seem to be reasonable

**Comment by ajdamico** [comment]
agreed..the issue might solely be with the linearized design variance calculation

**Comment by DjalmaPessoa** [comment]
the approach to lnearization of zenga is not based upon influence functions like most funtions in convey.
It would be nice to have some benchmarking.

**Comment by ajdamico** [comment]
@DjalmaPessoa https://github.com/DjalmaPessoa/convey/commit/41cffc786696da41b4d0534953aa61838fac6cd4

**Comment by guilhermejacob** [comment]
Zenga's variance is much closer to the replicate version. I'll close this but feel free to open if you disagree.
