### ISSUE TITLE
svycv function should not exist because `survey::cv` already contains those methods

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#68]
hi guilherme, i believe that the function introduced in this commit is not correctly implemented.
https://github.com/DjalmaPessoa/convey/compare/67f08c9c31...324f03a4be

the expected technique to access the coefficient of variation should be something like this, i think?

    cv( svymean(~eqincome, des_eusilc, squared = TRUE, na.rm = FALSE ) )

are there other uses of `svycv` that cannot be accessed using `survey::cv`?

in most cases, the coefficient of variation should be accessed from the `cvystat` object using this method:

	> survey:::cv.default
	function (object, warn = TRUE, ...) 
	{
		rval <- SE(object)/coef(object)
		if (warn && any(coef(object) < 0, na.rm = TRUE)) 
			warning("CV may not be useful for negative statistics")
		rval
	}
	<environment: namespace:survey>

however, if you need a special case for certain object classes, then you should follow the technique used by thomas lumley where certain classes have their own specific method (like `svyratio` below)

	> survey:::cv.svyratio
	function (object, ...) 
	{
		sqrt(object$var)/object$ratio
	}
	<environment: namespace:survey>
	> 

am i overlooking something?  if not, please remove `svycv`  ..sorry if i'm making a mistake and thanks for the hard work on this  :)

**Comment by guilhermejacob** [comment]
Yes, it should not exist. Removed it. Thanks for the heads up!

**Comment by ajdamico** [comment]
thanks guilherme!  https://github.com/DjalmaPessoa/convey/commit/cdf96219378d5085f4b8b8cea268e97990ee8977

**Comment by guilhermejacob** [comment]
There's something odd with the survey `cv` and `svycv`. The svygei with `epsilon = 2` should be equal to half the squared coefficient of variation. For `svycv`, it does; for survey `cv`, it doesn't.

The formulas for svy and svygei come from independent articles and match.
Here's the main article for svycv: [http://www.jos.nu/Articles/abstract.asp?article=13141].

Any ideias on that?

**Comment by ajdamico** [comment]
hi, `survey::cv` will not come close if the variances aren't the same computation (see below).  if the coefficient of variation requires a separate computation for certain classes of `cvystat` objects, you should add a `convey::cv.cvystat` method rather than adding an entirely separate `svycv` function, i think?  it is okay to write a `convey::cv.cvystat` method that either does something or calls `survey::cv.default` depending on some test


	library(survey)
	data(api)
	z <- apiclus1

	dclus1<-svydesign(id=~dnum, weights=~pw, data=z, fpc=~fpc)


	incvar <- z$api00
	x <- z[ "api00" ]
	design <- dclus1


	# lumley's variance calculation
	pweights <- 1/design$prob
	psum <- sum(pweights)
	average <- colSums( x * pweights/psum)
	x <- sweep(x, 2, average)
	svyrecvar(x * pweights/psum, design$cluster, design$strata, 
			design$fpc, postStrata = design$postStrata)

			
	# your non-squared code from
	# https://github.com/DjalmaPessoa/convey/commit/cdf96219378d5085f4b8b8cea268e97990ee8977
	w <- 1/design$prob
	average <- sum( w * incvar ) / sum( w )
	rval <- sum( w * ( ( incvar/average ) - 1 )^2 ) / sum( w )
	rval <- sqrt(rval)
	u_i <-(1/2) * ( ( (incvar/average - 1)^2)/rval - (2*incvar/average - 1)*rval )/sum(w)
	svyrecvar(u_i/design$prob, design$cluster,
		design$strata, design$fpc, postStrata = design$postStrata)

**Comment by guilhermejacob** [comment]
But you do think it's a good ideia to keep it, right?

**Comment by ajdamico** [comment]
i do not think that the user should ever be expected to use `svycv` --  if
you need it for intermediary calculations, that's fine, but i think the
user's call should be simply

    cv( svyxyzfun( ~ incvar , design ) )

**Comment by guilhermejacob** [comment]
Ok, I don't think it will be necessary, then. But, for the record, it matches the svygei (:
