### ISSUE TITLE
svyzenga takes too long on linearized samples. possible to improve performance?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#69]
@guilhermejacob problem point is https://github.com/DjalmaPessoa/convey/blob/master/R/svyzenga.R#L144-L155

in a call like

    svyzenga(~eqincome, des_eusilc, na.rm = FALSE)

you are making and remaking a vector

    length(u_l)
    [1] 14824

this strategy is causing the slowness.  i believe a faster strategy would be to make `y` into a matrix

    z <- matrix( rep( y , length( y ) ) , nrow = length( y ) )

and then perform these three lines of computations into a separate small function and then run them across the whole matrix in a vectorized manner https://github.com/DjalmaPessoa/convey/blob/master/R/svyzenga.R#L147-L151 with `sapply` or `apply` with `MARGIN=2`

**Comment by ajdamico** [comment]
@guilhermejacob if you post a question on stackoverflow, please point me to it in case i'm able to suggest any improvements..thanks!

**Comment by ajdamico** [comment]
http://stackoverflow.com/questions/37617125/how-can-i-revise-my-code-to-improve-my-processing-speed/

**Comment by ajdamico** [comment]
@guilhermejacob changing this to v0.2.0 because svyzenga is pretty slow at the moment

**Comment by ajdamico** [comment]
* checking examples ... OK
	Examples with CPU or elapsed time > 5s
				user system elapsed
	svyzenga   97.63   0.04   97.93
	svylorenz  19.65   0.07   19.77
	svyqsr      8.69   0.05    8.80
	svyrmpg     8.32   0.07    8.43
	svypoormed  7.63   0.08    7.72
	svyarpr     7.04   0.06    7.11
	svyisq      5.37   0.04    5.49
	svygei      5.08   0.13    5.24
	svyrmir     5.10   0.04    5.17
	svyarpt     5.01   0.04    5.10

**Comment by ajdamico** [comment]
@guilhermejacob once they speed up, please move the \dontrun{ line to the MonetDBLite block instead, so it runs them in-memory

https://github.com/DjalmaPessoa/convey/commit/9cc485040ebd690f7cc041e1072d954a47521ddf

**Comment by guilhermejacob** [comment]
I think it is good enough now. Check https://github.com/DjalmaPessoa/convey/commit/41cffc786696da41b4d0534953aa61838fac6cd4.
Feel free to re-open if you think this can be improved.

**Comment by ajdamico** [comment]
hi, i do think the speed can be improved here..  svyzenga still requires 13 seconds on a small dataset but the stackoverflow solution was near-instantaneous?


	 system.time( svyzenga(~eqincome, des_eusilc_pos_inc) )
	   user  system elapsed 
	  12.99    0.00   13.00

**Comment by guilhermejacob** [comment]
Should I call `data.table` or the other method? It seems a bit complicated. Rcpp?

**Comment by ajdamico** [comment]
i think http://stackoverflow.com/a/37697979/1759499 is the best solution?  free of dependencies..

**Comment by ajdamico** [comment]
[Rcpp lin zenga.txt](https://github.com/DjalmaPessoa/convey/files/361726/Rcpp.lin.zenga.txt)

review whether attached `Rcpp` solution makes sense

**Comment by ajdamico** [comment]
[svyzenga with Rcpp - example.zip](https://github.com/DjalmaPessoa/convey/files/362692/svyzenga.with.Rcpp.-.example.zip)

**Comment by ajdamico** [comment]
comment from @DjalmaPessoa 

Looking at the version of svyzenga I just sync from github, I believe we can improve the efficiency working with vectors and matrices. There are 5 terms in expression for linearization in the function lin_zenga:

Use: 

term1 <-  - matrix(( N - H_y)*( Tot - K_y ) / ( N * H_y* K_y ), ncol=1)
term2 <- (1/N^2) * sum( w * ( Tot - K_y ) / K_y )  # scalar

term3 <- matrix ((incvar/N) * sum( w * (N - H_y) / (H_y * K_y) ),ncol=1)

create the matrices:

upper <- matrix (0, nrow=length(incvar), ncol=length(incvar))
upper <- 1* (col(upper)>=row(upper))
lower <- 1* (row(upper)>=col(upper))

term4 <-upper %*% matrix(w * ( ( Tot - K_y ) / ( H_y^2 * K_y ) ),ncol=1)

term5 <- matrix(Tot*incvar/N, ncol=1)* lower%*% matrix(( w * ( ( N - H_y ) / ( H_y * K_y^2 ) ) , ncol=1 )

then sum: term1+term2+term3+term4+term5

I need to check if the matrices upper and lower are correct. Also it is supposed that incvar is sorted, also have to consider the ties.

**Comment by ajdamico** [comment]
@guilhermejacob i think that @DjalmaPessoa is correct -- i have made his recommended edits and `svyzenga` is now fast!

https://github.com/DjalmaPessoa/convey/commit/bd1bdc652c209691ea92a7dd2bf8167d14b69b6d

re-install the package and check it out  :)

	> system.time(svyzenga(~eqincome, des_eusilc))
	   user  system elapsed 
	   0.01    0.01    0.03 


note: this *does* change the result because the previous implementation looks like it included ties.  i have attached my walk-through of the change that explains how ties were previously dealt with and how they are dealt with under this new implementation

[vectorized svyzenga solution.txt](https://github.com/DjalmaPessoa/convey/files/362835/vectorized.svyzenga.solution.txt)

**Comment by guilhermejacob** [comment]
@DjalmaPessoa was absolutely right! Just amazing!
I'll check the issue with ties.
