### ISSUE TITLE
could you confirm that this was a mistake?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#7]
i have changed it in future commits, so now `lin` gets passed in rather than `lin_qsr` since i think it was wrong when `comp=TRUE` ?

https://github.com/DjalmaPessoa/convey/blob/e729565af08d60c466d4a935c23761755b83932b/R/svyqsr.R#L71-L73

**Comment by DjalmaPessoa** [comment]
already fixed
