### ISSUE TITLE
Comparing results from svyisq and svylorenz

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#70]
#  this is to show the difference between result from svyisq and svylorenz functions of convey
    library(survey)
    library(vardpoor)
    data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
    library(convey)

```
des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
des_eusilc <- convey_prep( des_eusilc )


# comparing svyisq and svylorenz

result <- rep(0, length(seq(0,1,.05)))
q <-  rep(0, length(seq(0,1,.05)))
tot <-  rep(0, length(seq(0,1,.05)))

# these are the results we would get using svyisq

for(i in 1: length(seq(0,1,.05))){
p <-   seq(0,1,.05)[i]
q[i] <- as.vector((svyquantile(~eqincome, des_eusilc, p, method= "constant")))

tot[i] <- svytotal(~I(eqincome* (eqincome< q[i])),des_eusilc)

result[i] <- tot[i]/coef(svytotal(~eqincome,des_eusilc))
}

# correspondent estimates by svylorenz

lorenz_est<- svylorenz( ~eqincome , design = des_eusilc, quantiles = seq(0,1,.05),
  alpha = .01 )

lorenz_est$quantiles

## there is a small difference between estimates
```

**Comment by ajdamico** [comment]
@DjalmaPessoa cleaner to have one assignee at a time
@guilhermejacob think you could untangle why the estimates differ?  if you have questions, please switch the assignee back to djalma
thanks!!

**Comment by guilhermejacob** [comment]
I rewrote the svylorenz to match svyisq with linear smoothing.

```
# this is to show the difference between result from svyisq and svylorenz functions of convey
library(survey)
library(vardpoor)
data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
library(convey)

des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
des_eusilc <- convey_prep( des_eusilc )


# comparing svyisq and svylorenz

result <- rep(0, length(seq(0,1,.05)))
q <-  rep(0, length(seq(0,1,.05)))
tot <-  rep(0, length(seq(0,1,.05)))

# these are the results we would get using svyisq

for(i in 1: length(seq(0,1,.05))){
  p <-   seq(0,1,.05)[i]
  q[i] <- as.vector((svyquantile(~eqincome, des_eusilc, p, method= "linear")))
  
  tot[i] <- svytotal(~I(eqincome* (eqincome <= q[i])),des_eusilc)
  
  result[i] <- tot[i]/coef(svytotal(~eqincome,des_eusilc))
}

# correspondent estimates by svylorenz

lorenz_est <- svylorenz( ~eqincome , design = des_eusilc, quantiles = seq(0,1,.05),
                        alpha = .01 )

lorenz_est$quantiles

# Test for equality:
lorenz_est$quantiles == result

# the only one that does not match has a very small difference
```

Is that ok?

**Comment by guilhermejacob** [comment]
On that solution, a new problem emerges. The following graph is the results of:
```
svylorenz( ~age , design = des_eusilc, quantiles = seq(0,1,.01), empirical = TRUE, alpha = .05 )
```
![rplot](https://cloud.githubusercontent.com/assets/12241665/15843663/4f875a44-2c3a-11e6-9eb7-9cd04e373a90.jpeg)

This breaks the convexity of the Lorenz curve.
The previous formula would result in:
![rplot02](https://cloud.githubusercontent.com/assets/12241665/15843780/26fe4686-2c3b-11e6-90ff-3e6fc6a0899f.jpeg)

**Comment by DjalmaPessoa** [comment]
the difference seems to be small, perhaps you shoud keep the previous formula that gives  convexity.

**Comment by guilhermejacob** [comment]
Writing an article about this right now.

**Comment by guilhermejacob** [comment]
I don't think this is a problem anymore as `svylorenz` is able to replicate [Jann (2016)](http://repec.sowi.unibe.ch/files/wp15/jann-2016-lorenz.pdf).
So, it's not that the functions are wrong; they just differ on the definition of the quantile.
I'm closing it, but reopen if needed.

**Comment by ajdamico** [comment]
nice
