### ISSUE TITLE
initiate a comparisons to outside sources vignette

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#71]
document this code (and other snippets) into a `convey` vignette that quickly shows users the various computations

https://github.com/DjalmaPessoa/convey/issues/67#issuecomment-223777356

**Comment by ajdamico** [comment]
additional discussion that belongs in a vignette
https://github.com/DjalmaPessoa/convey/issues/67#issuecomment-223957696

cc @DjalmaPessoa

**Comment by ajdamico** [comment]
@DjalmaPessoa i've added the text from your second comment to the book here:  https://guilhermejacob.github.io/context/1-9-comparisons-to-other-software.html#comparisons-to-other-software

could you provide a bit more of an explanation of what's happening here and why the numbers line up?  you can edit this in `index.Rmd`  thanks!

**Comment by DjalmaPessoa** [comment]
From where did you get this?
 
In all comparisons the `se` is obtained using the function  `SE_lin2`. 
The examples serve only to show that the `linearized variable`  computed from convey and from vardpoor are the same. So,  if  we estimate the `se` for the `linearized  variable` using the same method the results should be the same.
The estimates used are very basic: total, ratio and median, so I suggest you discard this part.

To show that the linearized variable variable from convey and survey are the same just use one of the examples before.

**Comment by ajdamico** [comment]
i got it from the links above.  scroll up and look for 67.  could you please make whatever edits to this section that you feel are necessary?  thanks

**Comment by DjalmaPessoa** [comment]
I'm in favor of discarding it all! I don't understand the point of it.
So I'm against editing it.

**Comment by ajdamico** [comment]
hi, i had added it because you made some good points (links below) but i don't feel strongly about it.  i've taken out that subchapter.  you wrote a lot of stuff here, if you think any of it belongs elsewhere in the book, please add it?  thanks djalma :)

https://github.com/DjalmaPessoa/convey/issues/67#issuecomment-223777356
https://github.com/DjalmaPessoa/convey/issues/67#issuecomment-223957696
