### ISSUE TITLE
should zeroes be allowed to pass through the `incvar` variable into `calc.atkinson`?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#74]
in both the svydesign and svrepdesign methods, below the block starting with

    warning( "The function is defined for strictly positive incomes only.  Discarding observations with zero or negative incomes.")

a zero-income observation with a positive weight can pass through that block and remain in the `incvar` vector because the negatives and zeroes might sometimes only be reset to zeroes

    incvar[ nps ] <- 0

is that correct?  thanks!

**Comment by guilhermejacob** [comment]
I'll remove the `if (length(nps) > length(design$prob)) incvar <- incvar[!nps] else incvar[ nps ] <- 0` line

**Comment by guilhermejacob** [comment]
It's better to keep that way, because it ensures that the vector has the same length.
Can I close it?

**Comment by ajdamico** [comment]
it was just a question :) close whenever

**Comment by guilhermejacob** [comment]
Can I revert to an the "c3aaef76fc1ed9273f22c82a581c7db923b18c07" commit? I don't know how to.

**Comment by ajdamico** [comment]
can you click the revert button?

https://help.github.com/desktop/guides/contributing/reverting-a-commit/

**Comment by guilhermejacob** [comment]
Should've closed it before. Not an issue anymore.
