### ISSUE TITLE
should the type_thresh= parameter of svyfgt() default to one of the three choices?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#75]
maybe not, just curious.  thanks!

**Comment by DjalmaPessoa** [comment]
Poverty studies at IBGE use this FGT indicator with a fixed poverty threshold in terms of minimum income. Perhaps this should be the default?

**Comment by ajdamico** [comment]
@DjalmaPessoa in your commit, you only changed the `svydesign` method and not the `svyrep.design` method?  should it default to `abs` for both?  or just the linearized version?  thanks!

https://github.com/DjalmaPessoa/convey/commit/ada73462e7aa75772511186fde8cb23d846c8bbe

**Comment by DjalmaPessoa** [comment]
both! I've already changed, but it is not working:

svyfgt(~eqincome, des_eusilc, g=0,  abs_thresh=10000)

Error in if (!(list(...)[["type_thresh"]] %in% c("relq", "abs", "relm")))
stop("type_thresh= must be \"relq\" \"relm\" or \"abs\".  see ?svyfgt for
more detail.") :
  argument is of length zero

**Comment by ajdamico** [comment]
sorry does this fix it?  sorry for breaking things

https://github.com/DjalmaPessoa/convey/commit/1eb9a1df64bfce73bff328d41cb1d752f5b121ea

**Comment by ajdamico** [comment]
this appears to work now, so closing the issue  :)
