### ISSUE TITLE
should `order=` and `percent=` be passed to svyarpt?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#76]
i think if the user specifies a non-default for `order=` or `percent=` in `svyarpr.survey.design` then those non-defaults should carry through to when svyarpr calls `svyarpt`

i made this change here, could you please review and confirm or revert the change?  thanks!

https://github.com/DjalmaPessoa/convey/commit/61e2a11110c63b5a28e168f24b726917ddc8e57c

**Comment by ajdamico** [comment]
second example of this, with my change:
https://github.com/DjalmaPessoa/convey/commit/ee5051892e2631516ddfe7694052617f49b7ec56

**Comment by ajdamico** [comment]
third example of this, with my change:
https://github.com/DjalmaPessoa/convey/commit/9fa871f4460e19f3cb53eef826f51096c047c383

**Comment by DjalmaPessoa** [comment]
The usual is order=.5 and percent = .6, as used by Eusilc. But it could be
of interest to study the effect of changing this and using different
thresholds. So I confirm the change. Thanks.
