### ISSUE TITLE
should `0.5` be hardcoded where it appears in `svypoormed` or should it be replaced with `order`?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#77]
there are lots of instances of `0.5` in this script that i am not sure about -- if the user changes the `order=` parameter to `0.75` then should all of those 0.5s change to 0.75 as well?  thanks

https://github.com/DjalmaPessoa/convey/blob/master/R/svypoormed.R

**Comment by DjalmaPessoa** [comment]
The arguments **order** and and **percent** are passed to **svyarpt** and **svyapr** used inside **svypoomed**. If the user chooses another threshold he could change. Might be interesting to allow other possibilities like in **svyfgt**. But that's another story.
