### ISSUE TITLE
discard some functions in deriv_rules?

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#79]
There are some functions in **deriv_rules** that were intended as auxiliary functions and weren't used in other functions.  The idea was to use them as building blocks to derive the linearized variable of more complex estimators from the linearized variable of simpler estimators. In fact, this is done for some functions of the library convey by means of the function **contrastinf**.

The function **contrastinf** is similar to the function **svycontrast** of the library **survey** beeing  more general.

In order to apply  **contrastinf** to get the linearized variable of an estimator g( T1,T2,T2,...) it is needed to know for each Ti a list with components :  **value** and **lin**. That is the reason why some  functions in convey have the attribute **lin**.

Considering this:

1. Should we discard functions like:  **icons, itot,cl_inf, prod_inf, ratio_inf**, etc, that were not used?
2. Should  all the functions in convey include the **lin attribute**?
3.  How to include the **lin attribute** in the case of using **svyby**?

**Comment by ajdamico** [comment]
hi,

1. i don't think those functions were ever intended to be used by the end-user.  since you (the package author) also don't use them, then i would recommend discarding them.  if you think it's likely that some subset of users will actually want to use them, then you'll need to document them and give a real usage example instead.  since they do not have the `#' @export` line in front of them, they are actually invisible to users (unless people read through the source code, which is unlikely)

2. what's the utility of the `lin` attribute for users?  is it likely that anyone will ever need this?  if so, then it would be good for you to document how/when someone might want this attribute.  if only very advanced users will ever need it, i think you can discard it.

3. if you decide to keep the `lin` attribute, then please open a separate issue for me with a usage example of `svyby` that describes the desired behavior, and i can try to get it working  :)

**Comment by DjalmaPessoa** [comment]
1. The initial idea was combine the linearized functions of simple estimators to get, by using the function  contrastinf, the linearized function of more complex estimators. The formulas for linearized variables of estimators like Gini, qsr are complex. In convey we get the linearized variables using the function contrastinf from simpler exepressions. The idea was to explore this as much as possible. Then, I realized that the number of  final estimators  would not compensate the effort. But I still like the idea.

2. To implement the idea in 1,  the attribute lin is needed. For example, to get the linearized variable in the functions svygini, svygpg, svysqr, svyrmir and svyrmpg I used the  lin attribute and the function contrastinf. 

3. Using the svyby to get estimates for domains makes unnecessary to know the lin attribute for domain. 
I wonder what happens with the lin attribute for domains when the object has lin attribute for the whole population? For example:

res_pop <- svyarpr( ~eqincome , design = des_eusilc )
str(res_pop) 
there is an attribute lin.

res_dom <- svyby(~eqincome , design = des_eusilc,FUN= svyarpr, by= ~db040)
str(res_dom)

there is no attribute lin. Why svyby throws it away ? Not that I think it is needed.

**Comment by ajdamico** [comment]
hi, look inside `survey:::svyby.default` for the functions `unwrap` and `unwrap2` -- neither of these maintain the `lin` attribute, so in order for you to keep that attribute with a `svyby` call, you will need to write an `unwrap.cvystat` method that works in all cases.  i am still unclear when a user would ever need to break into these background functions themselves, so i would recommend discarding them.  it is nice to keep the background functions minimal, but it sounds like you ended up not using them -- so i would vote to remove them from the package completely?  if you keep them in the package, you'll need to document them better and provide examples of how/when a user might ever need them..thanks!

**Comment by DjalmaPessoa** [comment]
I'd like to separate to issues:
1. the use o the lin attribute in convey
2. auxiliary functions not used elsewhere

1. To have an idea on how much the **lin** attribute is used in convey, just make a search for the expression attr( * , "lin")  in all files of the directory R . So if had to discard the **lin** attribute I'd have to reprogram almost all functions! 

2. The functions in the directory deriv_rules that are not used, I believe shoul be discarded. I'll keep them to use in a future version of convey, who knows ...?

**Comment by ajdamico** [comment]
i think you should remove the functions entirely.  you can search the code history on github if you ever want to bring them back.  call on skype if you want to talk about this more?  i am around..  but i think the functions that are not used should be deleted

**Comment by DjalmaPessoa** [comment]
they were already discarded!

**Comment by ajdamico** [comment]
could we close this issue then?  thanks
