### ISSUE TITLE
can tests.R be integrated into the testthat framework?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#8]
i'm not sure why it's a standalone script?  can it be used within testthat?  (maybe it already is and i'm just misunderstanding)

**Comment by DjalmaPessoa** [comment]
I was just begining to use testhat. Maybe it is possible to use the tests
in the testhat. I'll check it out.
Em sábado, 19 de setembro de 2015, Anthony Damico <notifications@github.com>
escreveu:

**Comment by ajdamico** [comment]
it looks like you've added a bunch of tests to testthat, which is great!  can the file tests.R be deleted now, or is that part of tests.R?  if you think this issue is resolved, you can close it  :)

**Comment by DjalmaPessoa** [comment]
The tests included so far are working except for the the function svygpg.
When executed in the console it works but not in testthat. The error
message is related to the vardpoor use.
The worse of it is that it breaks the test file sequence and subsequent
tests are not done.
To see what I mean just use devtools:::test().

**Comment by DjalmaPessoa** [comment]
All tests moved to testthat
