### ISSUE TITLE
highlight function contrastinf in deriv_rules.R

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#80]
I'd  like to include a documentation for the function contrastinf  and perhaps to move it to another place?

**Comment by ajdamico** [comment]
i have moved it to its own function in this commit..  you'll have to edit it from there?
https://github.com/DjalmaPessoa/convey/commit/7cb55c3c69dd220e8f63be2c0220506d2f67763d

**Comment by ajdamico** [comment]
hi, could you add more descriptive text in this block of examples?  what do each of these objects mean?  what purpose do they serve?  right now, this is just a bunch of code that might not make sense to a user..  commenting this examples block would make contrastinf() much more understandable to others  :)  thanks!

https://github.com/DjalmaPessoa/convey/blob/master/R/contrastinf.R#L26-L45

**Comment by DjalmaPessoa** [comment]
I just made a commit improving the examples in contrastinf(). Please check if it is okay.

**Comment by ajdamico** [comment]
https://github.com/DjalmaPessoa/convey/commit/2e63144d65170826b016fefd035080d77451f194

**Comment by ajdamico** [comment]
@DjalmaPessoa i really don't see anyone ever using a function like this..  i think it's too technical, and users will not care?  it does not hurt to leave it in as you have it -- lumley does this with some survey functions like `?bootweights` but they still have more documentation than you have written.  if you ever want (very technical) people to use this, you should add more description text about why it is useful and under what circumstances people might benefit from it..  :)

**Comment by DjalmaPessoa** [comment]
I don't agree with. You could say the same thing with respect to the
function svycontrast of the library survey, which I think it is similar and
a very useful function. Perhaps you are not seeing the reach of it. Sorry.
I used it in many functions in the library survey as you can check.

**Comment by ajdamico** [comment]
awesome
