### ISSUE TITLE
default still not working

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#83]
> svyqsr(~eqincome, des_eusilc )
Error in if ("alpha" %in% names(list(...)) & list(...)[["alpha"]] > 0.5) stop("alpha= cannot be larger than 0.5 (50%)") : 
  argument is of length zero

**Comment by ajdamico** [comment]
good catch thanks
https://github.com/DjalmaPessoa/convey/commit/6b9d085cb33522b858ed995ae7fb2f1a366bb77d
