### ISSUE TITLE
test examples in convey

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#85]
Please run:

library(convey)
library(testthat)
test_examples("C:/Users/owner/Documents/GitHub/convey/man")

and see what's going on!

**Comment by ajdamico** [comment]
these commits fix the first two problems..
https://github.com/DjalmaPessoa/convey/commit/64fbb36bcace27a30b36a9707a6d9dda300e1550
and
https://github.com/DjalmaPessoa/convey/commit/ba0c1ace037eaa84bd94955724b7f4f4b3757502
