### ISSUE TITLE
testing the examples 

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#86]
Please check:

> svyzenga(~eqincome, des_eusilc_rep, na.rm = FALSE)
Error in Y_fn(x, weights, 0, big_t) : object 'big_t' not found
In addition: Warning message:
In svyzenga.svyrep.design(~eqincome, des_eusilc_rep, na.rm = FALSE) :
  The function is defined for strictly positive incomes only.

**Comment by guilhermejacob** [comment]
big_t (or T) is a short for TRUE 😄 
fixed on my last commit

**Comment by ajdamico** [comment]
when an issue has been fixed please don't forget to close it  ;)

**Comment by ajdamico** [comment]
also, sorry, that was dumb of me to change
