### ISSUE TITLE
fix warnings from devtools::check()

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#87]
get lots of:  "no visible global function definition for..." how to fix it?
have to include the libraries in the Description?

**Comment by ajdamico** [comment]
what check did you run?

**Comment by DjalmaPessoa** [comment]
in the convey project
devtools::check()

**Comment by DjalmaPessoa** [comment]
I've got the message:
Consider adding
  importFrom("grDevices", "adjustcolor")
  importFrom("graphics", "abline", "lines", "plot", "points", "polygon")
  importFrom("stats", "approxfun", "coef", "deriv", "model.frame",
             "model.matrix", "na.pass", "printCoefmat", "qnorm", "terms",
             "terms.formula", "update", "weights")
  importFrom("utils", "tail")
to your NAMESPACE file.

**Comment by ajdamico** [comment]
@DjalmaPessoa i am still working through this..might take a few more days, but i will get there  :)

**Comment by ajdamico** [comment]
fixed! with the exception of idIsCurrent() but see e-mail to hannes about how to deal with that..  that is a function in the survey package that we cannot change
