### ISSUE TITLE
why do so many arguments pass na.rm= into `densfun` if the function does not use it?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#88]
hi, please take a look at these two pages..  the `na.rm=` parameter does not get used in the function but it gets passed in.  should it be used somehow or can each of these passes from the previous function be removed?  thanks!

https://github.com/DjalmaPessoa/convey/search?utf8=%E2%9C%93&q=densfun%28

**Comment by DjalmaPessoa** [comment]
it does get used in function:

if(na.rm){
    nas<-is.na(incvar)
    design<-design[!nas,]
    if (length(nas) > length(design$prob))
      incvar <- incvar[!nas]
    else incvar[nas] <- 0
  }

**Comment by ajdamico** [comment]
duh, sorry
