### ISSUE TITLE
add documentation for the `abs_thresh=` parameter of `svyfgt`

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#91]
hi, this block of @params lines is missing the `abs_thresh` parameter.. please add a description of what this parameter is.  thanks!

https://github.com/DjalmaPessoa/convey/blob/master/R/svyfgt.R#L5-L14

**Comment by DjalmaPessoa** [comment]
it is done

**Comment by ajdamico** [comment]
close the github issue if it is done?  ;)
