### ISSUE TITLE
computeQuantiles needs to be documented or the `export` should be removed

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#93]
currently the `@export` tells R that this function should be accessible by users.  but there is no documentation above the function and so it's throwing an error in the CRAN check..  if you expect that users will want to use this function, then you'll need to add documentation.  but if it is internal-only, then just remove the @export

    #' @export
    computeQuantiles <- function(xx, w, p = quantiles) {

**Comment by DjalmaPessoa** [comment]
this function was copied from the library survey and it is only to be used internally.  We should acknowlledge the authorship.

**Comment by ajdamico** [comment]
is `computeQuantiles` in the `survey` package somewhere?  if we can use that function directly rather than copying it over into `convey` then that would be better?

**Comment by DjalmaPessoa** [comment]
this function is inside

survey:::svyquantile.survey.design

**Comment by ajdamico** [comment]
ahh damn, then we'll need to re-define it within convey..  i agree it would
be good to attribute authorship to dr. lumley
