### ISSUE TITLE
functions that don't use convey_prep

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#94]
The only functions that use information from the whole population are those that work with a poverty threshold for the whole country, like the arpt. All functions that adopt the arpt line have to use the full_svydesign and consequently convey_prep. convey_prep is used also in the examples of functions that don't use the full_design. Is this really necessary?

**Comment by ajdamico** [comment]
i think it is easier to simply tell users to run that single line of code and not worry about things rather than explaining the nuance here?  but re-open and propose an alternative if you disagree?  :)  i am open to a change so long as it doesn't make things too complicated for users..

**Comment by DjalmaPessoa** [comment]
The function svyarpt is used only inside the functions: svyfgt, svyarpr,
svypoormed and svyrmpg.For these we need to use the full_design. So in the
documentation (details) and examples for these functions it should be
mentioned that poverty line used is based upon the whole population. Just
for these functions, it would be needed to use convey_prep, and when using
it should be mentioned the reason: the poverty line was computed for the
whole population.  This would make things much more clear.
If you think this complicated, we should at least be uniform, including the
call to convey_prep in the examples for all functions.

People at IBGE, who are not naive users, were not able to see what was
behind the use of convey_prep. It was complicated to them...

**Comment by ajdamico** [comment]
make whatever changes you think will be easiest for users :)

**Comment by DjalmaPessoa** [comment]
I've made a search for convey_prep in the R directory and it is included all over, so it would be hard to discard it where not needed. So I think we should leave as it is.

Could you please explain in the convey_prep documentation why the function is needed?  also it would be good, for the sake of uniformity, to include  convey_prep call to all the examples.  Also  there  are some functions with a call to convey_prep, even when not needed, and some with no call.

For instance, there is no call to convey_prep in the svygini examples.

**Comment by ajdamico** [comment]
here are the relevant commits:

https://github.com/DjalmaPessoa/convey/commit/5ba51dcc28137272df26ee18b74b15d272cd4caa

https://github.com/DjalmaPessoa/convey/commit/fd8231c7b22938e4b3471e28f3789f1263698179
