### ISSUE TITLE
two test-svygini.R expect_equal testthat lines currently fail

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#95]
look for the comment--

    # currently fails

--i have disabled them for now so we pass the CRAN check but they should be working before version 0.2.0

https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-extract_svygini.R

related: https://github.com/DjalmaPessoa/convey/issues/65

**Comment by DjalmaPessoa** [comment]
I've discarded conditions failling.

**Comment by ajdamico** [comment]
are they failing because (a) we no longer need to test them or because (b) they are not resolved yet?  if (b) then i think you should revert this commit and re-open to deal with for version v0.2.0.

https://github.com/DjalmaPessoa/convey/commit/5ebe70f84d1c384b8adec54e7e4f8e1864fa615b

**Comment by DjalmaPessoa** [comment]
1. for svyqsr, I believe the reason is mistake in vardpoor when computing the linearized variable;
2. for svygini,  there is no apparent reason, at least I was not able to figure it out.

**Comment by ajdamico** [comment]
okay, i have reverted your commit then -- we should eventually try to get those lines working properly or at least explain what's going on.  but they should stay commented out so it doesn't disrupt the CRAN checks for 0.1.0

**Comment by ajdamico** [comment]
looks good now
