### ISSUE TITLE
one test-svyqsr.R expect_equal testthat line currently fails

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#96]
look for the comment--

    # currently fails

--i have disabled them for now so we pass the CRAN check but they should be working before version 0.2.0

https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-extract_svyqsr.R

related: https://github.com/DjalmaPessoa/convey/issues/65

**Comment by DjalmaPessoa** [comment]
I've discarded the conditions that were failling. But still there are some warnings...

**Comment by ajdamico** [comment]
are they failing because (a) we no longer need to test them or because (b) they are not resolved yet?  if (b) then i think you should revert this commit and leave this issue open to deal with for version v0.2.0.  if (a) then please close this issue as well..

https://github.com/DjalmaPessoa/convey/commit/5ebe70f84d1c384b8adec54e7e4f8e1864fa615b

**Comment by ajdamico** [comment]
i guess (a) then?  :)
