### ISSUE TITLE
0.1.0 through winbuilder

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#97]
you should put the whole package through this website's check before finally submitting to cran..

http://win-builder.r-project.org/

**Comment by DjalmaPessoa** [comment]
I'll do it as soon as we finish the checking

**Comment by ajdamico** [comment]
that is fine but it is also okay to send version 0.1.0 to cran while we are still fixing things..  it is still considered experimental until 1.0.0 so it doesn't have to be perfect..  getting outsiders interested in the project will make it better software :)

**Comment by ajdamico** [comment]
@DjalmaPessoa @guilhermejacob this is the last issue before cran submission?  please include a note described in the e-mail exchange with hannes regarding the warnings, otherwise the cran maintainers will reject the package

**Comment by guilhermejacob** [comment]
ok, will do as soon as I finish testing. And I'll take Djalma's solution and copy on my scripts :P

**Comment by ajdamico** [comment]
@guilhermejacob this issue is assigned to djalma, he needs to submit to cran since he is the maintainer

**Comment by guilhermejacob** [comment]
ah, ok (:

**Comment by DjalmaPessoa** [comment]
The first sentence in the site is:

This service is intended for useRs who do not have Windows available for
checking and building Windows binary packages. Windows useRs can easily
build and check their packages on Windows with the setup described in the R
Installation and Administration manual.

I have windows available for checking and building the Windows binary
package!

**Comment by ajdamico** [comment]
it is still a good check

**Comment by DjalmaPessoa** [comment]
What should I use:


   - R-release: R-release, currently R-3.3.1 or
   - R-devel: R-devel, to be R-3.4.0 ?

**Comment by ajdamico** [comment]
current, i guess?  i am not sure

**Comment by DjalmaPessoa** [comment]
I've already uploaded and got the response:

File name: convey_0.1.0.tar.gz
File Size: 52422 bytes
Content type: application/x-gzip

**Comment by DjalmaPessoa** [comment]
I guess it was supposed to have a Maintainer field in the Description?

**Comment by ajdamico** [comment]
yes, please add yourself as the maintainer

**Comment by ajdamico** [comment]
@DjalmaPessoa i have fixed the error.  please run through winbuilder again and submit if it's OK.  

    ** running tests for arch 'i386' ... ERROR

remember to note that this warning is _expected_ and include the explanation..thanks

    Warning: 'isIdCurrent' is deprecated.

**Comment by DjalmaPessoa** [comment]
to run through winbuilder i just uploaded the file convey_0.1.0.tar.gz. Where should I include this note? The only possiblity would be inside the package, in this case where is the right place?

**Comment by ajdamico** [comment]
no, the CRAN submission form has a box for you to write the note

**Comment by DjalmaPessoa** [comment]
so, I just need to send the note to CRAN, not to the winbuilder?

**Comment by ajdamico** [comment]
hopefully v0.1.0 will be accepted so closing this issue!
