### ISSUE TITLE
error in test-svyatk.R

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#98]
test_file("C:/Users/owner/Documents/GitHub/convey/tests/testthat/test-svyatk.R")

Error in eval(expr, envir, enclos) : 
  could not find function "calcAtkinson"

**Comment by ajdamico** [comment]
https://github.com/DjalmaPessoa/convey/commit/e1f2979831af1b86ee8b101781e0de91268e6e0f should fix this
